/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface ChatMessages {
  fromId: string;
  id: Generated<string>;
  phraseId: string;
  readAt: Timestamp | null;
  sentAt: Generated<Timestamp>;
  toId: string;
}

export interface EventRuns {
  endedAt: Timestamp | null;
  eventId: string;
  phasesReleasedAt: Generated<Json>;
  startedAt: Generated<Timestamp>;
  status: string;
  teacherId: string;
}

export interface Friendships {
  acceptedAt: Timestamp | null;
  createdAt: Generated<Timestamp>;
  fromId: string;
  id: Generated<string>;
  status: Generated<string>;
  toId: string;
}

export interface Messages {
  audience: Json | null;
  body: string;
  broadcastId: string | null;
  createdAt: Generated<Timestamp>;
  id: Generated<string>;
  kind: string;
  readAt: Timestamp | null;
  senderId: string | null;
  studentId: string;
}

export interface Missions {
  createdAt: Generated<Timestamp>;
  description: Generated<string>;
  difficulty: string;
  eventId: string | null;
  eventPhase: number | null;
  icon: string;
  id: string;
  kind: Generated<string>;
  minLevel: Generated<number>;
  questions: Generated<Json>;
  rewardCoins: Generated<number>;
  rewardItem: Json;
  rewardXp: Generated<number>;
  task: Json | null;
  teacherId: string;
  title: string;
}

export interface Offers {
  buyerId: string;
  createdAt: Generated<Timestamp>;
  id: Generated<string>;
  item: Json;
  price: number;
  sellerId: string;
}

export interface Sessions {
  createdAt: Generated<Timestamp>;
  expiresAt: Timestamp;
  id: Generated<string>;
  studentId: string | null;
  teacherId: string | null;
  tokenHash: string;
}

export interface ShopItems {
  collection: string | null;
  cosmetic: Json | null;
  createdAt: Generated<Timestamp>;
  description: string;
  eventItemKey: string | null;
  featured: Generated<boolean>;
  hidden: Generated<boolean>;
  icon: string;
  id: string;
  name: string;
  price: number;
  rarity: string;
  slots: number | null;
  sold: Generated<number>;
  value: Generated<number>;
  xp: Generated<number>;
}

export interface Students {
  avatar: Generated<Json>;
  bonusSlots: Generated<number>;
  coins: Generated<number>;
  completedMissionIds: Generated<Json>;
  createdAt: Generated<Timestamp>;
  email: string;
  equipped: Generated<Json>;
  events: Generated<Json>;
  houseId: string | null;
  id: Generated<string>;
  inventory: Generated<Json>;
  level: Generated<number>;
  multiverseAccess: Timestamp | null;
  name: string;
  onboardingStep: Generated<string>;
  passwordHash: string | null;
  pendingItems: Generated<Json>;
  teacherId: string;
  turma: string;
  tutorialDone: Generated<boolean>;
  username: string;
  xp: Generated<number>;
}

export interface TeacherMessages {
  body: string;
  id: Generated<string>;
  missionId: string | null;
  readAt: Timestamp | null;
  repliedAt: Timestamp | null;
  replierName: string | null;
  reply: string | null;
  sentAt: Generated<Timestamp>;
  studentId: string;
  teacherId: string;
  topic: string;
}

export interface Teachers {
  createdAt: Generated<Timestamp>;
  email: string;
  id: Generated<string>;
  isAdmin: Generated<boolean>;
  name: string;
  passwordHash: string;
  tutorialDone: Generated<boolean>;
}

export interface Trades {
  createdAt: Generated<Timestamp>;
  fromId: string;
  id: Generated<string>;
  offered: Json;
  requested: Json;
  requestedIds: Json;
  toId: string;
}

export interface DB {
  chatMessages: ChatMessages;
  eventRuns: EventRuns;
  friendships: Friendships;
  messages: Messages;
  missions: Missions;
  offers: Offers;
  sessions: Sessions;
  shopItems: ShopItems;
  students: Students;
  teacherMessages: TeacherMessages;
  teachers: Teachers;
  trades: Trades;
}
