/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Sessions {
  createdAt: Generated<Timestamp>;
  expiresAt: Timestamp;
  id: Generated<string>;
  studentId: string | null;
  teacherId: string | null;
  tokenHash: string;
}

export interface Students {
  avatar: Generated<Json>;
  bonusSlots: Generated<number>;
  coins: Generated<number>;
  createdAt: Generated<Timestamp>;
  email: string;
  houseId: string | null;
  id: Generated<string>;
  level: Generated<number>;
  multiverseAccess: Timestamp | null;
  name: string;
  onboardingStep: Generated<string>;
  passwordHash: string | null;
  teacherId: string;
  turma: string;
  tutorialDone: Generated<boolean>;
  username: string;
  xp: Generated<number>;
}

export interface Teachers {
  createdAt: Generated<Timestamp>;
  email: string;
  id: Generated<string>;
  isAdmin: Generated<boolean>;
  name: string;
  passwordHash: string;
  tutorialDone: Generated<boolean>;
}

export interface DB {
  sessions: Sessions;
  students: Students;
  teachers: Teachers;
}
