import { MissionContent } from "../../../src/engine/missions";

// Quinta leva de missões de quiz para as turmas de programação de 12 anos:
// Pacote Office, Cultura Geek, Cultura Geek parte 2, Hardware parte 2,
// Roblox Studio parte 2 e Informática parte 2. 10 perguntas cada, todas
// comentadas, sem repetir as das levas anteriores. Importar com:
//   npm run missions:import -- <e-mail do professor> scripts/missions/programacao-12-anos-parte-5.ts
const missions: MissionContent[] = [
    {
        title: "Pacote Office",
        icon: "📎",
        difficulty: "iniciante",
        minLevel: 1,
        description: "Word, Excel, PowerPoint e Outlook: os programas da Microsoft para textos, planilhas, apresentações e e-mails",
        rewardXp: 150,
        rewardCoins: 60,
        rewardItem: {
            name: "Clipe Ajudante",
            icon: "📎",
            description: "Um clipe que adorava aparecer para oferecer ajuda nos documentos. Usar transforma a ajuda em XP.",
            rarity: "comum",
            value: 15,
            xp: 40,
        },
        kind: "quiz",
        questions: [
            {
                id: "q1",
                prompt: "Qual programa do Pacote Office é feito para escrever textos, como trabalhos da escola e cartas?",
                options: [
                    { id: "a", text: "Excel" },
                    { id: "b", text: "Word" },
                    { id: "c", text: "PowerPoint" },
                    { id: "d", text: "Outlook" },
                ],
                correctOptionId: "b",
                explanation: "O Microsoft Word é o editor de textos do Office. Nele você formata títulos, insere imagens, tabelas e numera páginas. Existem alternativas gratuitas, como o Google Docs e o LibreOffice Writer.",
            },
            {
                id: "q2",
                prompt: "Qual programa do Office trabalha com planilhas, tabelas e cálculos?",
                options: [
                    { id: "a", text: "Excel" },
                    { id: "b", text: "Word" },
                    { id: "c", text: "Paint" },
                    { id: "d", text: "PowerPoint" },
                ],
                correctOptionId: "a",
                explanation: "O Excel organiza dados em linhas e colunas e faz cálculos automaticamente. Dá para controlar gastos, montar o placar de um campeonato e criar gráficos com poucos cliques.",
            },
            {
                id: "q3",
                prompt: "Qual programa você usa para criar uma apresentação de slides para mostrar à turma?",
                options: [
                    { id: "a", text: "Word" },
                    { id: "b", text: "Excel" },
                    { id: "c", text: "PowerPoint" },
                    { id: "d", text: "Outlook" },
                ],
                correctOptionId: "c",
                explanation: "O PowerPoint cria apresentações com slides, que podem ter textos, imagens, vídeos e animações. Dica: use pouco texto em cada slide e fale o resto. Slides lotados de texto cansam quem está assistindo.",
            },
            {
                id: "q4",
                prompt: "No Word em português, qual botão deixa o texto selecionado em negrito?",
                options: [
                    { id: "a", text: "O botão I" },
                    { id: "b", text: "O botão S" },
                    { id: "c", text: "O botão A" },
                    { id: "d", text: "O botão N" },
                ],
                correctOptionId: "d",
                explanation: "Na guia Página Inicial do Word em português, o N é de Negrito, o I é de Itálico e o S é de Sublinhado. Na versão em inglês, os botões são B (bold), I (italic) e U (underline).",
            },
            {
                id: "q5",
                prompt: "No Excel, o que significa a célula B3?",
                options: [
                    { id: "a", text: "A célula da coluna B com a linha 3" },
                    { id: "b", text: "A terceira planilha do arquivo" },
                    { id: "c", text: "Um botão de negrito" },
                    { id: "d", text: "O valor B vezes 3" },
                ],
                correctOptionId: "a",
                explanation: "As colunas do Excel são letras (A, B, C...) e as linhas são números (1, 2, 3...). Cada célula é o encontro de uma coluna com uma linha, e o nome dela é o endereço: B3, A1, D10.",
            },
            {
                id: "q6",
                prompt: "No Excel, com que sinal toda fórmula deve começar?",
                options: [
                    { id: "a", text: "#" },
                    { id: "b", text: "=" },
                    { id: "c", text: "@" },
                    { id: "d", text: "$" },
                ],
                correctOptionId: "b",
                explanation: "Toda fórmula começa com =. Sem ele, o Excel entende que você digitou só um texto. Por exemplo, =10+5 mostra 15, mas 10+5 sem o = aparece escrito do jeito que você digitou.",
            },
            {
                id: "q7",
                prompt: "A1 vale 5, A2 vale 7 e A3 vale 8. Qual é o resultado de =SOMA(A1:A3)?",
                options: [
                    { id: "a", text: "13" },
                    { id: "b", text: "3" },
                    { id: "c", text: "20" },
                    { id: "d", text: "578" },
                ],
                correctOptionId: "c",
                explanation: "O SOMA soma todas as células do intervalo, e A1:A3 quer dizer \"de A1 até A3\": 5 + 7 + 8 = 20. Para a média, use =MÉDIA(A1:A3). Se um valor mudar, o resultado se atualiza sozinho!",
            },
            {
                id: "q8",
                prompt: "Pela extensão, qual destes arquivos é uma apresentação do PowerPoint?",
                options: [
                    { id: "a", text: "trabalho.docx" },
                    { id: "b", text: "notas.xlsx" },
                    { id: "c", text: "foto.png" },
                    { id: "d", text: "feira-de-ciencias.pptx" },
                ],
                correctOptionId: "d",
                explanation: "No Office, .docx é do Word, .xlsx é do Excel e .pptx é do PowerPoint. O \"x\" no final indica o formato moderno, usado desde 2007. Saber a extensão ajuda a saber qual programa abre o arquivo.",
            },
            {
                id: "q9",
                prompt: "No PowerPoint, qual é a diferença entre transição e animação?",
                options: [
                    { id: "a", text: "Não há diferença" },
                    { id: "b", text: "A transição é o efeito na troca de um slide para outro; a animação é o efeito em um elemento dentro do slide" },
                    { id: "c", text: "A animação muda a cor do slide" },
                    { id: "d", text: "A transição só funciona no Word" },
                ],
                correctOptionId: "b",
                explanation: "Transições acontecem entre slides, como o slide novo entrar deslizando. Animações fazem um título, imagem ou texto aparecer, se mover ou sumir dentro do slide. Usar poucos efeitos deixa a apresentação mais profissional.",
            },
            {
                id: "q10",
                prompt: "Qual programa do Office é usado para enviar e receber e-mails e organizar a agenda?",
                options: [
                    { id: "a", text: "Outlook" },
                    { id: "b", text: "Excel" },
                    { id: "c", text: "Word" },
                    { id: "d", text: "PowerPoint" },
                ],
                correctOptionId: "a",
                explanation: "O Outlook junta e-mail, calendário e contatos. Também fazem parte do pacote programas como o OneNote (anotações) e o Teams (reuniões e conversas), muito usados em escolas e empresas.",
            },
        ],
    },
    {
        title: "Cultura Geek",
        icon: "🎮",
        difficulty: "iniciante",
        minLevel: 1,
        description: "Filmes, séries e games que marcaram gerações: Minecraft, Mario, Pokémon, Star Wars, Harry Potter e mais",
        rewardXp: 150,
        rewardCoins: 60,
        rewardItem: {
            name: "Controle Retrô",
            icon: "🎮",
            description: "Um controle de videogame dos anos 80, com só dois botões. Usar transforma cada partida em XP.",
            rarity: "comum",
            value: 15,
            xp: 40,
        },
        kind: "quiz",
        questions: [
            {
                id: "q1",
                prompt: "No Minecraft, qual é o nome da criatura verde que se aproxima em silêncio e explode?",
                options: [
                    { id: "a", text: "Zumbi" },
                    { id: "b", text: "Enderman" },
                    { id: "c", text: "Creeper" },
                    { id: "d", text: "Esqueleto" },
                ],
                correctOptionId: "c",
                explanation: "O Creeper é um dos símbolos do Minecraft. Ele chega sem fazer barulho, solta um chiado e explode. O jogo foi criado pelo sueco Markus Persson, o \"Notch\", e desenvolvido pela Mojang.",
            },
            {
                id: "q2",
                prompt: "Qual é a profissão do Mario, o personagem mais famoso da Nintendo?",
                options: [
                    { id: "a", text: "Encanador" },
                    { id: "b", text: "Cozinheiro" },
                    { id: "c", text: "Bombeiro" },
                    { id: "d", text: "Astronauta" },
                ],
                correctOptionId: "a",
                explanation: "O Mario é um encanador, assim como o irmão Luigi. Por isso ele vive entrando em canos nos jogos! Ele foi criado por Shigeru Miyamoto, um dos game designers mais importantes da história.",
            },
            {
                id: "q3",
                prompt: "De qual tipo é o Pikachu, o Pokémon mais famoso?",
                options: [
                    { id: "a", text: "Fogo" },
                    { id: "b", text: "Elétrico" },
                    { id: "c", text: "Água" },
                    { id: "d", text: "Planta" },
                ],
                correctOptionId: "b",
                explanation: "O Pikachu é do tipo Elétrico e solta choques pelas bochechas vermelhas. Na franquia Pokémon, cada tipo é forte contra alguns e fraco contra outros: Elétrico é forte contra Água, por exemplo.",
            },
            {
                id: "q4",
                prompt: "Em Star Wars, qual é a arma típica dos cavaleiros Jedi?",
                options: [
                    { id: "a", text: "Arco e flecha" },
                    { id: "b", text: "Martelo" },
                    { id: "c", text: "Varinha mágica" },
                    { id: "d", text: "Sabre de luz" },
                ],
                correctOptionId: "d",
                explanation: "O sabre de luz é a arma dos Jedi (e também dos Sith, os vilões). Star Wars começou em 1977, criado por George Lucas, e a frase \"Que a Força esteja com você\" ficou famosa no mundo todo.",
            },
            {
                id: "q5",
                prompt: "Como se chama a escola de magia onde Harry Potter estuda?",
                options: [
                    { id: "a", text: "Hogwarts" },
                    { id: "b", text: "Xavier" },
                    { id: "c", text: "Nárnia" },
                    { id: "d", text: "Acampamento Meio-Sangue" },
                ],
                correctOptionId: "a",
                explanation: "Harry Potter estuda em Hogwarts, onde os alunos são divididos em quatro casas: Grifinória, Sonserina, Corvinal e Lufa-Lufa. Parece um pouco com as casas da CodeGuilds, não é?",
            },
            {
                id: "q6",
                prompt: "Qual é o nome verdadeiro do Homem-Aranha?",
                options: [
                    { id: "a", text: "Tony Stark" },
                    { id: "b", text: "Bruce Wayne" },
                    { id: "c", text: "Peter Parker" },
                    { id: "d", text: "Clark Kent" },
                ],
                correctOptionId: "c",
                explanation: "O Homem-Aranha é Peter Parker, um jovem que ganhou poderes ao ser picado por uma aranha. A frase mais famosa dele é \"com grandes poderes vêm grandes responsabilidades\". Tony Stark é o Homem de Ferro, Bruce Wayne é o Batman e Clark Kent é o Superman.",
            },
            {
                id: "q7",
                prompt: "Toy Story (1995), da Pixar, entrou para a história do cinema por quê?",
                options: [
                    { id: "a", text: "Foi o primeiro filme colorido" },
                    { id: "b", text: "Foi o primeiro longa-metragem feito totalmente com animação por computador" },
                    { id: "c", text: "Foi o primeiro filme com som" },
                    { id: "d", text: "Foi o primeiro filme em 3D" },
                ],
                correctOptionId: "b",
                explanation: "Toy Story foi o primeiro longa-metragem todo animado por computador. Por trás de cada cena há muita matemática e programação: os animadores da Pixar usam programas para criar luz, movimento e texturas.",
            },
            {
                id: "q8",
                prompt: "Na série de jogos The Legend of Zelda, qual é o nome do herói de roupa verde que o jogador controla?",
                options: [
                    { id: "a", text: "Zelda" },
                    { id: "b", text: "Ganon" },
                    { id: "c", text: "Mario" },
                    { id: "d", text: "Link" },
                ],
                correctOptionId: "d",
                explanation: "O herói é o Link! Muita gente confunde, mas Zelda é a princesa que dá nome à série. Ganon é o grande vilão. O primeiro jogo saiu em 1986, também criado por Shigeru Miyamoto.",
            },
            {
                id: "q9",
                prompt: "O Sonic, o ouriço azul supersônico, é o mascote de qual empresa de games?",
                options: [
                    { id: "a", text: "Sega" },
                    { id: "b", text: "Nintendo" },
                    { id: "c", text: "Sony" },
                    { id: "d", text: "Microsoft" },
                ],
                correctOptionId: "a",
                explanation: "O Sonic é o mascote da Sega e estreou em 1991. Na época, Sega e Nintendo disputavam os fãs: de um lado o Sonic veloz, do outro o Mario. Hoje o Sonic aparece até em consoles da Nintendo!",
            },
            {
                id: "q10",
                prompt: "No clássico Pac-Man (1980), o que o personagem faz pelo labirinto?",
                options: [
                    { id: "a", text: "Constrói casas" },
                    { id: "b", text: "Come pastilhas, fugindo de quatro fantasmas" },
                    { id: "c", text: "Dirige um carro de corrida" },
                    { id: "d", text: "Captura monstrinhos" },
                ],
                correctOptionId: "b",
                explanation: "O Pac-Man come as pastilhas do labirinto enquanto foge dos fantasmas Blinky, Pinky, Inky e Clyde. Ao comer uma pastilha grande, é a vez dele perseguir os fantasmas. Cada fantasma tem um jeito diferente de perseguir: é programação de comportamento!",
            },
        ],
    },
    {
        title: "Cultura Geek parte 2",
        icon: "🍿",
        difficulty: "iniciante",
        minLevel: 1,
        description: "Mais filmes, séries, quadrinhos e games: Tetris, Among Us, heróis, Jurassic Park e a Turma da Mônica",
        rewardXp: 150,
        rewardCoins: 60,
        rewardItem: {
            name: "Balde de Pipoca Lendário",
            icon: "🍿",
            description: "Um balde de pipoca que nunca esvazia durante uma maratona de filmes. Usar transforma a maratona em XP.",
            rarity: "raro",
            value: 30,
            xp: 60,
        },
        kind: "quiz",
        questions: [
            {
                id: "q1",
                prompt: "Em qual país foi criado o Tetris, o jogo das peças que caem?",
                options: [
                    { id: "a", text: "Japão" },
                    { id: "b", text: "Estados Unidos" },
                    { id: "c", text: "Na antiga União Soviética (atual Rússia)" },
                    { id: "d", text: "Brasil" },
                ],
                correctOptionId: "c",
                explanation: "O Tetris foi criado em 1984 por Alexey Pajitnov, um programador de Moscou, na antiga União Soviética. As peças de 4 quadradinhos se chamam tetraminós, daí o nome. É um dos jogos mais vendidos de todos os tempos.",
            },
            {
                id: "q2",
                prompt: "No jogo Among Us, qual é o objetivo de quem é o impostor?",
                options: [
                    { id: "a", text: "Completar todas as tarefas da nave" },
                    { id: "b", text: "Atrapalhar a tripulação sem ser descoberto" },
                    { id: "c", text: "Construir uma nave nova" },
                    { id: "d", text: "Coletar o maior número de moedas" },
                ],
                correctOptionId: "b",
                explanation: "Os tripulantes tentam completar as tarefas e descobrir quem é o impostor nas reuniões. O impostor finge ser tripulante e sabota a nave. O jogo, lançado em 2018, ficou famoso no mundo todo em 2020.",
            },
            {
                id: "q3",
                prompt: "Qual é o nome do martelo do Thor, o herói da Marvel?",
                options: [
                    { id: "a", text: "Excalibur" },
                    { id: "b", text: "Mjolnir" },
                    { id: "c", text: "Vibranium" },
                    { id: "d", text: "Tesseract" },
                ],
                correctOptionId: "b",
                explanation: "O martelo do Thor se chama Mjolnir e, segundo a história, só quem é digno consegue levantá-lo. O personagem foi inspirado no deus do trovão da mitologia nórdica.",
            },
            {
                id: "q4",
                prompt: "Em qual cidade o Batman protege as pessoas?",
                options: [
                    { id: "a", text: "Metrópolis" },
                    { id: "b", text: "Nova York" },
                    { id: "c", text: "Gotham" },
                    { id: "d", text: "Springfield" },
                ],
                correctOptionId: "c",
                explanation: "O Batman protege Gotham City. Por trás da máscara está o bilionário Bruce Wayne, que não tem superpoderes: usa inteligência, treino e tecnologia. Metrópolis é a cidade do Superman.",
            },
            {
                id: "q5",
                prompt: "De qual planeta veio o Superman?",
                options: [
                    { id: "a", text: "Krypton" },
                    { id: "b", text: "Marte" },
                    { id: "c", text: "Tatooine" },
                    { id: "d", text: "Asgard" },
                ],
                correctOptionId: "a",
                explanation: "O Superman nasceu em Krypton e foi enviado bebê para a Terra antes de o planeta ser destruído. A kryptonita, uma pedra do planeta natal dele, é a sua grande fraqueza.",
            },
            {
                id: "q6",
                prompt: "No filme Pantera Negra, como se chama o país africano escondido e cheio de tecnologia?",
                options: [
                    { id: "a", text: "Asgard" },
                    { id: "b", text: "Gotham" },
                    { id: "c", text: "Atlântida" },
                    { id: "d", text: "Wakanda" },
                ],
                correctOptionId: "d",
                explanation: "Wakanda é o país fictício do Pantera Negra. Ele é super avançado graças ao vibranium, um metal raríssimo. A irmã do herói, Shuri, é uma gênia da ciência e da tecnologia.",
            },
            {
                id: "q7",
                prompt: "Qual personagem de Star Wars é um mestre Jedi pequeno, verde e que fala com as palavras fora da ordem comum?",
                options: [
                    { id: "a", text: "Chewbacca" },
                    { id: "b", text: "Yoda" },
                    { id: "c", text: "R2-D2" },
                    { id: "d", text: "Darth Vader" },
                ],
                correctOptionId: "b",
                explanation: "O mestre Yoda treinou Jedis por séculos e fala de um jeito único, como \"Faça ou não faça. Tentativa não há.\" Chewbacca é o wookiee peludo e R2-D2 é o pequeno robô que se comunica com bipes.",
            },
            {
                id: "q8",
                prompt: "Em qual jogo o Mario apareceu pela primeira vez, em 1981, ainda com o nome de Jumpman?",
                options: [
                    { id: "a", text: "Super Mario Bros." },
                    { id: "b", text: "Mario Kart" },
                    { id: "c", text: "Pac-Man" },
                    { id: "d", text: "Donkey Kong" },
                ],
                correctOptionId: "d",
                explanation: "Antes de ter o próprio jogo, o Mario estreou em Donkey Kong (1981), pulando barris para salvar uma moça de um gorila. Na época ele se chamava Jumpman (\"homem que pula\"). Super Mario Bros. só veio em 1985.",
            },
            {
                id: "q9",
                prompt: "No filme Jurassic Park (1993), como os cientistas trazem os dinossauros de volta?",
                options: [
                    { id: "a", text: "Com uma máquina do tempo" },
                    { id: "b", text: "Com magia" },
                    { id: "c", text: "Com DNA de dinossauro encontrado em mosquitos presos no âmbar" },
                    { id: "d", text: "Encontrando ovos congelados no gelo" },
                ],
                correctOptionId: "c",
                explanation: "No filme, mosquitos que picaram dinossauros ficaram presos em âmbar (resina de árvore fossilizada), guardando o sangue com DNA. Na vida real isso não funcionaria, porque o DNA se desfaz com o tempo, mas foi uma ideia genial para a história, dirigida por Steven Spielberg.",
            },
            {
                id: "q10",
                prompt: "Na Turma da Mônica, criada pelo brasileiro Mauricio de Sousa, qual personagem morre de medo de água e não gosta de tomar banho?",
                options: [
                    { id: "a", text: "Cebolinha" },
                    { id: "b", text: "Magali" },
                    { id: "c", text: "Cascão" },
                    { id: "d", text: "Chico Bento" },
                ],
                correctOptionId: "c",
                explanation: "O Cascão tem pavor de água! O Cebolinha troca o R pelo L e vive criando \"planos infalíveis\", e a Magali adora comer, principalmente melancia. A Turma da Mônica é um orgulho dos quadrinhos brasileiros, com histórias desde a década de 1960.",
            },
        ],
    },
    {
        title: "Hardware parte 2",
        icon: "🔌",
        difficulty: "iniciante",
        minLevel: 1,
        description: "Mais hardware: portas e cabos, gigahertz, núcleos, BIOS, pendrive, rede e o Raspberry Pi",
        rewardXp: 150,
        rewardCoins: 60,
        rewardItem: {
            name: "Pendrive Perdido",
            icon: "💾",
            description: "Um pendrive encontrado no fundo da mochila, cheio de projetos esquecidos. Usar recupera tudo em forma de XP.",
            rarity: "comum",
            value: 15,
            xp: 40,
        },
        kind: "quiz",
        questions: [
            {
                id: "q1",
                prompt: "Como se chama a \"caixa\" que protege e guarda as peças de um computador de mesa?",
                options: [
                    { id: "a", text: "Monitor" },
                    { id: "b", text: "Gabinete" },
                    { id: "c", text: "Teclado" },
                    { id: "d", text: "Estabilizador" },
                ],
                correctOptionId: "b",
                explanation: "O gabinete guarda a placa-mãe, o processador, a memória, a fonte e o armazenamento. Muita gente chama o gabinete de \"CPU\", mas a CPU é só o processador, que fica lá dentro.",
            },
            {
                id: "q2",
                prompt: "Para que servem as portas USB do computador?",
                options: [
                    { id: "a", text: "Só para carregar o celular" },
                    { id: "b", text: "Para conectar a internet sem fio" },
                    { id: "c", text: "Para conectar aparelhos como mouse, teclado, pendrive, impressora e controle" },
                    { id: "d", text: "Para resfriar o processador" },
                ],
                correctOptionId: "c",
                explanation: "USB quer dizer \"Barramento Serial Universal\": é uma porta padrão que conecta muitos tipos de aparelhos, transferindo dados e energia. O tipo USB-C, que encaixa dos dois lados, está cada vez mais comum.",
            },
            {
                id: "q3",
                prompt: "Qual cabo leva imagem e som do computador ou do videogame para uma TV ou monitor?",
                options: [
                    { id: "a", text: "HDMI" },
                    { id: "b", text: "Cabo de força" },
                    { id: "c", text: "Cabo de rede" },
                    { id: "d", text: "Cabo do mouse" },
                ],
                correctOptionId: "a",
                explanation: "O HDMI transmite vídeo e áudio em alta qualidade por um único cabo. Por isso é o cabo usado para ligar videogames, notebooks e TV boxes na televisão.",
            },
            {
                id: "q4",
                prompt: "Um processador de 3 GHz (gigahertz). O que esse número indica?",
                options: [
                    { id: "a", text: "Quanto espaço ele tem para guardar arquivos" },
                    { id: "b", text: "A velocidade da internet" },
                    { id: "c", text: "O tamanho da tela" },
                    { id: "d", text: "A frequência: ele trabalha em cerca de 3 bilhões de ciclos por segundo" },
                ],
                correctOptionId: "d",
                explanation: "O GHz mede a frequência (o \"clock\") do processador: 3 GHz são 3 bilhões de ciclos por segundo. Mas não é o único fator de velocidade: a quantidade de núcleos e a geração do processador também contam muito.",
            },
            {
                id: "q5",
                prompt: "Um processador \"de 8 núcleos\" tem qual vantagem?",
                options: [
                    { id: "a", text: "Consegue trabalhar em várias tarefas ao mesmo tempo, como se fossem vários processadores juntos" },
                    { id: "b", text: "Tem 8 vezes mais memória RAM" },
                    { id: "c", text: "Gasta 8 vezes menos energia" },
                    { id: "d", text: "Funciona sem placa-mãe" },
                ],
                correctOptionId: "a",
                explanation: "Cada núcleo (core) consegue executar tarefas por conta própria. Com vários núcleos, o computador roda um jogo, a música e o navegador ao mesmo tempo com mais facilidade. Programas preparados para isso ficam muito mais rápidos.",
            },
            {
                id: "q6",
                prompt: "Qual é o primeiro programa que roda quando você liga o computador, antes mesmo do Windows, e confere se as peças estão funcionando?",
                options: [
                    { id: "a", text: "O navegador" },
                    { id: "b", text: "A BIOS (ou UEFI), gravada num chip da placa-mãe" },
                    { id: "c", text: "O Excel" },
                    { id: "d", text: "O antivírus" },
                ],
                correctOptionId: "b",
                explanation: "A BIOS, ou a versão mais moderna, UEFI, fica gravada num chip da placa-mãe. Ela testa as peças, encontra o armazenamento e dá a partida no sistema operacional. Por isso aparece um logotipo antes do Windows carregar.",
            },
            {
                id: "q7",
                prompt: "Que tipo de memória o pendrive usa para guardar os arquivos mesmo desconectado?",
                options: [
                    { id: "a", text: "Memória RAM, que apaga quando desliga" },
                    { id: "b", text: "Um disco que gira, como um HD" },
                    { id: "c", text: "Memória flash, a mesma tecnologia dos SSDs e dos cartões de memória" },
                    { id: "d", text: "Fita cassete" },
                ],
                correctOptionId: "c",
                explanation: "O pendrive usa memória flash, que guarda os dados sem precisar de energia e não tem partes móveis. Os SSDs e os cartões de memória de celulares e câmeras usam a mesma tecnologia.",
            },
            {
                id: "q8",
                prompt: "Para que serve a pasta térmica colocada entre o processador e o cooler?",
                options: [
                    { id: "a", text: "Para colar o processador na placa-mãe" },
                    { id: "b", text: "Para ajudar a passar o calor do processador para o cooler" },
                    { id: "c", text: "Para limpar o processador" },
                    { id: "d", text: "Para deixar a internet mais rápida" },
                ],
                correctOptionId: "b",
                explanation: "As superfícies do processador e do cooler parecem lisas, mas têm micro-buraquinhos com ar, que atrapalha a passagem do calor. A pasta térmica preenche esses espaços e ajuda a resfriar o processador.",
            },
            {
                id: "q9",
                prompt: "Qual peça permite que o computador se conecte à internet, por cabo ou por Wi-Fi?",
                options: [
                    { id: "a", text: "A placa de rede" },
                    { id: "b", text: "A placa de vídeo" },
                    { id: "c", text: "A fonte de alimentação" },
                    { id: "d", text: "O cooler" },
                ],
                correctOptionId: "a",
                explanation: "A placa de rede conecta o computador a uma rede, como a do roteador da sua casa, por cabo ou por Wi-Fi. Hoje ela costuma vir embutida na placa-mãe, e os notebooks já têm Wi-Fi.",
            },
            {
                id: "q10",
                prompt: "O que é o Raspberry Pi?",
                options: [
                    { id: "a", text: "Uma sobremesa de framboesa" },
                    { id: "b", text: "Um jogo de celular" },
                    { id: "c", text: "Um computador completo do tamanho de um cartão de crédito, criado para ensinar programação" },
                    { id: "d", text: "Uma marca de mouse" },
                ],
                correctOptionId: "c",
                explanation: "O Raspberry Pi é um computador pequeno e barato, criado no Reino Unido para ajudar estudantes a aprender programação e eletrônica. Com ele dá para montar robôs, estações meteorológicas e até videogames retrô. (E sim, raspberry é framboesa em inglês!)",
            },
        ],
    },
    {
        title: "Roblox Studio parte 2",
        icon: "🔥",
        difficulty: "medio",
        minLevel: 1,
        description: "Mais Roblox Studio: Workspace, Script e LocalScript, eventos de toque, propriedades, ferramentas e publicação",
        rewardXp: 180,
        rewardCoins: 80,
        rewardItem: {
            name: "Peça Mortal",
            icon: "🔥",
            description: "A famosa peça de lava dos jogos de obstáculos. Usar (com cuidado!) transforma o calor em XP.",
            rarity: "raro",
            value: 30,
            xp: 60,
        },
        kind: "quiz",
        questions: [
            {
                id: "q1",
                prompt: "No Explorer, dentro de qual serviço ficam as peças e os modelos que aparecem no mundo 3D do jogo?",
                options: [
                    { id: "a", text: "Workspace" },
                    { id: "b", text: "Lighting" },
                    { id: "c", text: "SoundService" },
                    { id: "d", text: "Players" },
                ],
                correctOptionId: "a",
                explanation: "O Workspace guarda tudo que existe no mundo 3D: peças, modelos, o terreno e os personagens durante o jogo. Se uma peça não está no Workspace, ela não aparece no mapa.",
            },
            {
                id: "q2",
                prompt: "Qual é a diferença entre um Script e um LocalScript no Roblox?",
                options: [
                    { id: "a", text: "Não há diferença" },
                    { id: "b", text: "O Script roda no servidor e vale para todos os jogadores; o LocalScript roda no aparelho de cada jogador" },
                    { id: "c", text: "O LocalScript só funciona no Studio" },
                    { id: "d", text: "O Script é escrito em Python" },
                ],
                correctOptionId: "b",
                explanation: "O Script roda no servidor, então o que ele faz (como abrir uma porta) acontece para todos. O LocalScript roda no computador ou celular de cada jogador e cuida de coisas pessoais, como a interface e os controles.",
            },
            {
                id: "q3",
                prompt: "Num Script colocado dentro de uma peça, o que é script.Parent?",
                options: [
                    { id: "a", text: "O jogador" },
                    { id: "b", text: "O próprio script" },
                    { id: "c", text: "A peça onde o script está" },
                    { id: "d", text: "O Workspace inteiro" },
                ],
                correctOptionId: "c",
                explanation: "No Explorer, os objetos ficam uns dentro dos outros. O Parent (\"pai\") é o objeto que contém outro. Se o script está dentro de uma peça, script.Parent é essa peça, e é assim que o script sabe com o que vai trabalhar.",
            },
            {
                id: "q4",
                prompt: "O que este script faz com o jogador que encostar na peça?",
                code: "local peca = script.Parent\n\npeca.Touched:Connect(function(outra)\n  local humanoid = outra.Parent:FindFirstChild(\"Humanoid\")\n  if humanoid then\n    humanoid.Health = 0\n  end\nend)",
                options: [
                    { id: "a", text: "Dá vida extra" },
                    { id: "b", text: "Faz o jogador pular mais alto" },
                    { id: "c", text: "Leva o jogador para o início" },
                    { id: "d", text: "Zera a vida do personagem, como uma peça de lava" },
                ],
                correctOptionId: "d",
                explanation: "O evento Touched dispara quando algo encosta na peça. O script procura o Humanoid (que controla a vida do personagem) e coloca Health = 0. É a famosa \"kill brick\", a peça de lava dos jogos de obstáculos!",
            },
            {
                id: "q5",
                prompt: "Qual propriedade deixa os jogadores atravessarem uma peça, como uma parede falsa?",
                options: [
                    { id: "a", text: "Anchored desligado" },
                    { id: "b", text: "CanCollide desligado" },
                    { id: "c", text: "Color preto" },
                    { id: "d", text: "Material Glass" },
                ],
                correctOptionId: "b",
                explanation: "Com CanCollide ligado, a peça é sólida. Desligado, tudo passa por ela. Junto com o Anchored ligado, para não cair, dá para criar passagens secretas nos mapas.",
            },
            {
                id: "q6",
                prompt: "Qual valor de Transparency deixa uma peça totalmente invisível?",
                options: [
                    { id: "a", text: "0" },
                    { id: "b", text: "0.5" },
                    { id: "c", text: "1" },
                    { id: "d", text: "100" },
                ],
                correctOptionId: "c",
                explanation: "A Transparency vai de 0 (totalmente visível) a 1 (invisível), e 0.5 deixa meio transparente. Uma peça invisível continua sólida se o CanCollide estiver ligado: é assim que se criam paredes invisíveis.",
            },
            {
                id: "q7",
                prompt: "Quais ferramentas do Studio servem para mover, mudar o tamanho e girar as peças?",
                options: [
                    { id: "a", text: "Move, Scale e Rotate" },
                    { id: "b", text: "Play, Stop e Pause" },
                    { id: "c", text: "Copy, Paste e Delete" },
                    { id: "d", text: "Explorer, Output e Toolbox" },
                ],
                correctOptionId: "a",
                explanation: "Na aba Home (ou Model), o Move mostra setas para arrastar, o Scale mostra bolinhas para esticar e o Rotate mostra anéis para girar. São as ferramentas mais usadas na construção.",
            },
            {
                id: "q8",
                prompt: "Qual ferramenta cria montanhas, lagos, grama e cavernas no mapa?",
                options: [
                    { id: "a", text: "Output" },
                    { id: "b", text: "Terrain Editor (Editor de Terreno)" },
                    { id: "c", text: "Properties" },
                    { id: "d", text: "SpawnLocation" },
                ],
                correctOptionId: "b",
                explanation: "O Terrain Editor \"pinta\" o terreno com materiais como grama, areia, rocha e água, além de criar morros e vales. Ele pode até gerar um mapa inteiro automaticamente para você começar.",
            },
            {
                id: "q9",
                prompt: "O que faz o task.wait() neste script do Roblox?",
                code: "print(\"3...\")\ntask.wait(1)\nprint(\"2...\")\ntask.wait(1)\nprint(\"1... Já!\")",
                options: [
                    { id: "a", text: "Para o jogo de vez" },
                    { id: "b", text: "Repete o script 2 vezes" },
                    { id: "c", text: "Faz o script esperar alguns segundos antes de continuar" },
                    { id: "d", text: "Apaga o script" },
                ],
                correctOptionId: "c",
                explanation: "O task.wait() pausa o script pelo tempo indicado, em segundos. No exemplo, cada número aparece com 1 segundo de intervalo, como uma contagem regressiva. É parecido com o bloco \"espere 1 seg\" do Scratch.",
            },
            {
                id: "q10",
                prompt: "Seu jogo está pronto. Como você o coloca no Roblox para outras pessoas jogarem?",
                options: [
                    { id: "a", text: "Mandando o arquivo por e-mail para cada jogador" },
                    { id: "b", text: "Clicando em Play" },
                    { id: "c", text: "Tirando um print da tela" },
                    { id: "d", text: "Pelo menu File → Publish to Roblox, e depois deixando o jogo público" },
                ],
                correctOptionId: "d",
                explanation: "O Publish to Roblox envia o jogo para os servidores da Roblox. Depois, nas configurações, você define se ele é público ou privado, coloca nome, descrição e imagem. Antes de publicar, teste bastante com o Play!",
            },
        ],
    },
    {
        title: "Informática parte 2",
        icon: "☁️",
        difficulty: "iniciante",
        minLevel: 1,
        description: "Mais informática: download e upload, nuvem, atalhos, backup, antivírus, sites seguros e boas pesquisas",
        rewardXp: 150,
        rewardCoins: 60,
        rewardItem: {
            name: "Nuvem de Backup",
            icon: "☁️",
            description: "Uma nuvem que guarda uma cópia de tudo que importa. Usar transforma a segurança em XP.",
            rarity: "comum",
            value: 15,
            xp: 40,
        },
        kind: "quiz",
        questions: [
            {
                id: "q1",
                prompt: "Qual é a diferença entre download e upload?",
                options: [
                    { id: "a", text: "Download é trazer um arquivo da internet para o seu aparelho; upload é enviar um arquivo do seu aparelho para a internet" },
                    { id: "b", text: "Não há diferença" },
                    { id: "c", text: "Download é apagar um arquivo" },
                    { id: "d", text: "Upload é imprimir um arquivo" },
                ],
                correctOptionId: "a",
                explanation: "Baixar um jogo é download. Enviar seu projeto .sb3 numa missão de entrega da CodeGuilds é upload! As conexões de internet costumam ter velocidade de download maior que a de upload.",
            },
            {
                id: "q2",
                prompt: "O que quer dizer guardar arquivos \"na nuvem\"?",
                options: [
                    { id: "a", text: "Guardar no céu, de verdade" },
                    { id: "b", text: "Guardar num pendrive" },
                    { id: "c", text: "Guardar em servidores na internet, para acessar de qualquer aparelho" },
                    { id: "d", text: "Apagar os arquivos" },
                ],
                correctOptionId: "c",
                explanation: "A nuvem são computadores de empresas (servidores) que guardam seus arquivos pela internet, como o Google Drive e o OneDrive. A vantagem é acessar de qualquer lugar e não perder tudo se o computador quebrar.",
            },
            {
                id: "q3",
                prompt: "Qual atalho abre a busca de palavras numa página ou documento?",
                options: [
                    { id: "a", text: "Ctrl + P" },
                    { id: "b", text: "Ctrl + F" },
                    { id: "c", text: "Ctrl + V" },
                    { id: "d", text: "Ctrl + Z" },
                ],
                correctOptionId: "b",
                explanation: "Ctrl + F (de \"find\", encontrar) abre a caixa de busca: digite uma palavra e o programa marca onde ela aparece. Funciona no navegador, no Word e em muitos outros programas. Ajuda muito em pesquisas!",
            },
            {
                id: "q4",
                prompt: "No Windows, qual atalho troca rapidamente entre as janelas abertas?",
                options: [
                    { id: "a", text: "Alt + Tab" },
                    { id: "b", text: "Ctrl + C" },
                    { id: "c", text: "Shift + A" },
                    { id: "d", text: "Ctrl + S" },
                ],
                correctOptionId: "a",
                explanation: "Segurando o Alt e apertando o Tab, você passa de uma janela para outra. Mas atenção: o Alt + F4 fecha a janela atual, então cuidado para não confundir!",
            },
            {
                id: "q5",
                prompt: "Qual atalho do Windows abre a ferramenta para recortar e capturar uma parte da tela?",
                options: [
                    { id: "a", text: "Ctrl + Alt + Del" },
                    { id: "b", text: "Windows + D" },
                    { id: "c", text: "Windows + Shift + S" },
                    { id: "d", text: "Alt + F4" },
                ],
                correctOptionId: "c",
                explanation: "O Windows + Shift + S deixa você escolher um pedaço da tela para capturar, e a imagem vai para a área de transferência (é só colar com Ctrl + V). A tecla Print Screen captura a tela inteira.",
            },
            {
                id: "q6",
                prompt: "O que é fazer um backup?",
                options: [
                    { id: "a", text: "Apagar arquivos antigos" },
                    { id: "b", text: "Formatar o computador" },
                    { id: "c", text: "Deixar o computador mais rápido" },
                    { id: "d", text: "Fazer uma cópia de segurança dos arquivos importantes em outro lugar" },
                ],
                correctOptionId: "d",
                explanation: "Backup é uma cópia de segurança: se o computador quebrar, for roubado ou pegar vírus, os arquivos continuam salvos, num HD externo, pendrive ou na nuvem. Quem programa sabe: perder um projeto inteiro dói!",
            },
            {
                id: "q7",
                prompt: "Para que serve um antivírus?",
                options: [
                    { id: "a", text: "Para detectar e remover programas maliciosos, que podem roubar dados ou estragar o computador" },
                    { id: "b", text: "Para deixar a internet mais rápida" },
                    { id: "c", text: "Para limpar a tela" },
                    { id: "d", text: "Para criar senhas" },
                ],
                correctOptionId: "a",
                explanation: "O antivírus procura e bloqueia programas maliciosos (malware), como vírus e programas que roubam senhas. O Windows já vem com um, o Microsoft Defender. Mesmo assim, evite baixar jogos e programas de sites desconhecidos.",
            },
            {
                id: "q8",
                prompt: "Num endereço que começa com https:// e mostra um cadeado no navegador, o que isso indica?",
                options: [
                    { id: "a", text: "Que o site é do governo" },
                    { id: "b", text: "Que a conexão com o site é criptografada, protegendo os dados no caminho" },
                    { id: "c", text: "Que o site é pago" },
                    { id: "d", text: "Que o site não tem anúncios" },
                ],
                correctOptionId: "b",
                explanation: "O \"s\" do https é de seguro: os dados vão embaralhados (criptografados), e ninguém no caminho consegue ler. Mas atenção: o cadeado não garante que o site é confiável, só que a conexão é protegida. Golpistas também usam https!",
            },
            {
                id: "q9",
                prompt: "Numa pesquisa no Google, para que servem as aspas, como em \"objetivos de desenvolvimento sustentável\"?",
                options: [
                    { id: "a", text: "Para pesquisar só imagens" },
                    { id: "b", text: "Para deixar a pesquisa mais lenta" },
                    { id: "c", text: "Para buscar a frase exata, com as palavras juntas e nessa ordem" },
                    { id: "d", text: "Não servem para nada" },
                ],
                correctOptionId: "c",
                explanation: "Com aspas, o buscador procura exatamente aquela frase, o que deixa o resultado mais preciso. Outra dica: confira sempre se o site é confiável e compare as informações em mais de uma fonte.",
            },
            {
                id: "q10",
                prompt: "Por que é importante instalar as atualizações do sistema e dos programas?",
                options: [
                    { id: "a", text: "Só para mudar as cores" },
                    { id: "b", text: "Porque elas corrigem bugs e falhas de segurança que poderiam ser usadas por invasores" },
                    { id: "c", text: "Porque deixam o computador sem internet" },
                    { id: "d", text: "Não é importante" },
                ],
                correctOptionId: "b",
                explanation: "As atualizações corrigem erros e fecham brechas de segurança descobertas depois do lançamento. Um sistema desatualizado é mais fácil de invadir. Programadores fazem atualizações o tempo todo, inclusive na CodeGuilds!",
            },
        ],
    },
]

export default missions
