import { MissionContent } from "../../../src/engine/missions";

// Segunda leva de missões de quiz para as turmas de programação de 12 anos:
// ODS parte 2, Scratch parte 2, MIT App Inventor, HTML e CSS.
// 10 perguntas cada, todas comentadas, sem repetir as da primeira leva
// (programacao-12-anos.ts). Importar com:
//   npm run missions:import -- <e-mail do professor> scripts/missions/programacao-12-anos-parte-2.ts
const missions: MissionContent[] = [
    {
        title: "ODS parte 2",
        icon: "🌎",
        difficulty: "iniciante",
        minLevel: 1,
        description: "Mais Objetivos de Desenvolvimento Sustentável: pobreza, saúde, energia, cidades, florestas e muito mais",
        rewardXp: 150,
        rewardCoins: 60,
        rewardItem: {
            name: "Folha da Árvore Sustentável",
            icon: "🍃",
            description: "Uma folha de uma árvore que cresce a cada boa ação pelo planeta. Usar transforma o cuidado em XP.",
            rarity: "comum",
            value: 15,
            xp: 40,
        },
        kind: "quiz",
        questions: [
            {
                id: "q1",
                prompt: "A Agenda 2030 tem um lema que resume a ideia dos ODS. Qual é ele?",
                options: [
                    { id: "a", text: "\"Cada um por si\"" },
                    { id: "b", text: "\"Não deixar ninguém para trás\"" },
                    { id: "c", text: "\"Primeiro os países ricos\"" },
                    { id: "d", text: "\"Tecnologia acima de tudo\"" },
                ],
                correctOptionId: "b",
                explanation: "O lema é \"não deixar ninguém para trás\". Os ODS só fazem sentido se chegarem a todas as pessoas, inclusive as mais pobres, as que moram longe e as que costumam ser esquecidas.",
            },
            {
                id: "q2",
                prompt: "Qual é o ODS número 1, o primeiro da lista?",
                options: [
                    { id: "a", text: "Erradicação da pobreza" },
                    { id: "b", text: "Vida na água" },
                    { id: "c", text: "Energia limpa e acessível" },
                    { id: "d", text: "Parcerias e meios de implementação" },
                ],
                correctOptionId: "a",
                explanation: "O ODS 1 é Erradicação da pobreza: acabar com a pobreza em todas as suas formas, em todos os lugares. Ele vem primeiro porque a pobreza afeta quase tudo: alimentação, saúde, educação e moradia.",
            },
            {
                id: "q3",
                prompt: "Campanhas de vacinação e o cuidado com a saúde das pessoas fazem parte de qual ODS?",
                options: [
                    { id: "a", text: "ODS 9 – Indústria, inovação e infraestrutura" },
                    { id: "b", text: "ODS 15 – Vida terrestre" },
                    { id: "c", text: "ODS 3 – Saúde e bem-estar" },
                    { id: "d", text: "ODS 11 – Cidades e comunidades sustentáveis" },
                ],
                correctOptionId: "c",
                explanation: "É o ODS 3, Saúde e bem-estar. Ele quer garantir uma vida saudável para pessoas de todas as idades, com vacinas, atendimento médico e prevenção de doenças.",
            },
            {
                id: "q4",
                prompt: "Meninas e meninos terem as mesmas oportunidades na escola, no esporte e no trabalho é o tema de qual ODS?",
                options: [
                    { id: "a", text: "ODS 1 – Erradicação da pobreza" },
                    { id: "b", text: "ODS 5 – Igualdade de gênero" },
                    { id: "c", text: "ODS 7 – Energia limpa e acessível" },
                    { id: "d", text: "ODS 14 – Vida na água" },
                ],
                correctOptionId: "b",
                explanation: "É o ODS 5, Igualdade de gênero. Na tecnologia isso é muito importante: ainda há poucas mulheres programando, e qualquer pessoa, menina ou menino, pode aprender a programar.",
            },
            {
                id: "q5",
                prompt: "Painéis solares e turbinas de vento (energia eólica) ajudam principalmente qual ODS?",
                options: [
                    { id: "a", text: "ODS 7 – Energia limpa e acessível" },
                    { id: "b", text: "ODS 2 – Fome zero" },
                    { id: "c", text: "ODS 16 – Paz, justiça e instituições eficazes" },
                    { id: "d", text: "ODS 4 – Educação de qualidade" },
                ],
                correctOptionId: "a",
                explanation: "É o ODS 7, Energia limpa e acessível. O sol e o vento são fontes renováveis, que não acabam e poluem muito menos do que queimar petróleo ou carvão. A ideia também é que todas as casas tenham energia.",
            },
            {
                id: "q6",
                prompt: "Mais ciclovias, ônibus e metrô de qualidade e praças bem cuidadas deixam a cidade melhor para todos. Isso é tema de qual ODS?",
                options: [
                    { id: "a", text: "ODS 13 – Ação contra a mudança global do clima" },
                    { id: "b", text: "ODS 3 – Saúde e bem-estar" },
                    { id: "c", text: "ODS 6 – Água potável e saneamento" },
                    { id: "d", text: "ODS 11 – Cidades e comunidades sustentáveis" },
                ],
                correctOptionId: "d",
                explanation: "É o ODS 11, Cidades e comunidades sustentáveis. Ele quer cidades seguras e boas de viver, com transporte público, moradia digna, áreas verdes e menos poluição.",
            },
            {
                id: "q7",
                prompt: "Combater o desmatamento e proteger as florestas e os animais que vivem nelas, como na Amazônia, é o foco de qual ODS?",
                options: [
                    { id: "a", text: "ODS 14 – Vida na água" },
                    { id: "b", text: "ODS 15 – Vida terrestre" },
                    { id: "c", text: "ODS 8 – Trabalho decente e crescimento econômico" },
                    { id: "d", text: "ODS 12 – Consumo e produção responsáveis" },
                ],
                correctOptionId: "b",
                explanation: "É o ODS 15, Vida terrestre. As florestas guardam muitas espécies de plantas e animais, ajudam a trazer chuva e a controlar o clima. O ODS 14, Vida na água, cuida dos mares e rios.",
            },
            {
                id: "q8",
                prompt: "Rampas, legendas e sites acessíveis para que pessoas com deficiência participem de tudo ajudam qual ODS?",
                options: [
                    { id: "a", text: "ODS 10 – Redução das desigualdades" },
                    { id: "b", text: "ODS 2 – Fome zero" },
                    { id: "c", text: "ODS 7 – Energia limpa e acessível" },
                    { id: "d", text: "ODS 6 – Água potável e saneamento" },
                ],
                correctOptionId: "a",
                explanation: "É o ODS 10, Redução das desigualdades. Ele quer incluir todas as pessoas, qualquer que seja a idade, a cor, a origem, a deficiência ou a condição financeira. Quem programa ajuda criando sites e apps que todo mundo consegue usar.",
            },
            {
                id: "q9",
                prompt: "Acabar com o trabalho infantil, para que crianças possam estudar e brincar, é uma das metas de qual ODS?",
                options: [
                    { id: "a", text: "ODS 9 – Indústria, inovação e infraestrutura" },
                    { id: "b", text: "ODS 13 – Ação contra a mudança global do clima" },
                    { id: "c", text: "ODS 8 – Trabalho decente e crescimento econômico" },
                    { id: "d", text: "ODS 15 – Vida terrestre" },
                ],
                correctOptionId: "c",
                explanation: "É o ODS 8, Trabalho decente e crescimento econômico. Ele defende empregos com salário justo e segurança para os adultos, e uma de suas metas é acabar com o trabalho infantil.",
            },
            {
                id: "q10",
                prompt: "Levar internet para mais lugares e incentivar novas invenções e tecnologias faz parte de qual ODS?",
                options: [
                    { id: "a", text: "ODS 5 – Igualdade de gênero" },
                    { id: "b", text: "ODS 1 – Erradicação da pobreza" },
                    { id: "c", text: "ODS 14 – Vida na água" },
                    { id: "d", text: "ODS 9 – Indústria, inovação e infraestrutura" },
                ],
                correctOptionId: "d",
                explanation: "É o ODS 9, Indústria, inovação e infraestrutura. Estradas, energia, internet e novas tecnologias ajudam um país a se desenvolver. A programação é uma das grandes ferramentas de inovação!",
            },
        ],
    },
    {
        title: "Scratch parte 2",
        icon: "🐈",
        difficulty: "medio",
        minLevel: 1,
        description: "Mais blocos do Scratch: teclas, perguntas, clones, sons e seus próprios blocos",
        rewardXp: 180,
        rewardCoins: 80,
        rewardItem: {
            name: "Clone do Gato",
            icon: "🐈",
            description: "Um gatinho criado pelo bloco \"crie clone de mim mesmo\". Usar libera a energia do clone em forma de XP.",
            rarity: "raro",
            value: 30,
            xp: 60,
        },
        kind: "quiz",
        questions: [
            {
                id: "q1",
                prompt: "O que o bloco \"se tocar na borda, volte\" faz?",
                options: [
                    { id: "a", text: "Apaga o ator quando ele toca a borda" },
                    { id: "b", text: "Faz o ator voltar para o centro do palco" },
                    { id: "c", text: "Faz o ator mudar de direção quando encosta na borda do palco, sem sair da tela" },
                    { id: "d", text: "Para o projeto" },
                ],
                correctOptionId: "c",
                explanation: "Quando o ator encosta na borda, ele \"quica\" e muda de direção, como uma bola batendo na parede. Junto com \"mova 10 passos\" dentro de um \"sempre\", o ator fica indo e voltando pelo palco.",
            },
            {
                id: "q2",
                prompt: "O bloco \"adicione 10 a x\" faz o ator se mexer para qual lado?",
                options: [
                    { id: "a", text: "Para a direita" },
                    { id: "b", text: "Para a esquerda" },
                    { id: "c", text: "Para cima" },
                    { id: "d", text: "Para baixo" },
                ],
                correctOptionId: "a",
                explanation: "O x é a posição na horizontal: aumentar o x leva o ator para a direita, e diminuir (\"adicione -10 a x\") leva para a esquerda. Para cima e para baixo, quem muda é o y.",
            },
            {
                id: "q3",
                prompt: "Depois do bloco \"aponte para a direção 90\", para onde o ator fica virado?",
                options: [
                    { id: "a", text: "Para cima" },
                    { id: "b", text: "Para baixo" },
                    { id: "c", text: "Para a esquerda" },
                    { id: "d", text: "Para a direita" },
                ],
                correctOptionId: "d",
                explanation: "No Scratch, 90 é para a direita, -90 é para a esquerda, 0 é para cima e 180 é para baixo. É por isso que o gato começa todo projeto olhando para a direita: a direção inicial dele é 90.",
            },
            {
                id: "q4",
                prompt: "Para o ator perguntar o nome do jogador e depois usar o que ele digitou, quais blocos você usa?",
                options: [
                    { id: "a", text: "\"diga\" e \"pense\"" },
                    { id: "b", text: "\"pergunte ... e espere\" e o bloco \"resposta\"" },
                    { id: "c", text: "\"mova\" e \"gire\"" },
                    { id: "d", text: "\"toque o som\" e \"pare todos os sons\"" },
                ],
                correctOptionId: "b",
                explanation: "O \"pergunte Qual é o seu nome? e espere\" (categoria Sensores) mostra uma caixa para o jogador digitar. O que ele escrever fica guardado no bloco \"resposta\", que você pode usar em \"diga\", por exemplo.",
            },
            {
                id: "q5",
                prompt: "Num jogo de nave, você quer que cada tiro seja uma cópia do mesmo ator. Que blocos fazem isso?",
                options: [
                    { id: "a", text: "\"crie clone de mim mesmo\" e \"quando eu começar como clone\"" },
                    { id: "b", text: "\"mostre\" e \"esconda\"" },
                    { id: "c", text: "\"mude x para\" e \"mude y para\"" },
                    { id: "d", text: "\"espere 1 seg\" e \"repita\"" },
                ],
                correctOptionId: "a",
                explanation: "Os clones são cópias de um ator criadas enquanto o projeto roda (categoria Controle). O \"crie clone de mim mesmo\" faz a cópia, e o script \"quando eu começar como clone\" diz o que cada cópia faz, como voar para cima. No fim, \"apague este clone\" remove a cópia.",
            },
            {
                id: "q6",
                prompt: "Qual bloco faz um script começar quando o jogador aperta a barra de espaço?",
                options: [
                    { id: "a", text: "\"espere 1 seg\"" },
                    { id: "b", text: "\"quando a bandeira verde for clicada\"" },
                    { id: "c", text: "\"quando a tecla espaço for pressionada\"" },
                    { id: "d", text: "\"mova 10 passos\"" },
                ],
                correctOptionId: "c",
                explanation: "O \"quando a tecla espaço for pressionada\" é da categoria Eventos e começa o script sempre que a tecla é apertada. Dá para escolher outras teclas, como as setas, para controlar um personagem.",
            },
            {
                id: "q7",
                prompt: "Qual bloco verifica se a variável \"pontos\" passou de 10, para usar dentro de um \"se ... então\"?",
                options: [
                    { id: "a", text: "(pontos) + (10)" },
                    { id: "b", text: "(pontos) > (10)" },
                    { id: "c", text: "adicione 10 a pontos" },
                    { id: "d", text: "mude pontos para 10" },
                ],
                correctOptionId: "b",
                explanation: "O bloco \"maior que\" ( > ), da categoria Operadores, compara dois valores e responde verdadeiro ou falso. Por isso ele tem formato de hexágono e se encaixa no \"se ... então\": se pontos > 10, então você passa de fase!",
            },
            {
                id: "q8",
                prompt: "Para um ator sumir do palco e aparecer de novo mais tarde, quais blocos você usa?",
                options: [
                    { id: "a", text: "\"pare tudo\" e \"bandeira verde\"" },
                    { id: "b", text: "\"apague este clone\" e \"crie clone\"" },
                    { id: "c", text: "\"gire 180 graus\" e \"gire -180 graus\"" },
                    { id: "d", text: "\"esconda\" e \"mostre\"" },
                ],
                correctOptionId: "d",
                explanation: "Os blocos \"esconda\" e \"mostre\" ficam na categoria Aparência. O ator escondido continua existindo e rodando os scripts dele, só não aparece. É útil para itens que surgem só em certos momentos.",
            },
            {
                id: "q9",
                prompt: "Qual é a diferença entre \"toque o som Miau até o fim\" e \"inicie o som Miau\"?",
                options: [
                    { id: "a", text: "O primeiro espera o som terminar para ir ao próximo bloco; o segundo começa o som e já segue em frente" },
                    { id: "b", text: "Não há diferença" },
                    { id: "c", text: "O segundo não toca nada" },
                    { id: "d", text: "O primeiro toca o som duas vezes" },
                ],
                correctOptionId: "a",
                explanation: "Com \"toque o som ... até o fim\", o script fica parado até o som acabar. Com \"inicie o som\", o som começa e os próximos blocos rodam ao mesmo tempo. Para uma música de fundo enquanto o jogo acontece, o \"inicie o som\" costuma ser melhor.",
            },
            {
                id: "q10",
                prompt: "Para que serve a categoria \"Meus Blocos\"?",
                options: [
                    { id: "a", text: "Para ver os blocos que você mais usou" },
                    { id: "b", text: "Para criar seus próprios blocos, juntando vários blocos em um só com um nome que você escolhe" },
                    { id: "c", text: "Para baixar blocos da internet" },
                    { id: "d", text: "Para apagar blocos do projeto" },
                ],
                correctOptionId: "b",
                explanation: "Em \"Meus Blocos\" você cria um bloco novo, como \"desenhe quadrado\", e define o que ele faz. Depois é só usar esse bloco sempre que precisar, em vez de repetir os mesmos blocos várias vezes. Os programadores chamam isso de função.",
            },
        ],
    },
    {
        title: "MIT App Inventor",
        icon: "📱",
        difficulty: "iniciante",
        minLevel: 1,
        description: "Crie aplicativos para celular com blocos: Designer, componentes, eventos e o app MIT AI2 Companion",
        rewardXp: 150,
        rewardCoins: 60,
        rewardItem: {
            name: "Celular de Blocos",
            icon: "📱",
            description: "Um celular montado peça por peça no App Inventor. Usar transforma cada componente em XP.",
            rarity: "comum",
            value: 15,
            xp: 40,
        },
        kind: "quiz",
        questions: [
            {
                id: "q1",
                prompt: "O que é o MIT App Inventor?",
                options: [
                    { id: "a", text: "Um jogo de celular" },
                    { id: "b", text: "Uma loja de aplicativos" },
                    { id: "c", text: "Uma ferramenta online para criar aplicativos de celular encaixando blocos" },
                    { id: "d", text: "Um modelo de celular" },
                ],
                correctOptionId: "c",
                explanation: "O App Inventor é uma ferramenta gratuita, que funciona no navegador, para criar aplicativos de celular. Assim como o Scratch, ele também foi criado com a participação do MIT e usa blocos de encaixar em vez de código digitado.",
            },
            {
                id: "q2",
                prompt: "O App Inventor tem duas áreas principais de trabalho. Quais são elas?",
                options: [
                    { id: "a", text: "Designer (onde você monta a tela) e Blocos (onde você programa o que o app faz)" },
                    { id: "b", text: "Palco e Fantasias" },
                    { id: "c", text: "Teclado e Mouse" },
                    { id: "d", text: "Fotos e Vídeos" },
                ],
                correctOptionId: "a",
                explanation: "No Designer você arrasta botões, textos e imagens para a tela do celular e ajusta a aparência deles. Em Blocos você diz o que acontece, por exemplo, quando alguém toca num botão. Dá para trocar entre os dois pelos botões no canto superior direito.",
            },
            {
                id: "q3",
                prompt: "Qual componente mostra um texto na tela que o usuário apenas lê, sem poder editar?",
                options: [
                    { id: "a", text: "CaixaDeTexto (TextBox)" },
                    { id: "b", text: "Legenda (Label)" },
                    { id: "c", text: "Botão (Button)" },
                    { id: "d", text: "Som (Sound)" },
                ],
                correctOptionId: "b",
                explanation: "A Legenda (Label) só mostra um texto, como um título ou um resultado. Quando o usuário precisa digitar algo, como o nome dele, usamos a CaixaDeTexto (TextBox).",
            },
            {
                id: "q4",
                prompt: "O bloco \"quando Botão1.Clique faça\" é um evento. O que ele quer dizer?",
                options: [
                    { id: "a", text: "Que o botão vai sumir sozinho" },
                    { id: "b", text: "Que o app vai fechar" },
                    { id: "c", text: "Que o botão muda de cor sozinho a cada segundo" },
                    { id: "d", text: "Que os blocos de dentro rodam toda vez que o usuário tocar no Botão1" },
                ],
                correctOptionId: "d",
                explanation: "Eventos esperam algo acontecer. O \"quando Botão1.Clique faça\" fica aguardando: cada vez que alguém toca no Botão1, os blocos encaixados dentro dele são executados. É parecido com o \"quando este ator for clicado\" do Scratch.",
            },
            {
                id: "q5",
                prompt: "O que acontece quando o usuário toca no botão, com estes blocos?",
                code: "quando Botão1.Clique faça\n    ajustar Legenda1.Texto para \"Olá, mundo!\"",
                options: [
                    { id: "a", text: "O celular desliga" },
                    { id: "b", text: "A Legenda1 passa a mostrar o texto \"Olá, mundo!\"" },
                    { id: "c", text: "O Botão1 é apagado" },
                    { id: "d", text: "Nada, porque falta uma imagem" },
                ],
                correctOptionId: "b",
                explanation: "O bloco \"ajustar Legenda1.Texto para\" muda o texto que a Legenda1 mostra. Como ele está dentro do evento de clique, a troca acontece quando o botão é tocado. Quase todo app começa com um exemplo assim!",
            },
            {
                id: "q6",
                prompt: "Para testar o app no seu celular enquanto ainda está criando, o que você usa?",
                options: [
                    { id: "a", text: "O aplicativo MIT AI2 Companion, lendo o código QR que aparece no computador" },
                    { id: "b", text: "Uma impressora" },
                    { id: "c", text: "O Scratch" },
                    { id: "d", text: "Não dá para testar no celular" },
                ],
                correctOptionId: "a",
                explanation: "Instalando o app MIT AI2 Companion no celular, você conecta pelo menu Conectar → AI Companion e lê o código QR. Aí cada mudança feita no computador aparece na hora no celular.",
            },
            {
                id: "q7",
                prompt: "Qual componente transforma um texto em voz, fazendo o celular \"falar\"?",
                options: [
                    { id: "a", text: "Legenda (Label)" },
                    { id: "b", text: "Imagem (Image)" },
                    { id: "c", text: "TextoParaFala (TextToSpeech)" },
                    { id: "d", text: "Botão (Button)" },
                ],
                correctOptionId: "c",
                explanation: "O TextoParaFala (TextToSpeech) lê em voz alta o texto que você mandar. Ele é um componente não visível: não aparece na tela do app, mas fica listado embaixo do celular no Designer.",
            },
            {
                id: "q8",
                prompt: "Qual sensor do celular permite que o app perceba quando o aparelho é sacudido?",
                options: [
                    { id: "a", text: "O sensor acelerômetro (AccelerometerSensor)" },
                    { id: "b", text: "A câmera" },
                    { id: "c", text: "A Legenda" },
                    { id: "d", text: "O alto-falante" },
                ],
                correctOptionId: "a",
                explanation: "O acelerômetro mede os movimentos do celular. Com ele dá para fazer, por exemplo, um app de dado que sorteia um número quando você sacode o aparelho. Também é um componente não visível.",
            },
            {
                id: "q9",
                prompt: "No Designer, onde você muda a cor, o tamanho da letra e o texto de um botão?",
                options: [
                    { id: "a", text: "Na área de Blocos" },
                    { id: "b", text: "No painel Propriedades, com o botão selecionado" },
                    { id: "c", text: "No menu Ajuda" },
                    { id: "d", text: "Não dá para mudar a aparência dos componentes" },
                ],
                correctOptionId: "b",
                explanation: "Ao selecionar um componente no Designer, o painel Propriedades (à direita) mostra tudo que dá para ajustar nele: cor de fundo, texto, tamanho da fonte, largura e muito mais. Essas propriedades também podem ser mudadas por blocos, enquanto o app roda.",
            },
            {
                id: "q10",
                prompt: "Qual é a extensão do arquivo do aplicativo pronto para instalar num celular Android?",
                options: [
                    { id: "a", text: ".sb3" },
                    { id: "b", text: ".html" },
                    { id: "c", text: ".pdf" },
                    { id: "d", text: ".apk" },
                ],
                correctOptionId: "d",
                explanation: "O .apk é o aplicativo pronto para instalar no Android, gerado pelo menu Compilar (Build). Já o .aia é o projeto do App Inventor, que você pode abrir e continuar editando depois. Nas missões de entrega da CodeGuilds, os dois tipos são aceitos.",
            },
        ],
    },
    {
        title: "HTML",
        icon: "🏷️",
        difficulty: "iniciante",
        minLevel: 1,
        description: "As tags que formam toda página da internet: títulos, parágrafos, links, imagens e listas",
        rewardXp: 150,
        rewardCoins: 60,
        rewardItem: {
            name: "Tag Perdida",
            icon: "🏷️",
            description: "Uma tag que fugiu de uma página antiga e nunca foi fechada. Usar fecha a tag e libera XP.",
            rarity: "comum",
            value: 15,
            xp: 40,
        },
        kind: "quiz",
        questions: [
            {
                id: "q1",
                prompt: "Para que serve o HTML?",
                options: [
                    { id: "a", text: "Para montar a estrutura e o conteúdo das páginas da internet" },
                    { id: "b", text: "Para editar fotos" },
                    { id: "c", text: "Para criar jogos 3D" },
                    { id: "d", text: "Para guardar arquivos na nuvem" },
                ],
                correctOptionId: "a",
                explanation: "HTML (HyperText Markup Language) é uma linguagem de marcação: ela diz o que é cada parte da página, como título, parágrafo, imagem e link. Toda página da internet tem HTML. A aparência fica com o CSS.",
            },
            {
                id: "q2",
                prompt: "Qual tag cria o título principal, o maior, de uma página?",
                options: [
                    { id: "a", text: "<p>" },
                    { id: "b", text: "<title>" },
                    { id: "c", text: "<h1>" },
                    { id: "d", text: "<h6>" },
                ],
                correctOptionId: "c",
                explanation: "As tags de título vão de <h1> (o mais importante e maior) até <h6> (o menor). A tag <title> é outra coisa: ela define o nome que aparece na aba do navegador, não um título dentro da página.",
            },
            {
                id: "q3",
                prompt: "Qual tag usamos para escrever um parágrafo de texto?",
                options: [
                    { id: "a", text: "<p>" },
                    { id: "b", text: "<a>" },
                    { id: "c", text: "<img>" },
                    { id: "d", text: "<li>" },
                ],
                correctOptionId: "a",
                explanation: "A tag <p> (de parágrafo) guarda um bloco de texto: <p>Eu gosto de programar!</p>. Cada parágrafo começa numa linha nova.",
            },
            {
                id: "q4",
                prompt: "O que falta neste código para o parágrafo ficar correto?",
                code: "<p>Olá, CodeGuilds!<p>",
                options: [
                    { id: "a", text: "Uma imagem" },
                    { id: "b", text: "A barra na tag de fechamento: </p>" },
                    { id: "c", text: "Escrever tudo em letras maiúsculas" },
                    { id: "d", text: "Nada, está correto" },
                ],
                correctOptionId: "b",
                explanation: "A maioria das tags vem em par: uma abre (<p>) e outra fecha (</p>), com uma barra. O conteúdo fica entre as duas. Esquecer de fechar uma tag é um dos bugs mais comuns no HTML.",
            },
            {
                id: "q5",
                prompt: "Qual código cria um link que leva para o site do Scratch?",
                options: [
                    { id: "a", text: "<link>scratch.mit.edu</link>" },
                    { id: "b", text: "<p href=\"https://scratch.mit.edu\">Scratch</p>" },
                    { id: "c", text: "<a href=\"https://scratch.mit.edu\">Scratch</a>" },
                    { id: "d", text: "<img src=\"https://scratch.mit.edu\">" },
                ],
                correctOptionId: "c",
                explanation: "Links usam a tag <a>. O endereço vai no atributo href, e o texto clicável fica entre <a> e </a>. Atributos são informações extras que colocamos dentro da tag de abertura.",
            },
            {
                id: "q6",
                prompt: "Na tag <img src=\"gato.png\" alt=\"Um gato laranja\">, para que serve o atributo alt?",
                options: [
                    { id: "a", text: "Para aumentar o tamanho da imagem" },
                    { id: "b", text: "Para descrever a imagem para quem não consegue vê-la, como pessoas cegas que usam leitores de tela" },
                    { id: "c", text: "Para mudar a cor da imagem" },
                    { id: "d", text: "Para transformar a imagem num link" },
                ],
                correctOptionId: "b",
                explanation: "O src diz qual arquivo de imagem mostrar, e o alt é um texto que descreve a imagem. Leitores de tela leem o alt em voz alta, e ele também aparece se a imagem não carregar. Isso é acessibilidade! Repare também que a <img> não tem tag de fechamento.",
            },
            {
                id: "q7",
                prompt: "Qual código cria uma lista com marcadores (bolinhas)?",
                options: [
                    { id: "a", text: "<ul>\n  <li>Scratch</li>\n  <li>HTML</li>\n</ul>" },
                    { id: "b", text: "<p>Scratch, HTML</p>" },
                    { id: "c", text: "<h1>Scratch</h1><h1>HTML</h1>" },
                    { id: "d", text: "<list>Scratch, HTML</list>" },
                ],
                correctOptionId: "a",
                explanation: "A tag <ul> (lista não ordenada) cria uma lista com bolinhas, e cada item fica numa tag <li>. Se você quiser itens numerados (1, 2, 3...), troque o <ul> por <ol> (lista ordenada).",
            },
            {
                id: "q8",
                prompt: "Uma página HTML tem duas partes principais: <head> e <body>. Onde fica o conteúdo que aparece na tela?",
                options: [
                    { id: "a", text: "No <head>" },
                    { id: "b", text: "Fora das duas" },
                    { id: "c", text: "No <body>" },
                    { id: "d", text: "Em um arquivo separado obrigatoriamente" },
                ],
                correctOptionId: "c",
                explanation: "O <body> (corpo) guarda tudo que aparece na página: títulos, textos, imagens e links. O <head> (cabeça) guarda informações sobre a página, como o <title> da aba e o link para o arquivo de CSS.",
            },
            {
                id: "q9",
                prompt: "Qual tag deixa um texto importante em negrito?",
                code: "<p>Atenção: a prova é <???>amanhã</???>!</p>",
                options: [
                    { id: "a", text: "<br>" },
                    { id: "b", text: "<strong>" },
                    { id: "c", text: "<ul>" },
                    { id: "d", text: "<h6>" },
                ],
                correctOptionId: "b",
                explanation: "A tag <strong> marca um texto como importante, e o navegador mostra em negrito. Já a tag <br> é uma quebra de linha: faz o texto continuar na linha de baixo.",
            },
            {
                id: "q10",
                prompt: "Você criou o arquivo da sua página no computador. Com que extensão ele deve ser salvo para abrir no navegador?",
                options: [
                    { id: "a", text: ".sb3" },
                    { id: "b", text: ".docx" },
                    { id: "c", text: ".apk" },
                    { id: "d", text: ".html" },
                ],
                correctOptionId: "d",
                explanation: "Páginas da internet são arquivos .html. Dá para escrevê-las num editor de código (como o VS Code) ou até no Bloco de Notas, salvar como index.html e abrir com dois cliques no navegador.",
            },
        ],
    },
    {
        title: "CSS",
        icon: "🎨",
        difficulty: "iniciante",
        minLevel: 1,
        description: "Dê estilo às suas páginas: cores, tamanhos, fontes, espaçamentos e seletores",
        rewardXp: 150,
        rewardCoins: 60,
        rewardItem: {
            name: "Pincel de Estilos",
            icon: "🖌️",
            description: "Um pincel que pinta qualquer página com uma linha de CSS. Usar transforma as cores em XP.",
            rarity: "comum",
            value: 15,
            xp: 40,
        },
        kind: "quiz",
        questions: [
            {
                id: "q1",
                prompt: "Se o HTML é a estrutura da página, para que serve o CSS?",
                options: [
                    { id: "a", text: "Para guardar senhas" },
                    { id: "b", text: "Para cuidar da aparência: cores, tamanhos, fontes e posição dos elementos" },
                    { id: "c", text: "Para criar o banco de dados" },
                    { id: "d", text: "Para conectar o computador à internet" },
                ],
                correctOptionId: "b",
                explanation: "CSS (Cascading Style Sheets, ou folhas de estilo em cascata) define o visual da página. Pense numa casa: o HTML são as paredes e os cômodos, e o CSS é a pintura, os móveis e a decoração.",
            },
            {
                id: "q2",
                prompt: "O que este código CSS faz?",
                code: "h1 {\n  color: blue;\n}",
                options: [
                    { id: "a", text: "Apaga todos os títulos" },
                    { id: "b", text: "Deixa só o primeiro título azul" },
                    { id: "c", text: "Deixa o texto de todos os <h1> da página azul" },
                    { id: "d", text: "Deixa o fundo da página azul" },
                ],
                correctOptionId: "c",
                explanation: "O h1 antes das chaves é o seletor: ele escolhe quais elementos vão receber o estilo, no caso todos os <h1>. Dentro das chaves fica a regra: a propriedade color (cor do texto) com o valor blue (azul).",
            },
            {
                id: "q3",
                prompt: "Qual propriedade muda a cor de FUNDO de um elemento?",
                options: [
                    { id: "a", text: "background-color" },
                    { id: "b", text: "color" },
                    { id: "c", text: "font-size" },
                    { id: "d", text: "text-align" },
                ],
                correctOptionId: "a",
                explanation: "background-color muda a cor de fundo, e color muda a cor do texto. Por exemplo, body { background-color: black; color: white; } deixa a página com fundo preto e letras brancas.",
            },
            {
                id: "q4",
                prompt: "Qual propriedade aumenta o tamanho da letra?",
                options: [
                    { id: "a", text: "color" },
                    { id: "b", text: "margin" },
                    { id: "c", text: "font-size" },
                    { id: "d", text: "border" },
                ],
                correctOptionId: "c",
                explanation: "font-size define o tamanho da fonte, por exemplo p { font-size: 20px; }. O px (pixels) é uma unidade de medida da tela. Outra propriedade de fonte é a font-family, que escolhe o tipo de letra.",
            },
            {
                id: "q5",
                prompt: "No HTML temos <p class=\"destaque\">. Qual seletor CSS escolhe esse elemento pela classe?",
                options: [
                    { id: "a", text: "destaque { }" },
                    { id: "b", text: "#destaque { }" },
                    { id: "c", text: "<destaque> { }" },
                    { id: "d", text: ".destaque { }" },
                ],
                correctOptionId: "d",
                explanation: "Classes são selecionadas com um ponto antes do nome: .destaque. Vários elementos podem ter a mesma classe e ganham o mesmo estilo. Já o # seleciona por id (#menu), que deve ser único na página.",
            },
            {
                id: "q6",
                prompt: "Como ligamos um arquivo estilo.css a uma página HTML?",
                options: [
                    { id: "a", text: "Com <link rel=\"stylesheet\" href=\"estilo.css\"> dentro do <head>" },
                    { id: "b", text: "Com <img src=\"estilo.css\">" },
                    { id: "c", text: "Com <a href=\"estilo.css\">Estilo</a>" },
                    { id: "d", text: "Não dá, o CSS precisa estar dentro de cada tag" },
                ],
                correctOptionId: "a",
                explanation: "A tag <link> no <head> avisa ao navegador que a página usa aquele arquivo de estilos. Deixar o CSS num arquivo separado é bom porque várias páginas podem usar o mesmo estilo, e basta mudar num lugar só.",
            },
            {
                id: "q7",
                prompt: "No CSS, cores podem ser escritas em código hexadecimal. Qual cor é #FF0000?",
                options: [
                    { id: "a", text: "Verde" },
                    { id: "b", text: "Azul" },
                    { id: "c", text: "Vermelho" },
                    { id: "d", text: "Preto" },
                ],
                correctOptionId: "c",
                explanation: "O código hexadecimal tem 3 pares: vermelho, verde e azul (RGB). FF é o máximo e 00 é nada. Então #FF0000 é vermelho no máximo, sem verde e sem azul. #000000 é preto e #FFFFFF é branco.",
            },
            {
                id: "q8",
                prompt: "Qual é a diferença entre padding e margin?",
                options: [
                    { id: "a", text: "Não há diferença" },
                    { id: "b", text: "padding é o espaço DENTRO do elemento, entre o conteúdo e a borda; margin é o espaço FORA, entre o elemento e os vizinhos" },
                    { id: "c", text: "padding muda a cor e margin muda a fonte" },
                    { id: "d", text: "margin só funciona em imagens" },
                ],
                correctOptionId: "b",
                explanation: "Todo elemento é como uma caixa: o conteúdo no meio, o padding em volta dele, depois a borda (border) e, por fora, a margin. Esse é o \"modelo de caixa\" do CSS, a base para organizar os espaços da página.",
            },
            {
                id: "q9",
                prompt: "Qual destas regras CSS está escrita corretamente?",
                options: [
                    { id: "a", text: "p { color red }" },
                    { id: "b", text: "p ( color: red; )" },
                    { id: "c", text: "p { color: red; }" },
                    { id: "d", text: "p = color: red" },
                ],
                correctOptionId: "c",
                explanation: "A regra tem o seletor, depois chaves { }. Dentro, cada propriedade é seguida de dois pontos, do valor e de ponto e vírgula: color: red;. Se faltar um desses sinais, o navegador ignora a regra, e o estilo não aparece.",
            },
            {
                id: "q10",
                prompt: "Qual regra deixa o texto de um título centralizado na página?",
                options: [
                    { id: "a", text: "h1 { font-size: center; }" },
                    { id: "b", text: "h1 { color: center; }" },
                    { id: "c", text: "h1 { margin: 0; }" },
                    { id: "d", text: "h1 { text-align: center; }" },
                ],
                correctOptionId: "d",
                explanation: "A propriedade text-align alinha o texto: left (esquerda), right (direita) ou center (centro). As outras opções misturam propriedades com valores que elas não aceitam.",
            },
        ],
    },
]

export default missions
