import { MissionContent } from "../../../src/engine/missions";

// Sexta leva de missões de quiz para as turmas de programação, só de
// linguagens: JavaScript parte 3, Python parte 3, CSS parte 2, HTML parte 2,
// Linguagem Lua parte 3 e Java parte 3. 10 perguntas cada, todas comentadas,
// sem repetir as das levas anteriores. Nível mínimo 50 em todas (o professor
// ajusta depois no painel). Importar com:
//   npm run missions:import -- <e-mail do professor> scripts/missions/programacao-12-anos-parte-6.ts
const missions: MissionContent[] = [
    {
        title: "JavaScript parte 3",
        icon: "🧠",
        difficulty: "avancado",
        minLevel: 50,
        description: "JavaScript avançando: typeof, resto da divisão, arrow functions, map, filter, includes, setTimeout e mais",
        rewardXp: 320,
        rewardCoins: 130,
        rewardItem: {
            name: "Cérebro do Interpretador",
            icon: "🧠",
            description: "O cérebro que lê cada linha de JavaScript da página. Usar transforma o raciocínio em XP.",
            rarity: "epico",
            value: 50,
            xp: 90,
        },
        kind: "quiz",
        questions: [
            {
                id: "q1",
                prompt: "O que este código mostra no console?",
                code: "console.log(typeof \"olá\");",
                options: [
                    { id: "a", text: "\"number\"" },
                    { id: "b", text: "\"string\"" },
                    { id: "c", text: "\"boolean\"" },
                    { id: "d", text: "\"olá\"" },
                ],
                correctOptionId: "b",
                explanation: "O typeof diz o tipo de um valor. Texto entre aspas é \"string\", números são \"number\" e true/false são \"boolean\". Ele ajuda a descobrir por que uma conta deu errado: às vezes o \"número\" é, na verdade, um texto.",
            },
            {
                id: "q2",
                prompt: "Qual condição descobre se o número n é par?",
                options: [
                    { id: "a", text: "n / 2 === 0" },
                    { id: "b", text: "n * 2 === 0" },
                    { id: "c", text: "n % 2 === 0" },
                    { id: "d", text: "n - 2 === 0" },
                ],
                correctOptionId: "c",
                explanation: "O % dá o resto da divisão. Número par dividido por 2 tem resto 0 (8 % 2 é 0) e ímpar tem resto 1 (7 % 2 é 1). Isso é usado, por exemplo, pra pintar as linhas de uma tabela de cores alternadas.",
            },
            {
                id: "q3",
                prompt: "O que este código mostra?",
                code: "const dobro = (n) => n * 2;\nconsole.log(dobro(7));",
                options: [
                    { id: "a", text: "7" },
                    { id: "b", text: "72" },
                    { id: "c", text: "Um erro" },
                    { id: "d", text: "14" },
                ],
                correctOptionId: "d",
                explanation: "Isso é uma arrow function (função flecha): um jeito curto de escrever funções com =>. Ela recebe n e devolve n * 2, então dobro(7) dá 14. É o mesmo que function dobro(n) { return n * 2; }.",
            },
            {
                id: "q4",
                prompt: "O que este código mostra?",
                code: "const notas = [4, 9, 6, 10];\nconst boas = notas.filter((n) => n >= 6);\nconsole.log(boas);",
                options: [
                    { id: "a", text: "[9, 6, 10]" },
                    { id: "b", text: "[4]" },
                    { id: "c", text: "3" },
                    { id: "d", text: "[4, 9, 6, 10]" },
                ],
                correctOptionId: "a",
                explanation: "O filter cria um array novo só com os itens que passam no teste. Aqui ficam as notas maiores ou iguais a 6: [9, 6, 10]. O array original não muda.",
            },
            {
                id: "q5",
                prompt: "O que este código mostra?",
                code: "const precos = [10, 20, 30];\nconst comDesconto = precos.map((p) => p / 2);\nconsole.log(comDesconto);",
                options: [
                    { id: "a", text: "[10, 20, 30]" },
                    { id: "b", text: "[5, 10, 15]" },
                    { id: "c", text: "30" },
                    { id: "d", text: "[20, 40, 60]" },
                ],
                correctOptionId: "b",
                explanation: "O map transforma cada item do array e devolve um array novo do mesmo tamanho. Aqui cada preço é dividido por 2. Map e filter são dos métodos mais usados no JavaScript.",
            },
            {
                id: "q6",
                prompt: "Qual é o resultado de [\"espada\", \"escudo\"].includes(\"escudo\")?",
                options: [
                    { id: "a", text: "1" },
                    { id: "b", text: "\"escudo\"" },
                    { id: "c", text: "true" },
                    { id: "d", text: "false" },
                ],
                correctOptionId: "c",
                explanation: "O includes responde se o item está no array: true (está) ou false (não está). Num jogo, serve pra conferir se o jogador já tem a chave antes de abrir a porta.",
            },
            {
                id: "q7",
                prompt: "O que o setTimeout faz neste código?",
                code: "setTimeout(() => {\n  console.log(\"Boom!\");\n}, 3000);",
                options: [
                    { id: "a", text: "Mostra \"Boom!\" 3000 vezes" },
                    { id: "b", text: "Mostra \"Boom!\" depois de 3 segundos" },
                    { id: "c", text: "Mostra \"Boom!\" a cada 3 segundos, pra sempre" },
                    { id: "d", text: "Apaga a página depois de 3 segundos" },
                ],
                correctOptionId: "b",
                explanation: "O setTimeout espera o tempo indicado em milissegundos (3000 ms = 3 segundos) e então roda a função uma vez. Para repetir de tempos em tempos, existe o setInterval.",
            },
            {
                id: "q8",
                prompt: "O que este código mostra?",
                code: "console.log(Number(\"10\") + 5);",
                options: [
                    { id: "a", text: "\"105\"" },
                    { id: "b", text: "15" },
                    { id: "c", text: "Um erro" },
                    { id: "d", text: "10" },
                ],
                correctOptionId: "b",
                explanation: "O Number() transforma o texto \"10\" no número 10, e 10 + 5 dá 15. Sem a conversão, \"10\" + 5 juntaria os dois como texto e daria \"105\". Converter é essencial quando o valor vem de um campo digitado.",
            },
            {
                id: "q9",
                prompt: "O que este código mostra?",
                code: "const vidas = 0;\nconst mensagem = vidas > 0 ? \"Continue!\" : \"Fim de jogo\";\nconsole.log(mensagem);",
                options: [
                    { id: "a", text: "Continue!" },
                    { id: "b", text: "Fim de jogo" },
                    { id: "c", text: "0" },
                    { id: "d", text: "true" },
                ],
                correctOptionId: "b",
                explanation: "Esse é o operador ternário: condição ? valorSeVerdade : valorSeFalso. Como vidas não é maior que 0, a mensagem fica \"Fim de jogo\". É um if/else curtinho que já devolve um valor.",
            },
            {
                id: "q10",
                prompt: "O que este código mostra?",
                code: "let tesouro;\nconsole.log(tesouro);",
                options: [
                    { id: "a", text: "0" },
                    { id: "b", text: "null" },
                    { id: "c", text: "undefined" },
                    { id: "d", text: "\"tesouro\"" },
                ],
                correctOptionId: "c",
                explanation: "Uma variável criada sem valor vale undefined (\"não definido\"). Já o null é colocado de propósito pelo programador pra dizer \"aqui não tem nada\". Os dois parecem iguais, mas o undefined costuma indicar que faltou dar um valor.",
            },
        ],
    },
    {
        title: "Python parte 3",
        icon: "🐉",
        difficulty: "avancado",
        minLevel: 50,
        description: "Python avançando: percorrer listas, fatiar, repetir textos, in, max, sorted, break, str e try/except",
        rewardXp: 320,
        rewardCoins: 130,
        rewardItem: {
            name: "Serpente Dourada",
            icon: "🐉",
            description: "A píton que cresceu e virou dragão depois de muito código. Usar transforma as escamas douradas em XP.",
            rarity: "epico",
            value: 50,
            xp: 90,
        },
        kind: "quiz",
        questions: [
            {
                id: "q1",
                prompt: "O que este código mostra?",
                code: "for heroi in [\"Mago\", \"Elfa\"]:\n    print(\"Olá,\", heroi)",
                options: [
                    { id: "a", text: "Olá, Mago e depois Olá, Elfa" },
                    { id: "b", text: "Olá, heroi duas vezes" },
                    { id: "c", text: "Olá, [\"Mago\", \"Elfa\"]" },
                    { id: "d", text: "Um erro" },
                ],
                correctOptionId: "a",
                explanation: "O for do Python pode percorrer uma lista item por item: a cada volta, heroi recebe o próximo nome. Por isso aparece uma saudação pra cada herói.",
            },
            {
                id: "q2",
                prompt: "O que este código mostra?",
                code: "print(\"ha\" * 3)",
                options: [
                    { id: "a", text: "ha3" },
                    { id: "b", text: "Um erro" },
                    { id: "c", text: "hahaha" },
                    { id: "d", text: "9" },
                ],
                correctOptionId: "c",
                explanation: "No Python, multiplicar um texto por um número repete o texto: \"ha\" * 3 vira \"hahaha\". Dá pra usar isso pra desenhar linhas, como \"-\" * 20.",
            },
            {
                id: "q3",
                prompt: "Qual é o resultado de \"uva\" in [\"maçã\", \"uva\", \"pera\"]?",
                options: [
                    { id: "a", text: "1" },
                    { id: "b", text: "True" },
                    { id: "c", text: "\"uva\"" },
                    { id: "d", text: "False" },
                ],
                correctOptionId: "b",
                explanation: "O in confere se um item está na lista e responde True ou False. Também funciona com textos: \"py\" in \"python\" dá True.",
            },
            {
                id: "q4",
                prompt: "O que este código mostra?",
                code: "pontos = [12, 45, 7, 30]\nprint(max(pontos))",
                options: [
                    { id: "a", text: "7" },
                    { id: "b", text: "4" },
                    { id: "c", text: "94" },
                    { id: "d", text: "45" },
                ],
                correctOptionId: "d",
                explanation: "O max() devolve o maior valor da lista, e o min() devolve o menor. Para somar tudo, existe o sum(): sum(pontos) daria 94.",
            },
            {
                id: "q5",
                prompt: "O que este código mostra?",
                code: "print(sorted([3, 1, 2]))",
                options: [
                    { id: "a", text: "[1, 2, 3]" },
                    { id: "b", text: "[3, 2, 1]" },
                    { id: "c", text: "[3, 1, 2]" },
                    { id: "d", text: "6" },
                ],
                correctOptionId: "a",
                explanation: "O sorted() devolve uma lista nova em ordem crescente. Com sorted(lista, reverse=True), a ordem fica decrescente, ótimo para montar um ranking.",
            },
            {
                id: "q6",
                prompt: "Quais números este código mostra?",
                code: "for n in range(1, 10):\n    if n == 4:\n        break\n    print(n)",
                options: [
                    { id: "a", text: "1, 2, 3 e 4" },
                    { id: "b", text: "1, 2 e 3" },
                    { id: "c", text: "1 até 9" },
                    { id: "d", text: "Só o 4" },
                ],
                correctOptionId: "b",
                explanation: "O break interrompe o laço na hora. Quando n chega a 4, o laço para antes do print, então aparecem só 1, 2 e 3.",
            },
            {
                id: "q7",
                prompt: "Este código dá erro. Como consertar?",
                code: "idade = 12\nprint(\"Idade: \" + idade)",
                options: [
                    { id: "a", text: "Trocar o + por *" },
                    { id: "b", text: "Usar str(idade), para transformar o número em texto" },
                    { id: "c", text: "Apagar as aspas" },
                    { id: "d", text: "Colocar ponto e vírgula no final" },
                ],
                correctOptionId: "b",
                explanation: "O Python não junta texto com número usando +. O str() transforma o número em texto: \"Idade: \" + str(idade) dá \"Idade: 12\". Outra saída é a f-string: f\"Idade: {idade}\".",
            },
            {
                id: "q8",
                prompt: "O que este código mostra?",
                code: "letras = [\"a\", \"b\", \"c\", \"d\", \"e\"]\nprint(letras[1:3])",
                options: [
                    { id: "a", text: "[\"a\", \"b\", \"c\"]" },
                    { id: "b", text: "[\"b\", \"c\", \"d\"]" },
                    { id: "c", text: "[\"b\", \"c\"]" },
                    { id: "d", text: "\"b\"" },
                ],
                correctOptionId: "c",
                explanation: "O fatiamento [1:3] pega da posição 1 até antes da 3, ou seja, as posições 1 e 2: \"b\" e \"c\". O primeiro número entra e o segundo fica de fora, igual no range().",
            },
            {
                id: "q9",
                prompt: "Para que serve o try/except neste código?",
                code: "try:\n    idade = int(input(\"Idade: \"))\nexcept ValueError:\n    print(\"Digite só números!\")",
                options: [
                    { id: "a", text: "Para repetir a pergunta 10 vezes" },
                    { id: "b", text: "Para o programa não quebrar se a pessoa digitar algo que não é número" },
                    { id: "c", text: "Para apagar o que a pessoa digitou" },
                    { id: "d", text: "Para deixar o programa mais rápido" },
                ],
                correctOptionId: "b",
                explanation: "Se a pessoa digitar \"doze\", o int() dá erro (ValueError). O try tenta rodar o código e, se esse erro acontecer, o except mostra uma mensagem amigável em vez de encerrar o programa.",
            },
            {
                id: "q10",
                prompt: "O que este código mostra?",
                code: "print(10 % 3)",
                options: [
                    { id: "a", text: "3" },
                    { id: "b", text: "3.33" },
                    { id: "c", text: "30" },
                    { id: "d", text: "1" },
                ],
                correctOptionId: "d",
                explanation: "O % dá o resto da divisão: 10 dividido por 3 dá 3 e sobra 1. Ele é muito usado pra saber se um número é par (n % 2 == 0) ou pra fazer algo a cada N vezes.",
            },
        ],
    },
    {
        title: "CSS parte 2",
        icon: "💅",
        difficulty: "medio",
        minLevel: 50,
        description: "Mais CSS: bordas, cantos arredondados, ids, hover, display, fontes, flexbox, opacidade e a cascata",
        rewardXp: 250,
        rewardCoins: 100,
        rewardItem: {
            name: "Paleta Arco-Íris",
            icon: "🌈",
            description: "Uma paleta com todas as cores do CSS. Usar pinta o seu XP de todas as cores.",
            rarity: "raro",
            value: 35,
            xp: 70,
        },
        kind: "quiz",
        questions: [
            {
                id: "q1",
                prompt: "O que a regra border: 2px solid red; faz?",
                options: [
                    { id: "a", text: "Deixa o texto vermelho" },
                    { id: "b", text: "Cria uma borda vermelha, contínua e de 2 pixels em volta do elemento" },
                    { id: "c", text: "Deixa o fundo vermelho" },
                    { id: "d", text: "Esconde o elemento" },
                ],
                correctOptionId: "b",
                explanation: "A propriedade border junta três informações: a espessura (2px), o estilo (solid = linha contínua; dashed = tracejada; dotted = pontilhada) e a cor (red).",
            },
            {
                id: "q2",
                prompt: "Qual propriedade arredonda os cantos de um botão?",
                options: [
                    { id: "a", text: "border-radius" },
                    { id: "b", text: "text-align" },
                    { id: "c", text: "font-size" },
                    { id: "d", text: "corner" },
                ],
                correctOptionId: "a",
                explanation: "O border-radius arredonda os cantos: border-radius: 8px deixa levemente arredondado, e border-radius: 50% transforma um quadrado num círculo, ótimo para fotos de perfil.",
            },
            {
                id: "q3",
                prompt: "No HTML existe <div id=\"menu\">. Qual seletor CSS escolhe esse elemento pelo id?",
                options: [
                    { id: "a", text: ".menu { }" },
                    { id: "b", text: "menu { }" },
                    { id: "c", text: "#menu { }" },
                    { id: "d", text: "*menu { }" },
                ],
                correctOptionId: "c",
                explanation: "O # seleciona pelo id, que deve ser único na página. O ponto (.) seleciona por classe, que pode se repetir em vários elementos.",
            },
            {
                id: "q4",
                prompt: "O que esta regra faz?",
                code: "button:hover {\n  background-color: gold;\n}",
                options: [
                    { id: "a", text: "Deixa todos os botões dourados sempre" },
                    { id: "b", text: "Esconde os botões" },
                    { id: "c", text: "Deixa o botão dourado quando o mouse passa por cima dele" },
                    { id: "d", text: "Deixa o botão dourado depois de clicado para sempre" },
                ],
                correctOptionId: "c",
                explanation: "O :hover é uma pseudo-classe: o estilo só vale enquanto o mouse está em cima do elemento. É assim que os botões \"reagem\" quando você passa o mouse.",
            },
            {
                id: "q5",
                prompt: "Qual regra faz um elemento sumir da página, sem ocupar espaço?",
                options: [
                    { id: "a", text: "display: none;" },
                    { id: "b", text: "color: white;" },
                    { id: "c", text: "font-size: 0px;" },
                    { id: "d", text: "border: none;" },
                ],
                correctOptionId: "a",
                explanation: "Com display: none, o elemento continua no HTML, mas não aparece nem ocupa lugar. É muito usado junto com JavaScript pra abrir e fechar menus.",
            },
            {
                id: "q6",
                prompt: "Qual propriedade escolhe o tipo de letra do texto?",
                options: [
                    { id: "a", text: "font-size" },
                    { id: "b", text: "font-family" },
                    { id: "c", text: "text-align" },
                    { id: "d", text: "letter" },
                ],
                correctOptionId: "b",
                explanation: "O font-family define a fonte, como font-family: Arial, sans-serif;. A segunda opção é uma reserva: se o computador não tiver Arial, usa outra fonte sem serifa.",
            },
            {
                id: "q7",
                prompt: "Que regras deixam os itens de uma caixa lado a lado e centralizados na horizontal?",
                options: [
                    { id: "a", text: "display: none; e text-align: left;" },
                    { id: "b", text: "color: center;" },
                    { id: "c", text: "font-size: center;" },
                    { id: "d", text: "display: flex; e justify-content: center;" },
                ],
                correctOptionId: "d",
                explanation: "O display: flex (flexbox) organiza os filhos de uma caixa em linha, e o justify-content: center os centraliza. O flexbox é uma das ferramentas mais usadas pra montar o layout das páginas.",
            },
            {
                id: "q8",
                prompt: "O que a regra opacity: 0.5; faz com o elemento?",
                options: [
                    { id: "a", text: "Deixa o elemento metade do tamanho" },
                    { id: "b", text: "Deixa o elemento meio transparente" },
                    { id: "c", text: "Gira o elemento pela metade" },
                    { id: "d", text: "Esconde metade do texto" },
                ],
                correctOptionId: "b",
                explanation: "O opacity vai de 0 (invisível) a 1 (totalmente visível). Com 0.5, o elemento fica meio transparente, como o efeito \"fantasma\" do Scratch.",
            },
            {
                id: "q9",
                prompt: "Com estas duas regras no mesmo arquivo, de que cor fica o parágrafo?",
                code: "p { color: blue; }\np { color: green; }",
                options: [
                    { id: "a", text: "Azul" },
                    { id: "b", text: "Verde" },
                    { id: "c", text: "Uma mistura de azul e verde" },
                    { id: "d", text: "Dá erro" },
                ],
                correctOptionId: "b",
                explanation: "É a \"cascata\" do CSS (o C de CSS): quando duas regras iguais disputam a mesma propriedade, vale a que vem por último. Por isso o parágrafo fica verde.",
            },
            {
                id: "q10",
                prompt: "Como escrevemos um comentário no CSS?",
                options: [
                    { id: "a", text: "// comentário" },
                    { id: "b", text: "# comentário" },
                    { id: "c", text: "/* comentário */" },
                    { id: "d", text: "<!-- comentário -->" },
                ],
                correctOptionId: "c",
                explanation: "No CSS, os comentários ficam entre /* e */ e podem ter várias linhas. O <!-- --> é o comentário do HTML, e o // é do JavaScript.",
            },
        ],
    },
    {
        title: "HTML parte 2",
        icon: "📄",
        difficulty: "medio",
        minLevel: 50,
        description: "Mais HTML: listas numeradas, tabelas, formulários, botões, links em nova aba, vídeos e a estrutura da página",
        rewardXp: 250,
        rewardCoins: 100,
        rewardItem: {
            name: "Pergaminho de Marcação",
            icon: "📄",
            description: "Um pergaminho cheio de tags bem fechadas. Usar transforma cada tag em XP.",
            rarity: "raro",
            value: 35,
            xp: 70,
        },
        kind: "quiz",
        questions: [
            {
                id: "q1",
                prompt: "Qual tag cria uma lista numerada (1, 2, 3...)?",
                options: [
                    { id: "a", text: "<ol>" },
                    { id: "b", text: "<ul>" },
                    { id: "c", text: "<li>" },
                    { id: "d", text: "<num>" },
                ],
                correctOptionId: "a",
                explanation: "O <ol> (ordered list, lista ordenada) numera os itens sozinho. Cada item continua sendo um <li>. É ótimo para passo a passo, como uma receita.",
            },
            {
                id: "q2",
                prompt: "Em uma tabela HTML, qual tag representa uma célula com dado?",
                code: "<table>\n  <tr>\n    <??>Ana</??>\n    <??>12</??>\n  </tr>\n</table>",
                options: [
                    { id: "a", text: "<li>" },
                    { id: "b", text: "<td>" },
                    { id: "c", text: "<p>" },
                    { id: "d", text: "<cell>" },
                ],
                correctOptionId: "b",
                explanation: "Na tabela, <tr> é uma linha (table row) e <td> é uma célula (table data). Para as células do cabeçalho, em negrito, usamos <th>.",
            },
            {
                id: "q3",
                prompt: "Qual campo esconde o que a pessoa digita, mostrando bolinhas no lugar?",
                options: [
                    { id: "a", text: "<input type=\"text\">" },
                    { id: "b", text: "<input type=\"number\">" },
                    { id: "c", text: "<input type=\"password\">" },
                    { id: "d", text: "<input type=\"email\">" },
                ],
                correctOptionId: "c",
                explanation: "O <input> muda de comportamento conforme o type: password esconde o texto, number só aceita números, email confere se tem @. Todos ficam dentro de um <form>.",
            },
            {
                id: "q4",
                prompt: "Qual tag cria um botão clicável?",
                options: [
                    { id: "a", text: "<click>" },
                    { id: "b", text: "<a>" },
                    { id: "c", text: "<input type=\"text\">" },
                    { id: "d", text: "<button>" },
                ],
                correctOptionId: "d",
                explanation: "O <button> cria um botão, como <button>Enviar</button>. Sozinho ele não faz nada: é o JavaScript (ou o formulário) que define o que acontece no clique.",
            },
            {
                id: "q5",
                prompt: "O que o atributo target=\"_blank\" faz em um link?",
                code: "<a href=\"https://scratch.mit.edu\" target=\"_blank\">Scratch</a>",
                options: [
                    { id: "a", text: "Deixa o link em branco" },
                    { id: "b", text: "Abre o link numa nova aba" },
                    { id: "c", text: "Desativa o link" },
                    { id: "d", text: "Esconde o link" },
                ],
                correctOptionId: "b",
                explanation: "Com target=\"_blank\", o link abre numa nova aba e a página atual continua aberta. É útil para links que levam pra outros sites.",
            },
            {
                id: "q6",
                prompt: "Como escrevemos um comentário no HTML?",
                options: [
                    { id: "a", text: "<!-- comentário -->" },
                    { id: "b", text: "// comentário" },
                    { id: "c", text: "/* comentário */" },
                    { id: "d", text: "# comentário" },
                ],
                correctOptionId: "a",
                explanation: "No HTML, os comentários ficam entre <!-- e -->. O navegador não mostra o que está ali dentro, então serve pra deixar anotações no código.",
            },
            {
                id: "q7",
                prompt: "Para que serve a tag <div>?",
                options: [
                    { id: "a", text: "Para dividir números" },
                    { id: "b", text: "Para criar um link" },
                    { id: "c", text: "Para agrupar elementos numa caixa, que depois recebe estilo com CSS" },
                    { id: "d", text: "Para tocar música" },
                ],
                correctOptionId: "c",
                explanation: "A <div> é uma caixa genérica: ela agrupa outros elementos para organizar a página. Sozinha não muda nada na aparência; é o CSS que dá cor, tamanho e posição a ela.",
            },
            {
                id: "q8",
                prompt: "Qual código coloca um vídeo na página com os botões de play e pausa?",
                options: [
                    { id: "a", text: "<img src=\"aula.mp4\">" },
                    { id: "b", text: "<video src=\"aula.mp4\" controls></video>" },
                    { id: "c", text: "<a href=\"aula.mp4\" controls>" },
                    { id: "d", text: "<play>aula.mp4</play>" },
                ],
                correctOptionId: "b",
                explanation: "A tag <video> mostra vídeos, e o atributo controls coloca os botões de play, pausa e volume. Para som, existe a tag <audio>, que funciona do mesmo jeito.",
            },
            {
                id: "q9",
                prompt: "Para que serve o <!DOCTYPE html> na primeira linha do arquivo?",
                options: [
                    { id: "a", text: "Para dar um título à página" },
                    { id: "b", text: "Para avisar ao navegador que a página usa o HTML moderno (HTML5)" },
                    { id: "c", text: "Para importar o CSS" },
                    { id: "d", text: "Para criar um comentário" },
                ],
                correctOptionId: "b",
                explanation: "O <!DOCTYPE html> não aparece na tela: ele diz ao navegador que o documento é HTML5. Sem ele, o navegador pode mostrar a página de um jeito antigo e cheio de diferenças.",
            },
            {
                id: "q10",
                prompt: "Qual é a regra para o atributo id de um elemento?",
                options: [
                    { id: "a", text: "Todos os elementos devem ter o mesmo id" },
                    { id: "b", text: "O id deve ser único: dois elementos da mesma página não podem ter o mesmo id" },
                    { id: "c", text: "O id só pode ter números" },
                    { id: "d", text: "O id serve para mudar a cor" },
                ],
                correctOptionId: "b",
                explanation: "O id identifica um elemento único, por exemplo <section id=\"contato\">. O CSS o seleciona com # e o JavaScript com getElementById. Para estilos que se repetem, usamos class.",
            },
        ],
    },
    {
        title: "Linguagem Lua parte 3",
        icon: "🌕",
        difficulty: "avancado",
        minLevel: 50,
        description: "Lua avançando: comentários longos, sorteios, arredondamento, conversões, pairs, textos e funções que devolvem vários valores",
        rewardXp: 320,
        rewardCoins: 130,
        rewardItem: {
            name: "Lua Cheia",
            icon: "🌕",
            description: "A Lua completa, depois de todas as fases. Usar transforma o luar em XP.",
            rarity: "epico",
            value: 50,
            xp: 90,
        },
        kind: "quiz",
        questions: [
            {
                id: "q1",
                prompt: "Como escrevemos um comentário de várias linhas em Lua?",
                options: [
                    { id: "a", text: "/* comentário */" },
                    { id: "b", text: "--[[ comentário ]]" },
                    { id: "c", text: "<!-- comentário -->" },
                    { id: "d", text: "## comentário ##" },
                ],
                correctOptionId: "b",
                explanation: "O -- faz um comentário de uma linha. Para várias linhas, usamos --[[ no começo e ]] no fim. Dá até pra \"desligar\" um trecho de código enquanto testa.",
            },
            {
                id: "q2",
                prompt: "Qual código sorteia um número de 1 a 6, como um dado, em Lua?",
                options: [
                    { id: "a", text: "math.random(1, 6)" },
                    { id: "b", text: "random.randint(1, 6)" },
                    { id: "c", text: "Math.random() * 6" },
                    { id: "d", text: "dado(6)" },
                ],
                correctOptionId: "a",
                explanation: "Em Lua, o math.random(1, 6) sorteia um inteiro de 1 a 6, incluindo os dois. No Roblox, além dele, também existe o Random.new() para sorteios.",
            },
            {
                id: "q3",
                prompt: "O que este código mostra?",
                code: "print(math.floor(3.7))",
                options: [
                    { id: "a", text: "4" },
                    { id: "b", text: "3.7" },
                    { id: "c", text: "3" },
                    { id: "d", text: "0.7" },
                ],
                correctOptionId: "c",
                explanation: "O math.floor arredonda para baixo, tirando a parte decimal: 3.7 vira 3. Já o math.ceil arredonda para cima: 3.2 viraria 4.",
            },
            {
                id: "q4",
                prompt: "O que este código mostra?",
                code: "print(tonumber(\"abc\"))",
                options: [
                    { id: "a", text: "0" },
                    { id: "b", text: "abc" },
                    { id: "c", text: "nil" },
                    { id: "d", text: "Um erro que fecha o programa" },
                ],
                correctOptionId: "c",
                explanation: "O tonumber transforma texto em número: tonumber(\"42\") dá 42. Quando o texto não é um número, ele devolve nil, sem quebrar o programa. Assim dá pra conferir se a pessoa digitou certo.",
            },
            {
                id: "q5",
                prompt: "Qual função percorre TODAS as chaves de uma tabela com nomes, como esta?",
                code: "local jogador = {nome = \"Ana\", vidas = 3, nivel = 7}",
                options: [
                    { id: "a", text: "ipairs(jogador)" },
                    { id: "b", text: "pairs(jogador)" },
                    { id: "c", text: "range(jogador)" },
                    { id: "d", text: "#jogador" },
                ],
                correctOptionId: "b",
                explanation: "O ipairs percorre listas numeradas (1, 2, 3...). Para tabelas com nomes como chave, usamos pairs: for chave, valor in pairs(jogador) do print(chave, valor) end. A ordem das chaves no pairs não é garantida.",
            },
            {
                id: "q6",
                prompt: "O que este código mostra?",
                code: "local fila = {\"Ana\", \"Bia\", \"Caio\"}\ntable.remove(fila, 1)\nprint(fila[1])",
                options: [
                    { id: "a", text: "Ana" },
                    { id: "b", text: "Bia" },
                    { id: "c", text: "Caio" },
                    { id: "d", text: "nil" },
                ],
                correctOptionId: "b",
                explanation: "O table.remove(fila, 1) tira o primeiro item e os outros andam uma posição pra frente. Agora fila[1] é \"Bia\". É exatamente como uma fila andando.",
            },
            {
                id: "q7",
                prompt: "O que este código mostra?",
                code: "print(string.upper(\"vitória\"))",
                options: [
                    { id: "a", text: "vitória" },
                    { id: "b", text: "Vitória" },
                    { id: "c", text: "VITóRIA" },
                    { id: "d", text: "VITÓRIA" },
                ],
                correctOptionId: "c",
                explanation: "O string.upper deixa as letras maiúsculas, mas, por padrão, a Lua só conhece as letras sem acento: o \"ó\" continua minúsculo. Por isso é comum evitar acentos em nomes de variáveis e chaves.",
            },
            {
                id: "q8",
                prompt: "O que este código mostra?",
                code: "local function dividir(a, b)\n  return a // b, a % b\nend\n\nlocal quociente, resto = dividir(7, 2)\nprint(quociente, resto)",
                options: [
                    { id: "a", text: "3 1" },
                    { id: "b", text: "3.5" },
                    { id: "c", text: "1 3" },
                    { id: "d", text: "Um erro" },
                ],
                correctOptionId: "a",
                explanation: "Em Lua, uma função pode devolver vários valores de uma vez, separados por vírgula. O // é a divisão inteira (7 // 2 = 3) e o % é o resto (1). Os dois valores caem nas duas variáveis.",
            },
            {
                id: "q9",
                prompt: "Quais números este código mostra?",
                code: "for i = 1, 10 do\n  if i > 3 then\n    break\n  end\n  print(i)\nend",
                options: [
                    { id: "a", text: "1 até 10" },
                    { id: "b", text: "4 até 10" },
                    { id: "c", text: "Só o 3" },
                    { id: "d", text: "1, 2 e 3" },
                ],
                correctOptionId: "d",
                explanation: "O break sai do laço na hora. Quando i passa de 3, o laço termina, então só aparecem 1, 2 e 3.",
            },
            {
                id: "q10",
                prompt: "O que este código mostra?",
                code: "print(string.sub(\"Roblox\", 1, 3))",
                options: [
                    { id: "a", text: "Rob" },
                    { id: "b", text: "obl" },
                    { id: "c", text: "Roblox" },
                    { id: "d", text: "R" },
                ],
                correctOptionId: "a",
                explanation: "O string.sub recorta um pedaço do texto, da posição inicial até a final, incluindo as duas. Como na Lua as posições começam em 1, as letras 1 a 3 formam \"Rob\".",
            },
        ],
    },
    {
        title: "Java parte 3",
        icon: "🏗️",
        difficulty: "avancado",
        minLevel: 50,
        description: "Java avançando: Scanner, char, ++, resto da divisão, textos, ArrayList, erros, construtores, final e while",
        rewardXp: 320,
        rewardCoins: 130,
        rewardItem: {
            name: "Viga de Objetos",
            icon: "🏗️",
            description: "A viga que sustenta qualquer programa orientado a objetos. Usar constrói XP.",
            rarity: "epico",
            value: 50,
            xp: 90,
        },
        kind: "quiz",
        questions: [
            {
                id: "q1",
                prompt: "Qual classe do Java é usada para ler o que a pessoa digita no teclado?",
                code: "import java.util.Scanner;\n\nScanner teclado = new Scanner(System.in);\nString nome = teclado.nextLine();",
                options: [
                    { id: "a", text: "System.out" },
                    { id: "b", text: "Math" },
                    { id: "c", text: "Scanner" },
                    { id: "d", text: "String" },
                ],
                correctOptionId: "c",
                explanation: "O Scanner, da biblioteca java.util, lê a entrada do teclado (System.in). O nextLine() lê uma linha de texto e o nextInt() lê um número inteiro. É o \"input\" do Java.",
            },
            {
                id: "q2",
                prompt: "Em Java, qual é a diferença entre 'A' e \"A\"?",
                options: [
                    { id: "a", text: "Não há diferença" },
                    { id: "b", text: "'A' é um char (um único caractere) e \"A\" é uma String (um texto)" },
                    { id: "c", text: "'A' é um número" },
                    { id: "d", text: "\"A\" dá erro" },
                ],
                correctOptionId: "b",
                explanation: "Em Java, aspas simples criam um char, que guarda exatamente um caractere (char letra = 'A';). Aspas duplas criam uma String, que guarda um texto de qualquer tamanho.",
            },
            {
                id: "q3",
                prompt: "O que este código mostra?",
                code: "int pontos = 5;\npontos++;\nSystem.out.println(pontos);",
                options: [
                    { id: "a", text: "5" },
                    { id: "b", text: "6" },
                    { id: "c", text: "10" },
                    { id: "d", text: "5++" },
                ],
                correctOptionId: "b",
                explanation: "O ++ soma 1 à variável: pontos++ é o mesmo que pontos = pontos + 1. Também existe o --, que tira 1. Eles aparecem muito nos laços for.",
            },
            {
                id: "q4",
                prompt: "Qual condição em Java descobre se o número n é ímpar?",
                options: [
                    { id: "a", text: "n % 2 == 1" },
                    { id: "b", text: "n / 2 == 1" },
                    { id: "c", text: "n * 2 == 1" },
                    { id: "d", text: "n == odd" },
                ],
                correctOptionId: "a",
                explanation: "O % dá o resto da divisão. Número ímpar dividido por 2 sempre sobra 1. (Cuidado com números negativos: em Java, -3 % 2 dá -1. Por isso muita gente prefere testar n % 2 != 0.)",
            },
            {
                id: "q5",
                prompt: "O que este código mostra?",
                code: "String nome = \"CodeGuilds\";\nSystem.out.println(nome.length());",
                options: [
                    { id: "a", text: "9" },
                    { id: "b", text: "11" },
                    { id: "c", text: "10" },
                    { id: "d", text: "CodeGuilds" },
                ],
                correctOptionId: "c",
                explanation: "O método length() da String conta os caracteres: C-o-d-e-G-u-i-l-d-s são 10. Repare nos parênteses: em String é length(), mas em array é length, sem parênteses.",
            },
            {
                id: "q6",
                prompt: "O que este código mostra?",
                code: "ArrayList<String> mochila = new ArrayList<>();\nmochila.add(\"espada\");\nmochila.add(\"mapa\");\nSystem.out.println(mochila.size());",
                options: [
                    { id: "a", text: "0" },
                    { id: "b", text: "1" },
                    { id: "c", text: "espada" },
                    { id: "d", text: "2" },
                ],
                correctOptionId: "d",
                explanation: "O ArrayList é uma lista que cresce: o add() coloca itens e o size() diz quantos tem. Diferente do array comum (int[]), que tem tamanho fixo, o ArrayList aumenta conforme precisa.",
            },
            {
                id: "q7",
                prompt: "Por que este código dá erro quando roda?",
                code: "int[] notas = {7, 8, 10};\nSystem.out.println(notas[3]);",
                options: [
                    { id: "a", text: "Porque falta ponto e vírgula" },
                    { id: "b", text: "Porque a posição 3 não existe: as posições vão de 0 a 2" },
                    { id: "c", text: "Porque 10 é um número muito grande" },
                    { id: "d", text: "Não dá erro, mostra 10" },
                ],
                correctOptionId: "b",
                explanation: "O array tem 3 itens nas posições 0, 1 e 2. Pedir a posição 3 gera o erro ArrayIndexOutOfBoundsException (\"índice fora dos limites\"), um dos erros mais comuns em Java.",
            },
            {
                id: "q8",
                prompt: "Nesta classe, para que serve o trecho public Personagem(String nome)?",
                code: "public class Personagem {\n    String nome;\n\n    public Personagem(String nome) {\n        this.nome = nome;\n    }\n}",
                options: [
                    { id: "a", text: "É o construtor: roda quando um objeto é criado com new e define os valores iniciais" },
                    { id: "b", text: "É um comentário" },
                    { id: "c", text: "Apaga o personagem" },
                    { id: "d", text: "É o método main" },
                ],
                correctOptionId: "a",
                explanation: "O construtor tem o mesmo nome da classe e roda no new Personagem(\"Ana\"). O this.nome é o nome do objeto, que recebe o valor passado. Assim cada personagem já nasce com seu nome.",
            },
            {
                id: "q9",
                prompt: "O que a palavra final faz nesta linha?",
                code: "final int VIDAS_MAXIMAS = 5;",
                options: [
                    { id: "a", text: "Termina o programa" },
                    { id: "b", text: "Faz a variável virar uma constante: o valor não pode ser trocado depois" },
                    { id: "c", text: "Coloca a variável no fim da lista" },
                    { id: "d", text: "Deixa a variável invisível" },
                ],
                correctOptionId: "b",
                explanation: "Com final, a variável vira constante: tentar mudar VIDAS_MAXIMAS depois dá erro. É costume escrever as constantes em MAIÚSCULAS, com _ separando as palavras.",
            },
            {
                id: "q10",
                prompt: "O que este código mostra?",
                code: "int n = 1;\nwhile (n < 20) {\n    n = n * 2;\n}\nSystem.out.println(n);",
                options: [
                    { id: "a", text: "16" },
                    { id: "b", text: "20" },
                    { id: "c", text: "2" },
                    { id: "d", text: "32" },
                ],
                correctOptionId: "d",
                explanation: "O n dobra a cada volta: 1, 2, 4, 8, 16, 32. Quando chega a 32, a condição n < 20 fica falsa e o laço para. O while só confere a condição no começo de cada volta.",
            },
        ],
    },
]

export default missions
