import { MissionContent } from "../../../src/engine/missions";

// Quarta leva de missões de quiz para as turmas de programação de 12 anos,
// só de linguagens: JavaScript parte 2, Java, Java parte 2, Python,
// Python parte 2 e Linguagem Lua parte 2. 10 perguntas cada, todas
// comentadas, sem repetir as das levas anteriores. Importar com:
//   npm run missions:import -- <e-mail do professor> scripts/missions/programacao-12-anos-parte-4.ts
const missions: MissionContent[] = [
    {
        title: "JavaScript parte 2",
        icon: "✨",
        difficulty: "medio",
        minLevel: 1,
        description: "JavaScript na página: alertas, cliques, elementos, listas, objetos, sorteios e muito mais",
        rewardXp: 180,
        rewardCoins: 80,
        rewardItem: {
            name: "Faísca do DOM",
            icon: "✨",
            description: "A faísca que faz uma página mudar quando alguém clica. Usar acende o seu XP.",
            rarity: "raro",
            value: 30,
            xp: 60,
        },
        kind: "quiz",
        questions: [
            {
                id: "q1",
                prompt: "O que acontece quando a página roda este código?",
                code: "alert(\"Bem-vindo à CodeGuilds!\");",
                options: [
                    { id: "a", text: "A mensagem aparece numa janelinha de aviso, com um botão OK" },
                    { id: "b", text: "A mensagem vai para o console" },
                    { id: "c", text: "A página fecha" },
                    { id: "d", text: "Nada acontece" },
                ],
                correctOptionId: "a",
                explanation: "O alert() abre uma caixa de aviso do navegador com a mensagem, e a página espera você clicar em OK. É útil para testes, mas em sites de verdade costuma incomodar, então use com moderação.",
            },
            {
                id: "q2",
                prompt: "No HTML existe <h1 id=\"titulo\">Olá</h1>. Qual código do JavaScript encontra esse elemento?",
                options: [
                    { id: "a", text: "console.log(\"titulo\")" },
                    { id: "b", text: "document.getElementById(\"titulo\")" },
                    { id: "c", text: "alert(\"titulo\")" },
                    { id: "d", text: "let titulo = h1" },
                ],
                correctOptionId: "b",
                explanation: "O document representa a página, e o getElementById() busca o elemento pelo id. Depois dá para mudar o texto, a cor e muito mais. Essa \"árvore\" de elementos que o JavaScript enxerga se chama DOM.",
            },
            {
                id: "q3",
                prompt: "O que este código faz?",
                code: "let titulo = document.getElementById(\"titulo\");\ntitulo.textContent = \"Missão cumprida!\";",
                options: [
                    { id: "a", text: "Apaga o título" },
                    { id: "b", text: "Mostra um alerta" },
                    { id: "c", text: "Troca o texto do elemento com id \"titulo\" para \"Missão cumprida!\"" },
                    { id: "d", text: "Muda a cor do título" },
                ],
                correctOptionId: "c",
                explanation: "O textContent é o texto de dentro do elemento. Quando você troca esse valor, a página muda na hora, sem recarregar. É assim que placares e mensagens são atualizados nos sites.",
            },
            {
                id: "q4",
                prompt: "Qual código faz algo acontecer quando o usuário clica num botão?",
                options: [
                    { id: "a", text: "botao.textContent = \"click\"" },
                    { id: "b", text: "console.log(\"click\")" },
                    { id: "c", text: "let click = botao" },
                    { id: "d", text: "botao.addEventListener(\"click\", function () { ... })" },
                ],
                correctOptionId: "d",
                explanation: "O addEventListener() fica \"escutando\" um evento, como o clique (\"click\"), e roda a função quando ele acontece. É a mesma ideia do \"quando este ator for clicado\" do Scratch e do \"quando Botão1.Clique\" do App Inventor.",
            },
            {
                id: "q5",
                prompt: "O que este código mostra no console?",
                code: "let itens = [\"espada\", \"escudo\", \"poção\"];\nitens.push(\"mapa\");\nconsole.log(itens.length);",
                options: [
                    { id: "a", text: "3" },
                    { id: "b", text: "4" },
                    { id: "c", text: "mapa" },
                    { id: "d", text: "0" },
                ],
                correctOptionId: "b",
                explanation: "O push() coloca um item no fim do array, que passa a ter 4 itens. O length diz quantos itens o array tem. Os dois juntos são perfeitos para um inventário de jogo!",
            },
            {
                id: "q6",
                prompt: "Com as crases, o que este código mostra?",
                code: "let nome = \"Ana\";\nlet nivel = 5;\nconsole.log(`${nome} está no nível ${nivel}`);",
                options: [
                    { id: "a", text: "${nome} está no nível ${nivel}" },
                    { id: "b", text: "nome está no nível nivel" },
                    { id: "c", text: "Ana está no nível 5" },
                    { id: "d", text: "Um erro" },
                ],
                correctOptionId: "c",
                explanation: "Textos entre crases (`) são template strings: tudo que fica dentro de ${ } é trocado pelo valor. É um jeito mais fácil de montar frases do que juntar vários pedaços com +.",
            },
            {
                id: "q7",
                prompt: "Qual é o resultado de true && false no JavaScript?",
                options: [
                    { id: "a", text: "true" },
                    { id: "b", text: "\"truefalse\"" },
                    { id: "c", text: "Um erro" },
                    { id: "d", text: "false" },
                ],
                correctOptionId: "d",
                explanation: "O && (\"e\") só dá true se os dois lados forem verdadeiros. O || (\"ou\") dá true se pelo menos um for. Exemplo num jogo: se (temChave && portaFechada) então abrir a porta.",
            },
            {
                id: "q8",
                prompt: "Qual código sorteia um número inteiro de 1 a 6, como um dado?",
                options: [
                    { id: "a", text: "Math.floor(Math.random() * 6) + 1" },
                    { id: "b", text: "Math.random(6)" },
                    { id: "c", text: "random(1, 6)" },
                    { id: "d", text: "6 + 1" },
                ],
                correctOptionId: "a",
                explanation: "O Math.random() sorteia um número entre 0 e 1 (nunca chega a 1). Vezes 6, fica entre 0 e quase 6. O Math.floor() corta as casas decimais (0 a 5) e o + 1 leva para 1 a 6.",
            },
            {
                id: "q9",
                prompt: "Qual valor aparece no console?",
                code: "let heroi = { nome: \"Luna\", vidas: 3, nivel: 7 };\nconsole.log(heroi.vidas);",
                options: [
                    { id: "a", text: "Luna" },
                    { id: "b", text: "7" },
                    { id: "c", text: "3" },
                    { id: "d", text: "vidas" },
                ],
                correctOptionId: "c",
                explanation: "Entre chaves fica um objeto: um conjunto de informações com nome (propriedades). Com o ponto, pegamos a propriedade que queremos: heroi.vidas é 3 e heroi.nome é \"Luna\".",
            },
            {
                id: "q10",
                prompt: "Quantas vezes \"Pulo!\" aparece no console?",
                code: "let pulos = 0;\nwhile (pulos < 3) {\n  console.log(\"Pulo!\");\n  pulos++;\n}",
                options: [
                    { id: "a", text: "Nenhuma" },
                    { id: "b", text: "3 vezes" },
                    { id: "c", text: "4 vezes" },
                    { id: "d", text: "Infinitas vezes" },
                ],
                correctOptionId: "b",
                explanation: "O while repete enquanto a condição for verdadeira. pulos começa em 0 e aumenta 1 a cada volta: 0, 1 e 2 rodam, e quando chega a 3 a condição fica falsa. Sem o pulos++, o laço nunca terminaria!",
            },
        ],
    },
    {
        title: "Java",
        icon: "☕",
        difficulty: "iniciante",
        minLevel: 1,
        description: "Os primeiros passos em Java: a origem da linguagem, a JVM, o main, os tipos e as regras de escrita",
        rewardXp: 150,
        rewardCoins: 60,
        rewardItem: {
            name: "Xícara de Café Java",
            icon: "☕",
            description: "O café que inspirou o nome e o símbolo da linguagem. Usar dá a energia de um programador em forma de XP.",
            rarity: "comum",
            value: 15,
            xp: 40,
        },
        kind: "quiz",
        questions: [
            {
                id: "q1",
                prompt: "Qual empresa criou a linguagem Java, lançada em 1995?",
                options: [
                    { id: "a", text: "A Sun Microsystems (hoje a Java pertence à Oracle)" },
                    { id: "b", text: "A Nintendo" },
                    { id: "c", text: "O MIT" },
                    { id: "d", text: "A PUC-Rio" },
                ],
                correctOptionId: "a",
                explanation: "O Java foi criado por uma equipe liderada por James Gosling na Sun Microsystems. Em 2010, a Oracle comprou a Sun e hoje cuida da linguagem. O símbolo do Java é uma xícara de café!",
            },
            {
                id: "q2",
                prompt: "O lema do Java é \"escreva uma vez, rode em qualquer lugar\". O que permite isso?",
                options: [
                    { id: "a", text: "O Java só funciona no Windows" },
                    { id: "b", text: "A JVM (Máquina Virtual Java), que roda o mesmo programa em sistemas diferentes" },
                    { id: "c", text: "A internet" },
                    { id: "d", text: "O mouse" },
                ],
                correctOptionId: "b",
                explanation: "O código Java é transformado num formato intermediário (bytecode), que a JVM entende. Como existe JVM para Windows, Linux, macOS e outros, o mesmo programa roda em todos eles sem precisar ser reescrito.",
            },
            {
                id: "q3",
                prompt: "Qual famoso jogo foi criado originalmente em Java?",
                options: [
                    { id: "a", text: "Super Mario Bros." },
                    { id: "b", text: "Pac-Man" },
                    { id: "c", text: "Minecraft (a Java Edition)" },
                    { id: "d", text: "Tetris" },
                ],
                correctOptionId: "c",
                explanation: "O Minecraft foi escrito em Java, e a versão de computador ainda se chama Minecraft: Java Edition. Os mods do Minecraft Java também são feitos em Java, um ótimo motivo para aprender a linguagem!",
            },
            {
                id: "q4",
                prompt: "Qual comando mostra \"Olá, Java!\" na tela?",
                options: [
                    { id: "a", text: "print(\"Olá, Java!\")" },
                    { id: "b", text: "console.log(\"Olá, Java!\")" },
                    { id: "c", text: "echo \"Olá, Java!\"" },
                    { id: "d", text: "System.out.println(\"Olá, Java!\");" },
                ],
                correctOptionId: "d",
                explanation: "Em Java, escrevemos System.out.println() para mostrar uma linha de texto. É mais comprido que o print do Python ou da Lua, mas a ideia é a mesma. O \"ln\" do final significa que pula para a próxima linha.",
            },
            {
                id: "q5",
                prompt: "Todo programa Java começa a rodar por um método especial. Qual é?",
                code: "public class Jogo {\n    public static void ???(String[] args) {\n        System.out.println(\"Começou!\");\n    }\n}",
                options: [
                    { id: "a", text: "main" },
                    { id: "b", text: "start" },
                    { id: "c", text: "begin" },
                    { id: "d", text: "play" },
                ],
                correctOptionId: "a",
                explanation: "O método main é o ponto de partida: quando o programa é executado, o Java procura por ele e roda o que está dentro. Repare também que todo código Java fica dentro de uma classe (class).",
            },
            {
                id: "q6",
                prompt: "O que falta no fim das instruções em Java?",
                code: "int vidas = 3\nSystem.out.println(vidas)",
                options: [
                    { id: "a", text: "Dois pontos (:)" },
                    { id: "b", text: "Um ponto final (.)" },
                    { id: "c", text: "Ponto e vírgula (;)" },
                    { id: "d", text: "Nada, está correto" },
                ],
                correctOptionId: "c",
                explanation: "Em Java, cada instrução termina com ponto e vírgula. O certo é int vidas = 3; e System.out.println(vidas);. Esquecer o ; é o erro mais comum de quem está começando, e o programa nem chega a rodar.",
            },
            {
                id: "q7",
                prompt: "Em Java, qual tipo de variável guarda um número inteiro, como a quantidade de vidas?",
                options: [
                    { id: "a", text: "String" },
                    { id: "b", text: "int" },
                    { id: "c", text: "boolean" },
                    { id: "d", text: "texto" },
                ],
                correctOptionId: "b",
                explanation: "Em Java, toda variável tem um tipo declarado: int para inteiros (int vidas = 3;), String para textos (String nome = \"Ana\";) e boolean para verdadeiro ou falso. Se você tentar guardar um texto num int, dá erro.",
            },
            {
                id: "q8",
                prompt: "Java e JavaScript são a mesma linguagem?",
                options: [
                    { id: "a", text: "Sim, são a mesma coisa" },
                    { id: "b", text: "Sim, JavaScript é só o Java para celular" },
                    { id: "c", text: "Não, são linguagens diferentes, criadas por empresas diferentes, apesar do nome parecido" },
                    { id: "d", text: "Não, porque o Java não é uma linguagem de programação" },
                ],
                correctOptionId: "c",
                explanation: "Apesar do nome, são linguagens bem diferentes. O JavaScript foi criado na Netscape, também em 1995, e ganhou esse nome em parte porque o Java estava famoso na época. Uma frase conhecida diz que Java está para JavaScript como carro está para carpete!",
            },
            {
                id: "q9",
                prompt: "Para o Java, nome e Nome são a mesma variável?",
                options: [
                    { id: "a", text: "Sim, o Java não liga para maiúsculas" },
                    { id: "b", text: "Sim, mas só dentro do main" },
                    { id: "c", text: "Não dá para usar letras maiúsculas em Java" },
                    { id: "d", text: "Não: o Java diferencia letras maiúsculas e minúsculas" },
                ],
                correctOptionId: "d",
                explanation: "O Java é \"case-sensitive\": nome, Nome e NOME são três coisas diferentes. Por isso escrever System com s minúsculo dá erro. Em Java, o costume é nomear variáveis em camelCase, como pontosDoJogador.",
            },
            {
                id: "q10",
                prompt: "Com que extensão são salvos os arquivos de código Java?",
                options: [
                    { id: "a", text: ".js" },
                    { id: "b", text: ".java" },
                    { id: "c", text: ".py" },
                    { id: "d", text: ".lua" },
                ],
                correctOptionId: "b",
                explanation: "O código Java fica em arquivos .java, e o nome do arquivo deve ser igual ao da classe pública (a classe Jogo fica em Jogo.java). O .js é JavaScript, o .py é Python e o .lua é Lua.",
            },
        ],
    },
    {
        title: "Java parte 2",
        icon: "📐",
        difficulty: "medio",
        minLevel: 1,
        description: "Condições, laços, divisões, textos, arrays, métodos e classes em Java",
        rewardXp: 180,
        rewardCoins: 80,
        rewardItem: {
            name: "Molde de Classe",
            icon: "📐",
            description: "O molde que cria objetos em Java. Usar fabrica XP a partir dele.",
            rarity: "raro",
            value: 30,
            xp: 60,
        },
        kind: "quiz",
        questions: [
            {
                id: "q1",
                prompt: "O que este código mostra?",
                code: "int pontos = 80;\n\nif (pontos >= 100) {\n    System.out.println(\"Ouro\");\n} else if (pontos >= 50) {\n    System.out.println(\"Prata\");\n} else {\n    System.out.println(\"Bronze\");\n}",
                options: [
                    { id: "a", text: "Ouro" },
                    { id: "b", text: "Prata" },
                    { id: "c", text: "Bronze" },
                    { id: "d", text: "Prata e Bronze" },
                ],
                correctOptionId: "b",
                explanation: "80 não é maior ou igual a 100, então o primeiro if é falso. Mas 80 é maior ou igual a 50, então aparece \"Prata\". Num if / else if / else, só um dos caminhos é executado: o primeiro que for verdadeiro.",
            },
            {
                id: "q2",
                prompt: "Quais números este laço mostra?",
                code: "for (int i = 0; i < 3; i++) {\n    System.out.println(i);\n}",
                options: [
                    { id: "a", text: "1, 2 e 3" },
                    { id: "b", text: "0, 1, 2 e 3" },
                    { id: "c", text: "0, 1 e 2" },
                    { id: "d", text: "Só o 3" },
                ],
                correctOptionId: "c",
                explanation: "O i começa em 0 e o laço repete enquanto i for menor que 3 (não igual). Então mostra 0, 1 e 2, ou seja, 3 repetições. Esse formato \"começa no 0 e vai até menor que N\" é muito usado em Java.",
            },
            {
                id: "q3",
                prompt: "Qual é o resultado desta divisão em Java?",
                code: "int resultado = 7 / 2;\nSystem.out.println(resultado);",
                options: [
                    { id: "a", text: "3" },
                    { id: "b", text: "3.5" },
                    { id: "c", text: "4" },
                    { id: "d", text: "Um erro" },
                ],
                correctOptionId: "a",
                explanation: "Quando dividimos dois int, o Java dá um resultado inteiro e descarta a parte decimal: 7 / 2 dá 3. Para ter 3.5, pelo menos um dos números precisa ser decimal, como 7.0 / 2, guardando num double.",
            },
            {
                id: "q4",
                prompt: "Qual tipo usar para guardar um número com casas decimais, como a altura 1.52?",
                options: [
                    { id: "a", text: "int" },
                    { id: "b", text: "boolean" },
                    { id: "c", text: "String" },
                    { id: "d", text: "double" },
                ],
                correctOptionId: "d",
                explanation: "O double guarda números com casas decimais: double altura = 1.52;. Repare que em Java (e na maioria das linguagens) a casa decimal é separada por ponto, não por vírgula.",
            },
            {
                id: "q5",
                prompt: "Uma variável boolean pode guardar quais valores?",
                options: [
                    { id: "a", text: "Qualquer número" },
                    { id: "b", text: "Só textos" },
                    { id: "c", text: "Apenas true (verdadeiro) ou false (falso)" },
                    { id: "d", text: "Sim, não e talvez" },
                ],
                correctOptionId: "c",
                explanation: "Um boolean guarda só true ou false, como boolean temChave = false;. Ele é perfeito para condições: if (temChave) { abrirPorta(); }.",
            },
            {
                id: "q6",
                prompt: "O que este código mostra?",
                code: "int nivel = 5;\nSystem.out.println(\"Nível \" + nivel);",
                options: [
                    { id: "a", text: "Nível 5" },
                    { id: "b", text: "Nível nivel" },
                    { id: "c", text: "Um erro" },
                    { id: "d", text: "10" },
                ],
                correctOptionId: "a",
                explanation: "Quando o + junta uma String com um número, o Java transforma o número em texto e cola os dois: \"Nível \" + 5 vira \"Nível 5\". O espaço depois de \"Nível\" está dentro das aspas, por isso aparece no resultado.",
            },
            {
                id: "q7",
                prompt: "O que este código mostra?",
                code: "int[] notas = {7, 8, 10};\nSystem.out.println(notas.length);",
                options: [
                    { id: "a", text: "10" },
                    { id: "b", text: "25" },
                    { id: "c", text: "2" },
                    { id: "d", text: "3" },
                ],
                correctOptionId: "d",
                explanation: "int[] é um array de inteiros, e o length diz quantos itens ele tem: 3. O primeiro item é notas[0] (7) e o último é notas[2] (10), porque em Java as posições começam do 0.",
            },
            {
                id: "q8",
                prompt: "O que este código mostra?",
                code: "static int dobro(int n) {\n    return n * 2;\n}\n\n// dentro do main:\nSystem.out.println(dobro(4));",
                options: [
                    { id: "a", text: "4" },
                    { id: "b", text: "8" },
                    { id: "c", text: "dobro" },
                    { id: "d", text: "42" },
                ],
                correctOptionId: "b",
                explanation: "Em Java, as funções se chamam métodos. Este recebe um int e devolve (return) o dobro dele: dobro(4) dá 8. O int antes do nome diz que o método devolve um número inteiro.",
            },
            {
                id: "q9",
                prompt: "Em Java, qual é a diferença entre uma classe e um objeto?",
                options: [
                    { id: "a", text: "A classe é o molde (como a planta de uma casa); o objeto é algo criado a partir dela (como cada casa construída)" },
                    { id: "b", text: "Não há diferença" },
                    { id: "c", text: "O objeto é o molde e a classe é criada a partir dele" },
                    { id: "d", text: "Classes só existem no Python" },
                ],
                correctOptionId: "a",
                explanation: "Uma classe Personagem define o que todo personagem tem (nome, vida) e faz (atacar). Cada objeto, criado com new Personagem(), é um personagem de verdade, com seus próprios valores. Isso é a Programação Orientada a Objetos, uma das bases do Java.",
            },
            {
                id: "q10",
                prompt: "Em Java, qual é o jeito certo de comparar se o texto da String senha é igual a \"dragão\"?",
                options: [
                    { id: "a", text: "senha = \"dragão\"" },
                    { id: "b", text: "senha + \"dragão\"" },
                    { id: "c", text: "senha.equals(\"dragão\")" },
                    { id: "d", text: "senha => \"dragão\"" },
                ],
                correctOptionId: "c",
                explanation: "Para comparar o conteúdo de Strings em Java, usamos .equals(). O == compara se são o mesmo objeto na memória, e pode dar false mesmo com textos iguais. Já o = sozinho guarda um valor, não compara.",
            },
        ],
    },
    {
        title: "Python",
        icon: "🐍",
        difficulty: "iniciante",
        minLevel: 1,
        description: "A linguagem mais fácil de ler: print, variáveis, indentação, condições, laços e listas",
        rewardXp: 150,
        rewardCoins: 60,
        rewardItem: {
            name: "Escama de Píton",
            icon: "🐍",
            description: "Uma escama brilhante deixada pela cobra símbolo do Python. Usar transforma o brilho em XP.",
            rarity: "comum",
            value: 15,
            xp: 40,
        },
        kind: "quiz",
        questions: [
            {
                id: "q1",
                prompt: "De onde vem o nome da linguagem Python?",
                options: [
                    { id: "a", text: "De uma cobra muito venenosa" },
                    { id: "b", text: "De um planeta" },
                    { id: "c", text: "Do grupo de comédia inglês Monty Python, de quem o criador da linguagem era fã" },
                    { id: "d", text: "Do nome do primeiro computador" },
                ],
                correctOptionId: "c",
                explanation: "O holandês Guido van Rossum criou o Python, lançado em 1991, e escolheu o nome por gostar do grupo de comédia Monty Python. A cobra virou símbolo depois. Hoje o Python é muito usado em inteligência artificial, ciência e automação.",
            },
            {
                id: "q2",
                prompt: "Qual comando mostra \"Olá, Python!\" na tela?",
                options: [
                    { id: "a", text: "print(\"Olá, Python!\")" },
                    { id: "b", text: "System.out.println(\"Olá, Python!\");" },
                    { id: "c", text: "console.log(\"Olá, Python!\")" },
                    { id: "d", text: "alert(\"Olá, Python!\")" },
                ],
                correctOptionId: "a",
                explanation: "No Python, basta print(). Sem ponto e vírgula no final e sem classe em volta: um programa Python pode ter uma linha só. Isso faz do Python uma ótima linguagem para começar.",
            },
            {
                id: "q3",
                prompt: "Como escrevemos um comentário no Python?",
                options: [
                    { id: "a", text: "-- comentário" },
                    { id: "b", text: "// comentário" },
                    { id: "c", text: "<!-- comentário -->" },
                    { id: "d", text: "# comentário" },
                ],
                correctOptionId: "d",
                explanation: "No Python, os comentários começam com # (cerquilha). Tudo depois dele, na mesma linha, é ignorado pelo computador. Comentários ajudam você e os colegas a entenderem o código.",
            },
            {
                id: "q4",
                prompt: "Qual linha cria corretamente uma variável no Python?",
                options: [
                    { id: "a", text: "let nome = \"Ana\"" },
                    { id: "b", text: "nome = \"Ana\"" },
                    { id: "c", text: "String nome = \"Ana\";" },
                    { id: "d", text: "local nome = \"Ana\"" },
                ],
                correctOptionId: "b",
                explanation: "No Python não precisa de palavra especial nem de tipo: é só escrever o nome, o sinal de igual e o valor. O Python descobre sozinho que \"Ana\" é um texto. O let é do JavaScript, o String é do Java e o local é da Lua.",
            },
            {
                id: "q5",
                prompt: "No Python, o que define quais linhas ficam dentro do if?",
                code: "if vidas == 0:\n    print(\"Fim de jogo\")\n    print(\"Tente de novo\")\nprint(\"Obrigado por jogar\")",
                options: [
                    { id: "a", text: "As chaves { }" },
                    { id: "b", text: "A palavra end" },
                    { id: "c", text: "A indentação: os espaços no começo das linhas" },
                    { id: "d", text: "O ponto e vírgula" },
                ],
                correctOptionId: "c",
                explanation: "O Python usa a indentação (o recuo com espaços) para saber o que está dentro do bloco. As duas linhas com recuo só rodam se vidas for 0. A última, sem recuo, roda sempre. Errar os espaços muda o programa ou dá erro!",
            },
            {
                id: "q6",
                prompt: "O que este código mostra?",
                code: "nota = 7\n\nif nota >= 9:\n    print(\"Excelente\")\nelif nota >= 6:\n    print(\"Aprovado\")\nelse:\n    print(\"Estude mais\")",
                options: [
                    { id: "a", text: "Excelente" },
                    { id: "b", text: "Aprovado" },
                    { id: "c", text: "Estude mais" },
                    { id: "d", text: "Aprovado e Estude mais" },
                ],
                correctOptionId: "b",
                explanation: "7 não é maior ou igual a 9, mas é maior ou igual a 6, então aparece \"Aprovado\". O elif é a forma curta de \"else if\" no Python. Repare nos dois pontos (:) no fim de cada condição.",
            },
            {
                id: "q7",
                prompt: "Quais números este laço mostra?",
                code: "for i in range(3):\n    print(i)",
                options: [
                    { id: "a", text: "1, 2 e 3" },
                    { id: "b", text: "0, 1 e 2" },
                    { id: "c", text: "0, 1, 2 e 3" },
                    { id: "d", text: "Só o 3" },
                ],
                correctOptionId: "b",
                explanation: "O range(3) gera os números 0, 1 e 2: começa no 0 e para antes do 3. Por isso o laço roda 3 vezes. Para ir de 1 a 3, use range(1, 4).",
            },
            {
                id: "q8",
                prompt: "O que este código mostra?",
                code: "print(2 ** 3)",
                options: [
                    { id: "a", text: "6" },
                    { id: "b", text: "5" },
                    { id: "c", text: "8" },
                    { id: "d", text: "23" },
                ],
                correctOptionId: "c",
                explanation: "No Python, ** é potência: 2 ** 3 é 2 × 2 × 2 = 8. Outros operadores úteis: // dá a divisão inteira (7 // 2 = 3) e % dá o resto da divisão (7 % 2 = 1).",
            },
            {
                id: "q9",
                prompt: "Qual valor aparece na tela?",
                code: "herois = [\"Mago\", \"Guerreiro\", \"Arqueira\"]\nprint(herois[1])",
                options: [
                    { id: "a", text: "Mago" },
                    { id: "b", text: "Arqueira" },
                    { id: "c", text: "1" },
                    { id: "d", text: "Guerreiro" },
                ],
                correctOptionId: "d",
                explanation: "Os colchetes criam uma lista. No Python, as posições começam do 0: herois[0] é \"Mago\", herois[1] é \"Guerreiro\" e herois[2] é \"Arqueira\". Lembre: na Lua a contagem começa do 1!",
            },
            {
                id: "q10",
                prompt: "Qual comando pede para o usuário digitar algo pelo teclado?",
                code: "nome = ???(\"Qual é o seu nome? \")\nprint(\"Olá,\", nome)",
                options: [
                    { id: "a", text: "input" },
                    { id: "b", text: "print" },
                    { id: "c", text: "read" },
                    { id: "d", text: "ask" },
                ],
                correctOptionId: "a",
                explanation: "O input() mostra a pergunta, espera a pessoa digitar e apertar Enter, e devolve o que foi digitado. É parecido com o bloco \"pergunte ... e espere\" do Scratch, e a resposta fica guardada na variável nome.",
            },
        ],
    },
    {
        title: "Python parte 2",
        icon: "🥚",
        difficulty: "medio",
        minLevel: 1,
        description: "Mais Python: conversões, while, funções, listas, textos, f-strings, dicionários e números aleatórios",
        rewardXp: 180,
        rewardCoins: 80,
        rewardItem: {
            name: "Ovo de Píton",
            icon: "🥚",
            description: "Um ovo que vai chocar um programador Python. Usar faz o seu XP nascer.",
            rarity: "raro",
            value: 30,
            xp: 60,
        },
        kind: "quiz",
        questions: [
            {
                id: "q1",
                prompt: "A pessoa digita 5 no input. Por que este código dá erro?",
                code: "idade = input(\"Sua idade: \")\nprint(idade + 1)",
                options: [
                    { id: "a", text: "Porque o input sempre devolve texto, e o Python não soma texto com número" },
                    { id: "b", text: "Porque falta ponto e vírgula" },
                    { id: "c", text: "Porque o nome idade é proibido" },
                    { id: "d", text: "Não dá erro, mostra 6" },
                ],
                correctOptionId: "a",
                explanation: "O input() devolve sempre um texto (\"5\"), mesmo que a pessoa digite um número. Para fazer contas, converta com int(): idade = int(input(\"Sua idade: \")). Aí idade + 1 dá 6.",
            },
            {
                id: "q2",
                prompt: "O que este código mostra?",
                code: "contagem = 3\nwhile contagem > 0:\n    print(contagem)\n    contagem = contagem - 1\nprint(\"Já!\")",
                options: [
                    { id: "a", text: "1, 2, 3 e Já!" },
                    { id: "b", text: "3, 2, 1 e Já!" },
                    { id: "c", text: "Só Já!" },
                    { id: "d", text: "3, 2, 1, 0 e Já!" },
                ],
                correctOptionId: "b",
                explanation: "O while repete enquanto contagem for maior que 0, diminuindo 1 a cada volta: mostra 3, 2 e 1. Quando contagem vira 0, o laço para e o \"Já!\" aparece. Uma contagem regressiva!",
            },
            {
                id: "q3",
                prompt: "O que este código mostra?",
                code: "def area_do_quadrado(lado):\n    return lado * lado\n\nprint(area_do_quadrado(4))",
                options: [
                    { id: "a", text: "8" },
                    { id: "b", text: "4" },
                    { id: "c", text: "16" },
                    { id: "d", text: "lado * lado" },
                ],
                correctOptionId: "c",
                explanation: "No Python, as funções são criadas com def. Esta recebe o lado e devolve (return) lado × lado. Com lado 4, a área é 16. Depois de criada, a função pode ser usada quantas vezes quiser.",
            },
            {
                id: "q4",
                prompt: "Qual comando coloca \"poção\" no fim da lista mochila?",
                code: "mochila = [\"espada\", \"mapa\"]",
                options: [
                    { id: "a", text: "mochila.push(\"poção\")" },
                    { id: "b", text: "mochila.append(\"poção\")" },
                    { id: "c", text: "mochila + poção" },
                    { id: "d", text: "add mochila \"poção\"" },
                ],
                correctOptionId: "b",
                explanation: "No Python, o append() adiciona um item no fim da lista. Depois dele, mochila fica [\"espada\", \"mapa\", \"poção\"]. No JavaScript, o mesmo trabalho é feito pelo push().",
            },
            {
                id: "q5",
                prompt: "O que este código mostra?",
                code: "print(len(\"Python\"))",
                options: [
                    { id: "a", text: "Python" },
                    { id: "b", text: "5" },
                    { id: "c", text: "1" },
                    { id: "d", text: "6" },
                ],
                correctOptionId: "d",
                explanation: "O len() conta o tamanho: num texto, conta as letras (P-y-t-h-o-n = 6); numa lista, conta os itens. É útil, por exemplo, para conferir se uma senha tem pelo menos 8 caracteres.",
            },
            {
                id: "q6",
                prompt: "O que este código mostra?",
                code: "grito = \"vitória\"\nprint(grito.upper())",
                options: [
                    { id: "a", text: "VITÓRIA" },
                    { id: "b", text: "vitória" },
                    { id: "c", text: "Vitória" },
                    { id: "d", text: "airótiv" },
                ],
                correctOptionId: "a",
                explanation: "O .upper() devolve o texto em letras maiúsculas, e o .lower() em minúsculas. É muito usado para comparar respostas sem se preocupar se a pessoa digitou \"SIM\", \"Sim\" ou \"sim\".",
            },
            {
                id: "q7",
                prompt: "O que esta f-string mostra?",
                code: "nome = \"Leo\"\npontos = 120\nprint(f\"{nome} fez {pontos} pontos\")",
                options: [
                    { id: "a", text: "{nome} fez {pontos} pontos" },
                    { id: "b", text: "Leo fez 120 pontos" },
                    { id: "c", text: "nome fez pontos pontos" },
                    { id: "d", text: "Um erro" },
                ],
                correctOptionId: "b",
                explanation: "Com um f antes das aspas, o Python troca o que está entre chaves { } pelo valor da variável. As f-strings são o jeito mais prático de montar frases no Python, parecido com as template strings do JavaScript.",
            },
            {
                id: "q8",
                prompt: "O que este código mostra?",
                code: "print(10 > 3)",
                options: [
                    { id: "a", text: "10" },
                    { id: "b", text: "Yes" },
                    { id: "c", text: "True" },
                    { id: "d", text: "7" },
                ],
                correctOptionId: "c",
                explanation: "Uma comparação responde verdadeiro ou falso, que no Python se escreve True e False (com a primeira letra maiúscula). 10 é maior que 3, então o resultado é True.",
            },
            {
                id: "q9",
                prompt: "Qual valor aparece na tela?",
                code: "aluno = {\"nome\": \"Bia\", \"idade\": 12, \"casa\": \"Ignis\"}\nprint(aluno[\"idade\"])",
                options: [
                    { id: "a", text: "Bia" },
                    { id: "b", text: "idade" },
                    { id: "c", text: "Ignis" },
                    { id: "d", text: "12" },
                ],
                correctOptionId: "d",
                explanation: "Entre chaves fica um dicionário: cada valor tem uma chave (um nome). Em vez de uma posição, usamos a chave para buscar: aluno[\"idade\"] é 12. É parecido com os objetos do JavaScript e as tabelas da Lua.",
            },
            {
                id: "q10",
                prompt: "Qual código sorteia um número de 1 a 6, como um dado?",
                options: [
                    { id: "a", text: "import random\nprint(random.randint(1, 6))" },
                    { id: "b", text: "print(dado(6))" },
                    { id: "c", text: "print(1 + 6)" },
                    { id: "d", text: "print(range(6))" },
                ],
                correctOptionId: "a",
                explanation: "O import random traz o módulo de sorteios do Python, e o randint(1, 6) sorteia um inteiro de 1 a 6, incluindo os dois. Os módulos são \"caixas de ferramentas\" prontas que você pode importar.",
            },
        ],
    },
    {
        title: "Linguagem Lua parte 2",
        icon: "🌓",
        difficulty: "medio",
        minLevel: 1,
        description: "Mais Lua: while, repeat, nil, elseif, and/or/not, tabelas, ipairs e laços com passo",
        rewardXp: 180,
        rewardCoins: 80,
        rewardItem: {
            name: "Fase Crescente",
            icon: "🌓",
            description: "Um pedaço da Lua que cresce a cada linha de código. Usar transforma o crescimento em XP.",
            rarity: "raro",
            value: 30,
            xp: 60,
        },
        kind: "quiz",
        questions: [
            {
                id: "q1",
                prompt: "O que este código mostra?",
                code: "local energia = 3\nwhile energia > 0 do\n  print(energia)\n  energia = energia - 1\nend",
                options: [
                    { id: "a", text: "1, 2 e 3" },
                    { id: "b", text: "3, 2, 1 e 0" },
                    { id: "c", text: "3, 2 e 1" },
                    { id: "d", text: "Nada" },
                ],
                correctOptionId: "c",
                explanation: "O while repete enquanto a condição for verdadeira: energia começa em 3 e cai 1 a cada volta, então aparecem 3, 2 e 1. Em Lua, o bloco do while começa com do e termina com end.",
            },
            {
                id: "q2",
                prompt: "Em Lua, como descobrimos quantos itens tem a tabela itens?",
                code: "local itens = {\"espada\", \"escudo\", \"poção\"}",
                options: [
                    { id: "a", text: "itens.length" },
                    { id: "b", text: "len(itens)" },
                    { id: "c", text: "#itens" },
                    { id: "d", text: "itens.size()" },
                ],
                correctOptionId: "c",
                explanation: "Em Lua, o operador # (cerquilha) dá o tamanho de uma lista ou de um texto: #itens é 3 e #\"Lua\" é 3. Cada linguagem tem seu jeito: length no JavaScript, len() no Python.",
            },
            {
                id: "q3",
                prompt: "Qual comando coloca \"mapa\" no fim da tabela itens?",
                options: [
                    { id: "a", text: "table.insert(itens, \"mapa\")" },
                    { id: "b", text: "itens.push(\"mapa\")" },
                    { id: "c", text: "itens.append(\"mapa\")" },
                    { id: "d", text: "itens + \"mapa\"" },
                ],
                correctOptionId: "a",
                explanation: "Em Lua, usamos table.insert() para adicionar um item a uma tabela. Sem dizer a posição, ele coloca no fim. Para tirar, existe table.remove(). Isso é muito usado em inventários no Roblox.",
            },
            {
                id: "q4",
                prompt: "Em Lua, qual é o valor de uma variável que ainda não recebeu nenhum valor?",
                code: "local tesouro\nprint(tesouro)",
                options: [
                    { id: "a", text: "0" },
                    { id: "b", text: "nil" },
                    { id: "c", text: "\"\" (texto vazio)" },
                    { id: "d", text: "false" },
                ],
                correctOptionId: "b",
                explanation: "Em Lua, nil significa \"nada\", a ausência de valor. Uma variável criada sem valor vale nil, e buscar um item que não existe numa tabela também dá nil. Conferir se algo é nil evita muitos erros nos scripts.",
            },
            {
                id: "q5",
                prompt: "Qual é o jeito certo de escrever \"senão se\" em Lua?",
                code: "if nota >= 9 then\n  print(\"Excelente\")\n??? nota >= 6 then\n  print(\"Aprovado\")\nelse\n  print(\"Estude mais\")\nend",
                options: [
                    { id: "a", text: "else if" },
                    { id: "b", text: "elif" },
                    { id: "c", text: "elseif" },
                    { id: "d", text: "senaose" },
                ],
                correctOptionId: "c",
                explanation: "Em Lua é elseif, tudo junto. Com else if separado, a Lua abre um novo if dentro do else, e aí ele precisaria de outro end. O elif é do Python.",
            },
            {
                id: "q6",
                prompt: "Em Lua, quais palavras representam \"e\", \"ou\" e \"não\" nas condições?",
                options: [
                    { id: "a", text: "&&, || e !" },
                    { id: "b", text: "and, or e not" },
                    { id: "c", text: "e, ou e nao" },
                    { id: "d", text: "+, - e *" },
                ],
                correctOptionId: "b",
                explanation: "A Lua usa palavras: and, or e not. Por exemplo: if temChave and not portaAberta then ... end. É mais fácil de ler do que os símbolos && e || do JavaScript e do Java.",
            },
            {
                id: "q7",
                prompt: "O que este código mostra?",
                code: "local frutas = {\"maçã\", \"uva\"}\nfor i, fruta in ipairs(frutas) do\n  print(i, fruta)\nend",
                options: [
                    { id: "a", text: "0 maçã e 1 uva" },
                    { id: "b", text: "Só maçã" },
                    { id: "c", text: "1 maçã e 2 uva" },
                    { id: "d", text: "2" },
                ],
                correctOptionId: "c",
                explanation: "O ipairs() percorre a lista em ordem, dando a posição (i) e o valor (fruta) a cada volta. Como em Lua a contagem começa do 1, aparecem \"1 maçã\" e \"2 uva\". No Roblox, isso é muito usado para percorrer jogadores e peças.",
            },
            {
                id: "q8",
                prompt: "O que este código mostra?",
                code: "local jogador = {nome = \"Ana\", vidas = 3}\nprint(jogador.vidas)",
                options: [
                    { id: "a", text: "Ana" },
                    { id: "b", text: "3" },
                    { id: "c", text: "vidas" },
                    { id: "d", text: "nil" },
                ],
                correctOptionId: "b",
                explanation: "Uma tabela da Lua também pode guardar valores com nome, como um dicionário. Com o ponto, pegamos o valor: jogador.vidas é 3. As tabelas são a única estrutura de dados da Lua e servem para quase tudo.",
            },
            {
                id: "q9",
                prompt: "Qual é a principal diferença do repeat ... until em relação ao while?",
                code: "repeat\n  print(\"Tentando...\")\nuntil true",
                options: [
                    { id: "a", text: "O repeat nunca roda" },
                    { id: "b", text: "O repeat roda o bloco pelo menos uma vez, porque só testa a condição no final" },
                    { id: "c", text: "Não há diferença" },
                    { id: "d", text: "O repeat só funciona com números" },
                ],
                correctOptionId: "b",
                explanation: "O repeat executa o bloco e só depois confere a condição do until. Se ela for verdadeira, para. Por isso o código acima mostra \"Tentando...\" uma vez. O while, ao contrário, testa antes e pode nem rodar.",
            },
            {
                id: "q10",
                prompt: "Quais números este laço mostra?",
                code: "for i = 0, 10, 5 do\n  print(i)\nend",
                options: [
                    { id: "a", text: "0, 1, 2, ... até 10" },
                    { id: "b", text: "0, 5 e 10" },
                    { id: "c", text: "5 e 10" },
                    { id: "d", text: "10, 5 e 0" },
                ],
                correctOptionId: "b",
                explanation: "O terceiro número do for é o passo: quanto somar a cada volta. Começando em 0 e indo até 10 de 5 em 5, aparecem 0, 5 e 10. Com passo negativo dá para contar para trás: for i = 3, 1, -1 mostra 3, 2 e 1.",
            },
        ],
    },
]

export default missions
