import { MissionContent } from "../../../src/engine/missions";

// Terceira leva de missões de quiz para as turmas de programação de 12 anos:
// ODS parte 3, Scratch parte 3, Roblox Studio, JavaScript, Linguagem Lua,
// Informática e Hardware. 10 perguntas cada, todas comentadas, sem repetir as
// das levas anteriores (programacao-12-anos.ts e programacao-12-anos-parte-2.ts).
// Importar com:
//   npm run missions:import -- <e-mail do professor> scripts/missions/programacao-12-anos-parte-3.ts
const missions: MissionContent[] = [
    {
        title: "ODS parte 3",
        icon: "🌏",
        difficulty: "iniciante",
        minLevel: 1,
        description: "A história da Agenda 2030, as metas, os 5 Ps e como os ODS se ligam uns aos outros",
        rewardXp: 150,
        rewardCoins: 60,
        rewardItem: {
            name: "Gota de Chuva Limpa",
            icon: "💧",
            description: "Uma gota guardada numa cisterna do sertão. Usar mostra o valor de cada gota em forma de XP.",
            rarity: "comum",
            value: 15,
            xp: 40,
        },
        kind: "quiz",
        questions: [
            {
                id: "q1",
                prompt: "O que quer dizer \"desenvolvimento sustentável\"?",
                options: [
                    { id: "a", text: "Construir o máximo de prédios possível" },
                    { id: "b", text: "Usar todos os recursos da natureza agora, sem pensar no futuro" },
                    { id: "c", text: "Atender às necessidades de hoje sem prejudicar as gerações futuras" },
                    { id: "d", text: "Parar de usar qualquer tecnologia" },
                ],
                correctOptionId: "c",
                explanation: "Desenvolvimento sustentável é crescer e melhorar a vida das pessoas hoje, mas cuidando para que quem vier depois (inclusive os seus netos!) também tenha água, comida, florestas e um planeta saudável.",
            },
            {
                id: "q2",
                prompt: "Antes dos ODS, a ONU tinha outro plano, válido de 2000 a 2015. Como ele se chamava?",
                options: [
                    { id: "a", text: "Objetivos de Desenvolvimento do Milênio (ODM)" },
                    { id: "b", text: "Copa do Mundo da Sustentabilidade" },
                    { id: "c", text: "Plano Real" },
                    { id: "d", text: "Agenda 1990" },
                ],
                correctOptionId: "a",
                explanation: "Eram os 8 Objetivos de Desenvolvimento do Milênio (ODM). Eles trouxeram avanços, como menos fome e mais crianças na escola. Em 2015, os ODS os substituíram com 17 objetivos mais amplos, que incluem também o meio ambiente e as cidades.",
            },
            {
                id: "q3",
                prompt: "Cada ODS é dividido em metas mais específicas. Quantas metas existem ao todo?",
                options: [
                    { id: "a", text: "17" },
                    { id: "b", text: "50" },
                    { id: "c", text: "1.000" },
                    { id: "d", text: "169" },
                ],
                correctOptionId: "d",
                explanation: "São 169 metas distribuídas entre os 17 objetivos. Por exemplo, acabar com o trabalho infantil é uma meta do ODS 8. As metas ajudam a medir se o mundo está mesmo avançando.",
            },
            {
                id: "q4",
                prompt: "A Agenda 2030 organiza os ODS em 5 grandes áreas, conhecidas como os \"5 Ps\". Quais são?",
                options: [
                    { id: "a", text: "Pessoas, Planeta, Prosperidade, Paz e Parcerias" },
                    { id: "b", text: "Pão, Peixe, Pizza, Pastel e Pudim" },
                    { id: "c", text: "Política, Poder, Prêmio, Prova e Pontos" },
                    { id: "d", text: "Praia, Parque, Praça, Prédio e Ponte" },
                ],
                correctOptionId: "a",
                explanation: "Os 5 Ps são Pessoas (acabar com a fome e a pobreza), Planeta (proteger a natureza), Prosperidade (vida digna para todos), Paz (sociedades justas e sem violência) e Parcerias (todos trabalhando juntos).",
            },
            {
                id: "q5",
                prompt: "Quantos países se comprometeram com a Agenda 2030 em 2015?",
                options: [
                    { id: "a", text: "Só os 10 países mais ricos" },
                    { id: "b", text: "Só o Brasil" },
                    { id: "c", text: "Os 193 países que fazem parte da ONU, incluindo o Brasil" },
                    { id: "d", text: "Nenhum, foi só uma sugestão" },
                ],
                correctOptionId: "c",
                explanation: "Todos os 193 países-membros da ONU aprovaram a Agenda 2030, e o Brasil é um deles. Isso mostra que os desafios dos ODS, como o clima e a fome, são de todo o planeta.",
            },
            {
                id: "q6",
                prompt: "Qual ODS fala de sociedades pacíficas, sem violência, com justiça para todos e governos honestos, que combatem a corrupção?",
                options: [
                    { id: "a", text: "ODS 7 – Energia limpa e acessível" },
                    { id: "b", text: "ODS 16 – Paz, justiça e instituições eficazes" },
                    { id: "c", text: "ODS 14 – Vida na água" },
                    { id: "d", text: "ODS 2 – Fome zero" },
                ],
                correctOptionId: "b",
                explanation: "É o ODS 16. Ele quer diminuir todas as formas de violência (inclusive contra crianças), garantir que todos tenham acesso à justiça e que as instituições sejam transparentes. O respeito e o diálogo na escola também fazem parte dessa ideia.",
            },
            {
                id: "q7",
                prompt: "Uma escola cria uma horta para produzir verduras para a merenda. Qual ODS está MAIS ligado a essa ideia?",
                options: [
                    { id: "a", text: "ODS 2 – Fome zero e agricultura sustentável" },
                    { id: "b", text: "ODS 9 – Indústria, inovação e infraestrutura" },
                    { id: "c", text: "ODS 16 – Paz, justiça e instituições eficazes" },
                    { id: "d", text: "ODS 7 – Energia limpa e acessível" },
                ],
                correctOptionId: "a",
                explanation: "A horta produz alimento saudável sem destruir a natureza, que é a ideia do ODS 2. E ela ainda ajuda outros ODS: ensina os alunos (ODS 4) e melhora a saúde de quem come (ODS 3).",
            },
            {
                id: "q8",
                prompt: "Por que dizemos que os ODS são \"integrados\"?",
                options: [
                    { id: "a", text: "Porque todos foram escritos no mesmo dia" },
                    { id: "b", text: "Porque é preciso escolher só um para cumprir" },
                    { id: "c", text: "Porque cada país cuida de um ODS diferente" },
                    { id: "d", text: "Porque avançar em um ODS ajuda os outros, e um problema em um atrapalha os outros" },
                ],
                correctOptionId: "d",
                explanation: "Os ODS estão ligados como peças de um sistema. Água limpa (ODS 6) melhora a saúde (ODS 3), e crianças saudáveis aprendem melhor na escola (ODS 4). Por isso eles precisam avançar juntos.",
            },
            {
                id: "q9",
                prompt: "No sertão do Nordeste, muitas famílias guardam a água da chuva em cisternas para beber e cozinhar na época da seca. Isso ajuda qual ODS?",
                options: [
                    { id: "a", text: "ODS 14 – Vida na água" },
                    { id: "b", text: "ODS 6 – Água potável e saneamento" },
                    { id: "c", text: "ODS 9 – Indústria, inovação e infraestrutura" },
                    { id: "d", text: "ODS 5 – Igualdade de gênero" },
                ],
                correctOptionId: "b",
                explanation: "As cisternas garantem água para as famílias durante a seca, que é o objetivo do ODS 6: água potável para todos. O ODS 14 trata da vida nos mares e rios, não da água para as pessoas usarem.",
            },
            {
                id: "q10",
                prompt: "Celulares, carregadores e computadores velhos viram lixo eletrônico. Qual é o destino certo para eles?",
                options: [
                    { id: "a", text: "Jogar no lixo comum de casa" },
                    { id: "b", text: "Queimar no quintal" },
                    { id: "c", text: "Levar a um ponto de coleta de lixo eletrônico, para serem reciclados com segurança" },
                    { id: "d", text: "Jogar no rio" },
                ],
                correctOptionId: "c",
                explanation: "Aparelhos eletrônicos têm metais e substâncias que poluem o solo e a água, mas também materiais que podem ser reaproveitados. Levar a um ponto de coleta ajuda o ODS 12 (Consumo e produção responsáveis).",
            },
        ],
    },
    {
        title: "Scratch parte 3",
        icon: "😺",
        difficulty: "medio",
        minLevel: 1,
        description: "Deslizar, efeitos, tamanho, camadas, listas, cronômetro e mais truques para seus projetos no Scratch",
        rewardXp: 180,
        rewardCoins: 80,
        rewardItem: {
            name: "Cronômetro Mágico",
            icon: "⏱️",
            description: "Um cronômetro que nunca atrasa, tirado do bloco de Sensores. Usar transforma cada segundo em XP.",
            rarity: "raro",
            value: 30,
            xp: 60,
        },
        kind: "quiz",
        questions: [
            {
                id: "q1",
                prompt: "Qual é a diferença entre \"vá para x: 100 y: 0\" e \"deslize por 1 segundos até x: 100 y: 0\"?",
                options: [
                    { id: "a", text: "O primeiro faz o ator pular na hora para a posição; o segundo leva o ator até lá em movimento, durante 1 segundo" },
                    { id: "b", text: "Não há diferença" },
                    { id: "c", text: "O segundo faz o ator sumir" },
                    { id: "d", text: "O primeiro só funciona no palco" },
                ],
                correctOptionId: "a",
                explanation: "O \"vá para\" teletransporta o ator na hora. O \"deslize\" mostra o caminho, como se o ator andasse até o ponto. Para animações suaves, o \"deslize\" fica muito mais bonito.",
            },
            {
                id: "q2",
                prompt: "O bloco \"mude o tamanho para 50 %\" faz o quê com o ator?",
                options: [
                    { id: "a", text: "Deixa o ator com o dobro do tamanho" },
                    { id: "b", text: "Deixa o ator com metade do tamanho original" },
                    { id: "c", text: "Move o ator 50 passos" },
                    { id: "d", text: "Deixa o ator 50% transparente" },
                ],
                correctOptionId: "b",
                explanation: "100% é o tamanho original do ator. 50% é a metade, e 200% é o dobro. Esse bloco fica na categoria Aparência e é ótimo para fazer um personagem crescer quando pega um item.",
            },
            {
                id: "q3",
                prompt: "Para o ator ficar trocando de cor como um arco-íris, qual script funciona?",
                code: "quando a bandeira verde for clicada\nsempre\n    adicione 25 ao efeito cor\nfim",
                options: [
                    { id: "a", text: "Esse script não funciona, cor não muda no Scratch" },
                    { id: "b", text: "Esse script troca o cenário" },
                    { id: "c", text: "Esse script funciona: a cada repetição, a cor do ator muda um pouco" },
                    { id: "d", text: "Esse script apaga o ator" },
                ],
                correctOptionId: "c",
                explanation: "Os efeitos gráficos ficam na categoria Aparência: cor, olho de peixe, redemoinho, pixelização, mosaico, brilho e fantasma. Dentro do \"sempre\", o \"adicione 25 ao efeito cor\" vai mudando a cor sem parar. Para voltar ao normal, use \"remova os efeitos gráficos\".",
            },
            {
                id: "q4",
                prompt: "Qual efeito deixa o ator transparente, como um fantasma?",
                options: [
                    { id: "a", text: "O efeito \"fantasma\"" },
                    { id: "b", text: "O efeito \"cor\"" },
                    { id: "c", text: "O efeito \"mosaico\"" },
                    { id: "d", text: "O efeito \"olho de peixe\"" },
                ],
                correctOptionId: "a",
                explanation: "Com \"mude o efeito fantasma para 50\", o ator fica meio transparente. Com 100, ele fica invisível, mas continua lá. Aumentando aos poucos dentro de um \"repita\", dá para fazer o ator desaparecer suavemente.",
            },
            {
                id: "q5",
                prompt: "Dois atores estão um em cima do outro e o gato ficou escondido atrás da árvore. Qual bloco traz o gato para a frente?",
                options: [
                    { id: "a", text: "\"mostre\"" },
                    { id: "b", text: "\"vá para a camada da frente\"" },
                    { id: "c", text: "\"mude o tamanho para 100 %\"" },
                    { id: "d", text: "\"aponte para a direção 90\"" },
                ],
                correctOptionId: "b",
                explanation: "Os atores ficam em camadas, como folhas empilhadas. O \"vá para a camada da frente\" (Aparência) coloca o ator por cima de todos. Também existe \"vá para trás 1 camadas\" para ajustar a ordem aos poucos.",
            },
            {
                id: "q6",
                prompt: "Você quer guardar vários nomes de frutas de uma vez, como \"maçã\", \"banana\" e \"uva\". O que você cria no Scratch?",
                options: [
                    { id: "a", text: "Um ator para cada fruta" },
                    { id: "b", text: "Um cenário" },
                    { id: "c", text: "Uma lista" },
                    { id: "d", text: "Um som" },
                ],
                correctOptionId: "c",
                explanation: "Uma variável guarda um valor só. Uma lista guarda vários valores em ordem. Em Variáveis, clique em \"Criar uma Lista\" e use blocos como \"adicione maçã a frutas\" e \"item 1 de frutas\". É ótimo para placares e jogos de perguntas.",
            },
            {
                id: "q7",
                prompt: "Num jogo de corrida contra o tempo, quais blocos ajudam a medir quantos segundos o jogador levou?",
                options: [
                    { id: "a", text: "\"zere o cronômetro\" e o bloco \"cronômetro\", da categoria Sensores" },
                    { id: "b", text: "\"mova 10 passos\" e \"gire 15 graus\"" },
                    { id: "c", text: "\"toque o som\" e \"pare todos os sons\"" },
                    { id: "d", text: "\"mostre\" e \"esconda\"" },
                ],
                correctOptionId: "a",
                explanation: "O cronômetro do Scratch conta os segundos desde que o projeto começou ou desde o último \"zere o cronômetro\". Zere no começo da corrida e, na chegada, use o bloco \"cronômetro\" para mostrar o tempo do jogador.",
            },
            {
                id: "q8",
                prompt: "O que o bloco \"espere até que <tocando em Bola?>\" faz?",
                options: [
                    { id: "a", text: "Espera sempre 1 segundo" },
                    { id: "b", text: "Apaga a bola" },
                    { id: "c", text: "Faz o ator ir até a bola" },
                    { id: "d", text: "Pausa o script até o ator encostar na Bola, e só então segue para o próximo bloco" },
                ],
                correctOptionId: "d",
                explanation: "O \"espere até que\" (Controle) segura o script até a condição ficar verdadeira. É ótimo para coisas como \"espere até que a tecla espaço esteja pressionada\" antes de começar a fase.",
            },
            {
                id: "q9",
                prompt: "Qual é o resultado do bloco \"junte (Olá) (mundo)\"?",
                options: [
                    { id: "a", text: "\"Olá mundo\", com espaço" },
                    { id: "b", text: "\"Olámundo\", tudo grudado" },
                    { id: "c", text: "Um erro" },
                    { id: "d", text: "\"mundo Olá\"" },
                ],
                correctOptionId: "b",
                explanation: "O \"junte\" (Operadores) cola dois textos exatamente como estão, então o resultado é \"Olámundo\". Para ter espaço, escreva \"Olá \" com um espaço no final. Ele é muito usado para montar frases, como juntar \"Seus pontos: \" com a variável pontos.",
            },
            {
                id: "q10",
                prompt: "Ao criar uma variável, o Scratch pergunta se ela é \"Para todos os atores\" ou \"Apenas para este ator\". Qual é a diferença?",
                options: [
                    { id: "a", text: "Não há diferença" },
                    { id: "b", text: "\"Apenas para este ator\" faz a variável aparecer em todos os projetos" },
                    { id: "c", text: "\"Para todos os atores\" pode ser usada e mudada por qualquer ator; \"Apenas para este ator\" só existe para aquele ator" },
                    { id: "d", text: "\"Para todos os atores\" apaga a variável quando o projeto para" },
                ],
                correctOptionId: "c",
                explanation: "Uma variável \"Para todos os atores\", como os pontos do jogo, é compartilhada por todos. Uma \"Apenas para este ator\", como a vida de cada inimigo, é própria daquele ator, e cada clone ganha a sua cópia.",
            },
        ],
    },
    {
        title: "Roblox Studio",
        icon: "🎮",
        difficulty: "iniciante",
        minLevel: 1,
        description: "Crie mundos 3D no Roblox Studio: Explorer, Properties, peças, testes e os primeiros scripts",
        rewardXp: 150,
        rewardCoins: 60,
        rewardItem: {
            name: "Peça Ancorada",
            icon: "🧱",
            description: "Uma peça com Anchored ligado: nunca cai, nem com terremoto. Usar transforma a estabilidade em XP.",
            rarity: "comum",
            value: 15,
            xp: 40,
        },
        kind: "quiz",
        questions: [
            {
                id: "q1",
                prompt: "O que é o Roblox Studio?",
                options: [
                    { id: "a", text: "O programa gratuito da Roblox para criar jogos e experiências que outras pessoas jogam no Roblox" },
                    { id: "b", text: "Um jogo de corrida" },
                    { id: "c", text: "Um editor de vídeos para YouTube" },
                    { id: "d", text: "Uma rede social de fotos" },
                ],
                correctOptionId: "a",
                explanation: "O Roblox Studio é a ferramenta de criação da Roblox. Com ele você monta mundos 3D, programa como eles funcionam e publica para outras pessoas jogarem. Todos os jogos do Roblox foram criados nele.",
            },
            {
                id: "q2",
                prompt: "Qual linguagem de programação é usada nos scripts do Roblox Studio?",
                options: [
                    { id: "a", text: "Scratch" },
                    { id: "b", text: "HTML" },
                    { id: "c", text: "Luau, uma linguagem baseada em Lua" },
                    { id: "d", text: "CSS" },
                ],
                correctOptionId: "c",
                explanation: "O Roblox usa o Luau, uma versão da linguagem Lua com alguns recursos a mais. E a Lua foi criada no Brasil! Quem aprende Lua consegue programar no Roblox com facilidade.",
            },
            {
                id: "q3",
                prompt: "Qual janela mostra a lista de tudo que existe no seu jogo (peças, scripts, luzes...), organizado como uma árvore?",
                options: [
                    { id: "a", text: "Toolbox" },
                    { id: "b", text: "Explorer" },
                    { id: "c", text: "Output" },
                    { id: "d", text: "Play" },
                ],
                correctOptionId: "b",
                explanation: "O Explorer mostra todos os objetos do jogo, uns dentro dos outros, como pastas. Por ele você encontra, seleciona, renomeia e organiza tudo. Se ele sumir, dá para abrir de novo pela aba View.",
            },
            {
                id: "q4",
                prompt: "Você selecionou uma peça e quer mudar a cor, o tamanho e o material dela. Qual janela você usa?",
                options: [
                    { id: "a", text: "Properties" },
                    { id: "b", text: "Output" },
                    { id: "c", text: "Toolbox" },
                    { id: "d", text: "Nenhuma, não dá para mudar" },
                ],
                correctOptionId: "a",
                explanation: "A janela Properties mostra as características do objeto selecionado, como Color (cor), Size (tamanho), Material e Transparency (transparência). É parecida com o painel Propriedades do App Inventor.",
            },
            {
                id: "q5",
                prompt: "Como se chamam os blocos básicos do Roblox Studio, como cubos, esferas e cilindros, usados para montar o mundo?",
                options: [
                    { id: "a", text: "Atores" },
                    { id: "b", text: "Fantasias" },
                    { id: "c", text: "Parts (peças)" },
                    { id: "d", text: "Tags" },
                ],
                correctOptionId: "c",
                explanation: "As Parts são as peças de construção do Roblox. Você pode mudar o formato (Block, Sphere, Cylinder, Wedge), mover, girar, redimensionar e juntar várias peças para criar casas, obstáculos e mapas inteiros.",
            },
            {
                id: "q6",
                prompt: "Você construiu uma plataforma flutuando no ar, mas quando testa o jogo ela cai. Qual propriedade você deve ligar?",
                options: [
                    { id: "a", text: "Transparency" },
                    { id: "b", text: "Color" },
                    { id: "c", text: "Material" },
                    { id: "d", text: "Anchored" },
                ],
                correctOptionId: "d",
                explanation: "Com Anchored (ancorada) ligado, a peça fica presa no lugar e a gravidade não a derruba. Peças de cenário, como chão, paredes e plataformas, quase sempre precisam estar ancoradas.",
            },
            {
                id: "q7",
                prompt: "Como você testa o seu jogo dentro do Roblox Studio, jogando com um personagem?",
                options: [
                    { id: "a", text: "Clicando em Play, na barra de cima" },
                    { id: "b", text: "Publicando o jogo e esperando um amigo testar" },
                    { id: "c", text: "Fechando o Roblox Studio" },
                    { id: "d", text: "Não dá para testar no Studio" },
                ],
                correctOptionId: "a",
                explanation: "O botão Play coloca o seu personagem dentro do jogo para testar na hora. Para voltar a editar, clique em Stop. Testar várias vezes durante a criação ajuda a achar bugs cedo.",
            },
            {
                id: "q8",
                prompt: "Onde aparece a mensagem deste script quando o jogo roda?",
                code: "print(\"Olá, Roblox!\")",
                options: [
                    { id: "a", text: "Numa placa dentro do jogo" },
                    { id: "b", text: "Na janela Output" },
                    { id: "c", text: "No chat dos jogadores" },
                    { id: "d", text: "Em lugar nenhum" },
                ],
                correctOptionId: "b",
                explanation: "O print mostra mensagens na janela Output, que serve para o criador acompanhar o que o script está fazendo. Os jogadores não veem essas mensagens. É ótimo para encontrar erros.",
            },
            {
                id: "q9",
                prompt: "Qual objeto define o lugar onde o personagem do jogador aparece quando o jogo começa?",
                options: [
                    { id: "a", text: "Terrain" },
                    { id: "b", text: "Camera" },
                    { id: "c", text: "SpawnLocation" },
                    { id: "d", text: "Lighting" },
                ],
                correctOptionId: "c",
                explanation: "O SpawnLocation é a plataforma de onde o jogador nasce (e renasce). Num jogo de obstáculos, colocar SpawnLocations ao longo do caminho funciona como checkpoints.",
            },
            {
                id: "q10",
                prompt: "Para que serve a Toolbox (caixa de ferramentas) do Roblox Studio?",
                options: [
                    { id: "a", text: "Para apagar o jogo" },
                    { id: "b", text: "Para encontrar modelos, imagens e sons prontos para usar no seu jogo" },
                    { id: "c", text: "Para conversar com outros jogadores" },
                    { id: "d", text: "Para mudar a senha da conta" },
                ],
                correctOptionId: "b",
                explanation: "A Toolbox tem modelos, imagens, sons e outros recursos criados pela Roblox e pela comunidade. Cuidado: modelos de desconhecidos podem ter scripts escondidos que estragam o jogo. Prefira os que são da própria Roblox ou de criadores verificados.",
            },
        ],
    },
    {
        title: "JavaScript",
        icon: "⚙️",
        difficulty: "medio",
        minLevel: 1,
        description: "A linguagem que dá vida às páginas: variáveis, textos, contas, condições, repetições, funções e listas",
        rewardXp: 180,
        rewardCoins: 80,
        rewardItem: {
            name: "Engrenagem do JavaScript",
            icon: "⚙️",
            description: "A engrenagem que faz as páginas da internet se mexerem. Usar coloca seu conhecimento para girar em forma de XP.",
            rarity: "raro",
            value: 30,
            xp: 60,
        },
        kind: "quiz",
        questions: [
            {
                id: "q1",
                prompt: "Numa página da internet, o HTML faz a estrutura e o CSS cuida da aparência. E o JavaScript?",
                options: [
                    { id: "a", text: "Ele guarda as imagens" },
                    { id: "b", text: "Ele dá comportamento e interatividade: responde a cliques, faz contas, muda a página" },
                    { id: "c", text: "Ele escolhe as cores" },
                    { id: "d", text: "Ele é o nome de um navegador" },
                ],
                correctOptionId: "b",
                explanation: "O JavaScript é uma linguagem de programação que roda no navegador. Ele faz a página reagir: abrir um menu, validar um formulário, mostrar um placar. Apesar do nome parecido, JavaScript e Java são linguagens diferentes.",
            },
            {
                id: "q2",
                prompt: "Qual comando mostra uma mensagem no console do navegador?",
                options: [
                    { id: "a", text: "print(\"Oi\")" },
                    { id: "b", text: "diga \"Oi\"" },
                    { id: "c", text: "console.log(\"Oi\")" },
                    { id: "d", text: "<p>Oi</p>" },
                ],
                correctOptionId: "c",
                explanation: "O console.log() escreve mensagens no console, que você abre com F12 no navegador. Os programadores usam muito para ver o valor das variáveis e encontrar bugs.",
            },
            {
                id: "q3",
                prompt: "Qual palavra cria uma variável cujo valor pode mudar depois, como os pontos de um jogo?",
                code: "??? pontos = 0;\npontos = pontos + 10;",
                options: [
                    { id: "a", text: "let" },
                    { id: "b", text: "const" },
                    { id: "c", text: "print" },
                    { id: "d", text: "if" },
                ],
                correctOptionId: "a",
                explanation: "O let cria uma variável que pode receber um novo valor. O const cria uma constante: depois de definido, o valor não pode ser trocado, e o código acima daria erro.",
            },
            {
                id: "q4",
                prompt: "O que este código mostra no console?",
                code: "console.log(2 + 3 * 2);",
                options: [
                    { id: "a", text: "10" },
                    { id: "b", text: "12" },
                    { id: "c", text: "7" },
                    { id: "d", text: "8" },
                ],
                correctOptionId: "d",
                explanation: "Igual na matemática, a multiplicação vem antes da soma: 3 * 2 = 6, e 2 + 6 = 8. Se você quiser somar primeiro, use parênteses: (2 + 3) * 2 dá 10.",
            },
            {
                id: "q5",
                prompt: "E este código, o que mostra?",
                code: "console.log(\"5\" + 3);",
                options: [
                    { id: "a", text: "8" },
                    { id: "b", text: "\"53\"" },
                    { id: "c", text: "Um erro" },
                    { id: "d", text: "2" },
                ],
                correctOptionId: "b",
                explanation: "Entre aspas, \"5\" é um texto (uma string), não um número. Quando você soma texto com número, o JavaScript junta os dois como texto: \"53\". É um bug muito comum quando o valor vem de um campo digitado pelo usuário!",
            },
            {
                id: "q6",
                prompt: "O que este código mostra no console?",
                code: "let idade = 12;\n\nif (idade >= 12) {\n  console.log(\"Pode jogar\");\n} else {\n  console.log(\"Ainda não\");\n}",
                options: [
                    { id: "a", text: "Pode jogar" },
                    { id: "b", text: "Ainda não" },
                    { id: "c", text: "As duas mensagens" },
                    { id: "d", text: "Nenhuma mensagem" },
                ],
                correctOptionId: "a",
                explanation: "O >= quer dizer \"maior ou igual\". Como 12 é igual a 12, a condição é verdadeira e o if mostra \"Pode jogar\". O else só roda quando a condição é falsa.",
            },
            {
                id: "q7",
                prompt: "O que este laço mostra no console?",
                code: "for (let i = 1; i <= 3; i++) {\n  console.log(i);\n}",
                options: [
                    { id: "a", text: "Só o número 3" },
                    { id: "b", text: "0, 1 e 2" },
                    { id: "c", text: "1, 2 e 3" },
                    { id: "d", text: "Nada" },
                ],
                correctOptionId: "c",
                explanation: "O for começa com i valendo 1, repete enquanto i for menor ou igual a 3 e, a cada volta, soma 1 (i++). Por isso mostra 1, 2 e 3. É como o \"repita\" do Scratch, mas com um contador.",
            },
            {
                id: "q8",
                prompt: "O que este código mostra?",
                code: "function saudar(nome) {\n  return \"Oi, \" + nome + \"!\";\n}\n\nconsole.log(saudar(\"Ana\"));",
                options: [
                    { id: "a", text: "saudar" },
                    { id: "b", text: "Oi, nome!" },
                    { id: "c", text: "Um erro" },
                    { id: "d", text: "Oi, Ana!" },
                ],
                correctOptionId: "d",
                explanation: "Uma função é um bloco de código com nome que pode ser usado várias vezes. Aqui, o nome recebe \"Ana\" e a função devolve (return) a frase montada. É como os \"Meus Blocos\" do Scratch.",
            },
            {
                id: "q9",
                prompt: "Qual valor aparece no console?",
                code: "let frutas = [\"maçã\", \"banana\", \"uva\"];\nconsole.log(frutas[0]);",
                options: [
                    { id: "a", text: "maçã" },
                    { id: "b", text: "banana" },
                    { id: "c", text: "uva" },
                    { id: "d", text: "0" },
                ],
                correctOptionId: "a",
                explanation: "Os colchetes criam um array (uma lista). No JavaScript, a contagem das posições começa do 0: frutas[0] é \"maçã\", frutas[1] é \"banana\" e frutas[2] é \"uva\".",
            },
            {
                id: "q10",
                prompt: "Num jogo, você quer conferir se a senha digitada é exatamente igual a \"dragão\". Qual comparação usar?",
                options: [
                    { id: "a", text: "senha = \"dragão\"" },
                    { id: "b", text: "senha === \"dragão\"" },
                    { id: "c", text: "senha + \"dragão\"" },
                    { id: "d", text: "senha => \"dragão\"" },
                ],
                correctOptionId: "b",
                explanation: "Um sinal de igual (=) guarda um valor na variável. Três sinais (===) comparam se dois valores são exatamente iguais e respondem true ou false. Confundir os dois é um erro bem comum de quem está começando.",
            },
        ],
    },
    {
        title: "Linguagem Lua",
        icon: "🌙",
        difficulty: "medio",
        minLevel: 1,
        description: "A linguagem brasileira usada no Roblox e em muitos jogos: print, variáveis, condições, laços, tabelas e funções",
        rewardXp: 180,
        rewardCoins: 80,
        rewardItem: {
            name: "Pedra Lunar",
            icon: "🌙",
            description: "Uma pedra brilhante trazida da Lua (a linguagem!). Usar transforma o brilho em XP.",
            rarity: "raro",
            value: 30,
            xp: 60,
        },
        kind: "quiz",
        questions: [
            {
                id: "q1",
                prompt: "Onde a linguagem de programação Lua foi criada?",
                options: [
                    { id: "a", text: "No Japão" },
                    { id: "b", text: "Nos Estados Unidos" },
                    { id: "c", text: "No Brasil, na PUC-Rio" },
                    { id: "d", text: "Na Lua, por astronautas" },
                ],
                correctOptionId: "c",
                explanation: "A Lua foi criada em 1993 na PUC-Rio, no Rio de Janeiro, por pesquisadores brasileiros. Por isso o nome é em português! Hoje ela é usada no mundo todo, principalmente em jogos, e é a base do Luau do Roblox.",
            },
            {
                id: "q2",
                prompt: "Qual comando mostra \"Olá!\" na tela em Lua?",
                options: [
                    { id: "a", text: "console.log(\"Olá!\")" },
                    { id: "b", text: "print(\"Olá!\")" },
                    { id: "c", text: "<p>Olá!</p>" },
                    { id: "d", text: "echo Olá!" },
                ],
                correctOptionId: "b",
                explanation: "Em Lua, usamos print() para mostrar mensagens. É o mesmo comando que você usa nos scripts do Roblox Studio, e a mensagem aparece na janela Output.",
            },
            {
                id: "q3",
                prompt: "Como escrevemos um comentário (um texto que o computador ignora) em Lua?",
                options: [
                    { id: "a", text: "-- isto é um comentário" },
                    { id: "b", text: "// isto é um comentário" },
                    { id: "c", text: "<!-- isto é um comentário -->" },
                    { id: "d", text: "# isto é um comentário" },
                ],
                correctOptionId: "a",
                explanation: "Em Lua, os comentários começam com dois hífens (--). Eles servem para explicar o código para você mesmo e para outras pessoas. Cada linguagem tem o seu jeito: no JavaScript são duas barras (//).",
            },
            {
                id: "q4",
                prompt: "O que este código mostra?",
                code: "local pontos = 10\npontos = pontos + 5\nprint(pontos)",
                options: [
                    { id: "a", text: "10" },
                    { id: "b", text: "5" },
                    { id: "c", text: "15" },
                    { id: "d", text: "pontos" },
                ],
                correctOptionId: "c",
                explanation: "A palavra local cria a variável pontos com o valor 10. Depois, pontos recebe o próprio valor mais 5, ficando 15. Usar local é uma boa prática: a variável só existe naquela parte do código.",
            },
            {
                id: "q5",
                prompt: "Em Lua, como juntamos dois textos?",
                code: "local nome = \"Ana\"\nprint(\"Olá, \" ?? nome)",
                options: [
                    { id: "a", text: "Com +" },
                    { id: "b", text: "Com &" },
                    { id: "c", text: "Com *" },
                    { id: "d", text: "Com .. (dois pontos seguidos)" },
                ],
                correctOptionId: "d",
                explanation: "Em Lua, textos são juntados com .. (dois pontos). \"Olá, \" .. nome resulta em \"Olá, Ana\". Diferente do JavaScript, o + em Lua serve só para somar números.",
            },
            {
                id: "q6",
                prompt: "Qual palavra fecha o bloco do if em Lua?",
                code: "if vidas == 0 then\n  print(\"Fim de jogo\")\n???",
                options: [
                    { id: "a", text: "end" },
                    { id: "b", text: "}" },
                    { id: "c", text: "stop" },
                    { id: "d", text: "fim" },
                ],
                correctOptionId: "a",
                explanation: "Em Lua, os blocos começam com uma palavra (como then ou do) e terminam com end. Repare também que a comparação usa dois sinais de igual (==): um só (=) serve para guardar um valor.",
            },
            {
                id: "q7",
                prompt: "Em Lua, qual operador significa \"diferente de\"?",
                options: [
                    { id: "a", text: "!=" },
                    { id: "b", text: "~=" },
                    { id: "c", text: "<>" },
                    { id: "d", text: "=/=" },
                ],
                correctOptionId: "b",
                explanation: "Em Lua, \"diferente de\" é ~= (til e igual). Por exemplo, if resposta ~= \"sim\" then ... end. Em muitas outras linguagens, como o JavaScript, o \"diferente\" é escrito !=.",
            },
            {
                id: "q8",
                prompt: "O que este laço mostra?",
                code: "for i = 1, 3 do\n  print(i)\nend",
                options: [
                    { id: "a", text: "Só o número 3" },
                    { id: "b", text: "0, 1, 2 e 3" },
                    { id: "c", text: "Nada" },
                    { id: "d", text: "1, 2 e 3" },
                ],
                correctOptionId: "d",
                explanation: "O for i = 1, 3 começa com i valendo 1 e repete até 3, somando 1 a cada volta. Então mostra 1, 2 e 3. É um jeito curto de repetir algo um número certo de vezes.",
            },
            {
                id: "q9",
                prompt: "O que este código mostra?",
                code: "local frutas = {\"maçã\", \"banana\", \"uva\"}\nprint(frutas[1])",
                options: [
                    { id: "a", text: "banana" },
                    { id: "b", text: "uva" },
                    { id: "c", text: "maçã" },
                    { id: "d", text: "1" },
                ],
                correctOptionId: "c",
                explanation: "Em Lua, as listas são feitas com tabelas, usando chaves { }. E, diferente do JavaScript, a contagem começa do 1: frutas[1] é \"maçã\". Essa é uma das características mais famosas da Lua.",
            },
            {
                id: "q10",
                prompt: "O que este código mostra?",
                code: "function dobro(n)\n  return n * 2\nend\n\nprint(dobro(5))",
                options: [
                    { id: "a", text: "10" },
                    { id: "b", text: "5" },
                    { id: "c", text: "dobro" },
                    { id: "d", text: "52" },
                ],
                correctOptionId: "a",
                explanation: "A função dobro recebe um número (n) e devolve (return) esse número vezes 2. Chamando dobro(5), o resultado é 10. Assim como o if e o for, a função também termina com end.",
            },
        ],
    },
    {
        title: "Informática",
        icon: "🖥️",
        difficulty: "iniciante",
        minLevel: 1,
        description: "Informática básica: sistema operacional, atalhos, arquivos, navegadores e segurança na internet",
        rewardXp: 150,
        rewardCoins: 60,
        rewardItem: {
            name: "Mouse Antigo",
            icon: "🖱️",
            description: "Um mouse de bolinha dos computadores de antigamente. Usar transforma cada clique em XP.",
            rarity: "comum",
            value: 15,
            xp: 40,
        },
        kind: "quiz",
        questions: [
            {
                id: "q1",
                prompt: "Qual é a diferença entre hardware e software?",
                options: [
                    { id: "a", text: "Hardware são as partes físicas do computador; software são os programas" },
                    { id: "b", text: "Hardware são os programas; software são as peças" },
                    { id: "c", text: "Os dois são a mesma coisa" },
                    { id: "d", text: "Hardware é a internet; software é a energia" },
                ],
                correctOptionId: "a",
                explanation: "Hardware é tudo que dá para tocar: teclado, tela, processador. Software são os programas e aplicativos, como o navegador, os jogos e o Scratch. Um precisa do outro para o computador funcionar.",
            },
            {
                id: "q2",
                prompt: "Qual destes é um sistema operacional?",
                options: [
                    { id: "a", text: "Google Chrome" },
                    { id: "b", text: "Windows" },
                    { id: "c", text: "Scratch" },
                    { id: "d", text: "YouTube" },
                ],
                correctOptionId: "b",
                explanation: "O sistema operacional é o programa principal, que controla o computador e permite que os outros programas funcionem. Windows, Linux e macOS são sistemas de computador. No celular, os mais comuns são Android e iOS.",
            },
            {
                id: "q3",
                prompt: "Quais atalhos de teclado copiam e colam um texto selecionado?",
                options: [
                    { id: "a", text: "Ctrl + S e Ctrl + P" },
                    { id: "b", text: "Ctrl + Z e Ctrl + Y" },
                    { id: "c", text: "Ctrl + C para copiar e Ctrl + V para colar" },
                    { id: "d", text: "Alt + F4 e Alt + Tab" },
                ],
                correctOptionId: "c",
                explanation: "Ctrl + C copia e Ctrl + V cola. Também existe o Ctrl + X, que recorta (tira do lugar para colar em outro). Esses atalhos funcionam em quase todos os programas e economizam muito tempo.",
            },
            {
                id: "q4",
                prompt: "Você apagou um parágrafo sem querer. Qual atalho desfaz a última ação?",
                options: [
                    { id: "a", text: "Ctrl + Z" },
                    { id: "b", text: "Ctrl + C" },
                    { id: "c", text: "Ctrl + A" },
                    { id: "d", text: "Ctrl + P" },
                ],
                correctOptionId: "a",
                explanation: "Ctrl + Z desfaz a última ação, e dá para apertar várias vezes. Ctrl + A seleciona tudo, Ctrl + S salva e Ctrl + P imprime. Salvar com Ctrl + S de vez em quando evita perder o trabalho!",
            },
            {
                id: "q5",
                prompt: "Qual é a diferença entre um arquivo e uma pasta?",
                options: [
                    { id: "a", text: "Não há diferença" },
                    { id: "b", text: "Um arquivo guarda um conteúdo (texto, foto, música); uma pasta organiza e agrupa arquivos e outras pastas" },
                    { id: "c", text: "A pasta só existe no celular" },
                    { id: "d", text: "O arquivo só guarda vídeos" },
                ],
                correctOptionId: "b",
                explanation: "Arquivos guardam o conteúdo: um projeto do Scratch, uma foto, um trabalho da escola. Pastas funcionam como gavetas para organizar os arquivos. Dar nomes claros aos dois ajuda a encontrar tudo depois.",
            },
            {
                id: "q6",
                prompt: "Pela extensão, qual destes arquivos é uma música?",
                options: [
                    { id: "a", text: "trabalho.docx" },
                    { id: "b", text: "foto.jpg" },
                    { id: "c", text: "jogo.sb3" },
                    { id: "d", text: "musica.mp3" },
                ],
                correctOptionId: "d",
                explanation: "A extensão, que vem depois do ponto, mostra o tipo do arquivo: .mp3 é áudio, .jpg e .png são imagens, .docx é documento do Word, .mp4 é vídeo e .sb3 é projeto do Scratch.",
            },
            {
                id: "q7",
                prompt: "Qual destes programas é um navegador de internet?",
                options: [
                    { id: "a", text: "Mozilla Firefox" },
                    { id: "b", text: "Windows" },
                    { id: "c", text: "Bloco de Notas" },
                    { id: "d", text: "Calculadora" },
                ],
                correctOptionId: "a",
                explanation: "Navegadores são os programas que abrem sites: Firefox, Google Chrome, Microsoft Edge e Safari são alguns exemplos. É no navegador que você acessa a CodeGuilds e o site do Scratch.",
            },
            {
                id: "q8",
                prompt: "Você apagou um arquivo do computador sem querer. Onde provavelmente dá para recuperá-lo?",
                options: [
                    { id: "a", text: "No navegador" },
                    { id: "b", text: "Na Lixeira" },
                    { id: "c", text: "Na Calculadora" },
                    { id: "d", text: "Não dá, ele sumiu para sempre" },
                ],
                correctOptionId: "b",
                explanation: "No Windows, os arquivos apagados vão primeiro para a Lixeira. Abra a Lixeira, clique com o botão direito no arquivo e escolha Restaurar. Só depois de esvaziar a Lixeira é que ele é apagado de vez.",
            },
            {
                id: "q9",
                prompt: "Qual destas é a senha mais forte?",
                options: [
                    { id: "a", text: "123456" },
                    { id: "b", text: "O seu nome" },
                    { id: "c", text: "Gato!Azul#Pula27Muros" },
                    { id: "d", text: "senha" },
                ],
                correctOptionId: "c",
                explanation: "Senhas fortes são longas e misturam letras maiúsculas e minúsculas, números e símbolos, sem usar seu nome ou sua data de nascimento. E nunca conte sua senha para colegas: só para os seus pais ou responsáveis.",
            },
            {
                id: "q10",
                prompt: "Chega uma mensagem dizendo que você ganhou um prêmio, pedindo para clicar num link e digitar sua senha. O que fazer?",
                options: [
                    { id: "a", text: "Clicar rápido para não perder o prêmio" },
                    { id: "b", text: "Mandar a mensagem para todos os amigos" },
                    { id: "c", text: "Digitar a senha, mas só uma vez" },
                    { id: "d", text: "Não clicar, não passar dados e avisar um adulto de confiança" },
                ],
                correctOptionId: "d",
                explanation: "Isso é um golpe, chamado phishing: uma mensagem falsa para roubar senhas e dados. Sites e jogos de verdade nunca pedem sua senha por mensagem. Na dúvida, não clique e mostre para um adulto.",
            },
        ],
    },
    {
        title: "Hardware",
        icon: "🔧",
        difficulty: "iniciante",
        minLevel: 1,
        description: "Por dentro do computador: processador, memória, armazenamento, placa-mãe, bits e bytes",
        rewardXp: 150,
        rewardCoins: 60,
        rewardItem: {
            name: "Chave do Técnico",
            icon: "🔧",
            description: "A ferramenta de quem abre o gabinete e entende cada peça. Usar transforma o conhecimento em XP.",
            rarity: "comum",
            value: 15,
            xp: 40,
        },
        kind: "quiz",
        questions: [
            {
                id: "q1",
                prompt: "Qual peça é considerada o \"cérebro\" do computador, porque executa as instruções dos programas?",
                options: [
                    { id: "a", text: "A fonte de alimentação" },
                    { id: "b", text: "O processador (CPU)" },
                    { id: "c", text: "O monitor" },
                    { id: "d", text: "O mouse" },
                ],
                correctOptionId: "b",
                explanation: "O processador, ou CPU (Unidade Central de Processamento), faz os cálculos e executa as instruções de todos os programas, bilhões de vezes por segundo. Quanto mais rápido ele é, mais rápido o computador responde.",
            },
            {
                id: "q2",
                prompt: "O que acontece com o que está na memória RAM quando o computador é desligado?",
                options: [
                    { id: "a", text: "Fica guardado para sempre" },
                    { id: "b", text: "Vai para a internet" },
                    { id: "c", text: "É apagado" },
                    { id: "d", text: "Vai para a impressora" },
                ],
                correctOptionId: "c",
                explanation: "A RAM é uma memória temporária e muito rápida, onde ficam os programas abertos e o que você está fazendo agora. Quando o computador desliga, ela é apagada. Por isso é preciso salvar os arquivos!",
            },
            {
                id: "q3",
                prompt: "Onde os seus arquivos, fotos e programas ficam guardados mesmo com o computador desligado?",
                options: [
                    { id: "a", text: "No armazenamento: o HD ou o SSD" },
                    { id: "b", text: "Na memória RAM" },
                    { id: "c", text: "No cooler" },
                    { id: "d", text: "No teclado" },
                ],
                correctOptionId: "a",
                explanation: "O HD e o SSD guardam os dados de forma permanente. O SSD não tem partes móveis e é bem mais rápido que o HD, que usa um disco girando. Com SSD, o computador liga e abre programas muito mais depressa.",
            },
            {
                id: "q4",
                prompt: "Qual é a placa principal do computador, onde o processador, a memória e as outras peças são conectados?",
                options: [
                    { id: "a", text: "A placa de vídeo" },
                    { id: "b", text: "A placa-mãe" },
                    { id: "c", text: "O pendrive" },
                    { id: "d", text: "A tela" },
                ],
                correctOptionId: "b",
                explanation: "A placa-mãe é a base que liga todas as peças e permite que elas conversem entre si. Processador, memória RAM, placa de vídeo e armazenamento são encaixados ou conectados nela.",
            },
            {
                id: "q5",
                prompt: "Qual peça é especializada em gerar imagens, muito importante para jogos 3D e edição de vídeo?",
                options: [
                    { id: "a", text: "A fonte de alimentação" },
                    { id: "b", text: "O HD" },
                    { id: "c", text: "A placa de vídeo (GPU)" },
                    { id: "d", text: "A caixa de som" },
                ],
                correctOptionId: "c",
                explanation: "A placa de vídeo, ou GPU, cuida de desenhar tudo o que aparece na tela. Jogos com gráficos 3D, como muitos do Roblox, exigem bastante dela. Hoje as GPUs também são usadas para treinar inteligências artificiais.",
            },
            {
                id: "q6",
                prompt: "Para que serve a fonte de alimentação do computador?",
                options: [
                    { id: "a", text: "Para resfriar o processador" },
                    { id: "b", text: "Para guardar arquivos" },
                    { id: "c", text: "Para conectar à internet" },
                    { id: "d", text: "Para transformar a energia da tomada e distribuir para as peças" },
                ],
                correctOptionId: "d",
                explanation: "A fonte recebe a energia da tomada e a converte para as tensões que cada peça precisa, distribuindo para a placa-mãe, os discos e a placa de vídeo. Uma fonte de má qualidade pode danificar o computador.",
            },
            {
                id: "q7",
                prompt: "Para que serve o cooler (ventoinha) que fica em cima do processador?",
                options: [
                    { id: "a", text: "Para resfriar o processador, que esquenta muito enquanto trabalha" },
                    { id: "b", text: "Para deixar o computador mais rápido na internet" },
                    { id: "c", text: "Para tocar música" },
                    { id: "d", text: "Para guardar os jogos" },
                ],
                correctOptionId: "a",
                explanation: "O processador gera muito calor. O cooler, junto com um dissipador de metal, tira esse calor. Se o computador esquenta demais, ele fica lento ou desliga sozinho para se proteger. Por isso é bom manter as entradas de ar limpas.",
            },
            {
                id: "q8",
                prompt: "A tela touch (sensível ao toque) de um celular é um dispositivo de entrada ou de saída?",
                options: [
                    { id: "a", text: "Só de entrada" },
                    { id: "b", text: "Só de saída" },
                    { id: "c", text: "Dos dois: mostra imagens (saída) e recebe seus toques (entrada)" },
                    { id: "d", text: "Nenhum dos dois" },
                ],
                correctOptionId: "c",
                explanation: "A tela touch é um dispositivo de entrada e saída ao mesmo tempo. Ela mostra as imagens, como um monitor, e também percebe onde você toca, como um mouse. Outro exemplo é um headset com microfone.",
            },
            {
                id: "q9",
                prompt: "Quantos bits formam 1 byte?",
                options: [
                    { id: "a", text: "2" },
                    { id: "b", text: "10" },
                    { id: "c", text: "100" },
                    { id: "d", text: "8" },
                ],
                correctOptionId: "d",
                explanation: "O bit é a menor informação do computador: um 0 ou um 1. Um byte é um grupo de 8 bits, o suficiente para guardar, por exemplo, uma letra. A partir dele vêm o kilobyte, o megabyte e o gigabyte.",
            },
            {
                id: "q10",
                prompt: "Qual destas medidas de armazenamento é a MAIOR?",
                options: [
                    { id: "a", text: "1 kilobyte (KB)" },
                    { id: "b", text: "1 megabyte (MB)" },
                    { id: "c", text: "1 terabyte (TB)" },
                    { id: "d", text: "1 gigabyte (GB)" },
                ],
                correctOptionId: "c",
                explanation: "A ordem é: KB < MB < GB < TB, e cada uma é cerca de mil vezes maior que a anterior. Uma foto de celular tem alguns MB, um jogo pode ter vários GB, e um HD pode guardar 1 TB ou mais.",
            },
        ],
    },
]

export default missions
