import { MissionContent } from "../../../src/engine/missions";

// Missões de quiz para as turmas de programação de 12 anos: ODS, introdução
// ao Scratch, o mundo da programação e blocos de código no Scratch.
// 10 perguntas cada, todas comentadas (a explicação aparece pro aluno no
// resultado). Importar com:
//   npm run missions:import -- <e-mail do professor> scripts/missions/programacao-12-anos.ts
const missions: MissionContent[] = [
    {
        title: "ODS",
        icon: "🌍",
        difficulty: "iniciante",
        minLevel: 1,
        description: "Conheça os Objetivos de Desenvolvimento Sustentável da ONU e como você pode ajudar o planeta",
        rewardXp: 150,
        rewardCoins: 60,
        rewardItem: {
            name: "Semente da Agenda 2030",
            icon: "🌱",
            description: "Uma semente que só cresce quando alguém cuida do planeta. Usar transforma o cuidado em XP.",
            rarity: "comum",
            value: 15,
            xp: 40,
        },
        kind: "quiz",
        questions: [
            {
                id: "q1",
                prompt: "Quantos são os Objetivos de Desenvolvimento Sustentável (ODS) da ONU?",
                options: [
                    { id: "a", text: "10" },
                    { id: "b", text: "12" },
                    { id: "c", text: "17" },
                    { id: "d", text: "25" },
                ],
                correctOptionId: "c",
                explanation: "São 17 ODS. Cada um trata de um grande desafio do mundo, como acabar com a fome, cuidar da água e garantir educação para todos. Juntos, eles formam um plano para deixar o planeta melhor para todo mundo.",
            },
            {
                id: "q2",
                prompt: "Os ODS fazem parte de uma agenda com um ano como meta. Que ano é esse?",
                options: [
                    { id: "a", text: "2025" },
                    { id: "b", text: "2030" },
                    { id: "c", text: "2050" },
                    { id: "d", text: "2100" },
                ],
                correctOptionId: "b",
                explanation: "A meta é 2030. Por isso o plano se chama Agenda 2030. Ele foi combinado em 2015 pelos países da ONU, que se comprometeram a trabalhar pelos 17 objetivos até lá.",
            },
            {
                id: "q3",
                prompt: "Qual organização criou os ODS, junto com os países que fazem parte dela?",
                options: [
                    { id: "a", text: "FIFA" },
                    { id: "b", text: "NASA" },
                    { id: "c", text: "ONU (Organização das Nações Unidas)" },
                    { id: "d", text: "Google" },
                ],
                correctOptionId: "c",
                explanation: "Foi a ONU, a Organização das Nações Unidas, que reúne quase todos os países do mundo (o Brasil é um deles). Os países membros aprovaram juntos os ODS em 2015.",
            },
            {
                id: "q4",
                prompt: "Qual ODS fala sobre garantir que todas as crianças e jovens tenham acesso a uma escola boa e inclusiva?",
                options: [
                    { id: "a", text: "ODS 4 – Educação de qualidade" },
                    { id: "b", text: "ODS 7 – Energia limpa e acessível" },
                    { id: "c", text: "ODS 14 – Vida na água" },
                    { id: "d", text: "ODS 9 – Indústria, inovação e infraestrutura" },
                ],
                correctOptionId: "a",
                explanation: "É o ODS 4, Educação de qualidade. Ele quer que todo mundo possa aprender, inclusive pessoas com deficiência e quem mora longe das cidades. Aprender programação na escola também faz parte desse objetivo!",
            },
            {
                id: "q5",
                prompt: "Fechar a torneira enquanto escova os dentes ajuda principalmente qual ODS?",
                options: [
                    { id: "a", text: "ODS 2 – Fome zero" },
                    { id: "b", text: "ODS 6 – Água potável e saneamento" },
                    { id: "c", text: "ODS 5 – Igualdade de gênero" },
                    { id: "d", text: "ODS 16 – Paz, justiça e instituições eficazes" },
                ],
                correctOptionId: "b",
                explanation: "O ODS 6 trata de água limpa e saneamento básico (esgoto tratado) para todos. A água potável não é infinita: economizar no dia a dia ajuda a ter água para mais pessoas.",
            },
            {
                id: "q6",
                prompt: "O aquecimento global e as mudanças no clima são o tema de qual ODS?",
                options: [
                    { id: "a", text: "ODS 3 – Saúde e bem-estar" },
                    { id: "b", text: "ODS 11 – Cidades e comunidades sustentáveis" },
                    { id: "c", text: "ODS 13 – Ação contra a mudança global do clima" },
                    { id: "d", text: "ODS 1 – Erradicação da pobreza" },
                ],
                correctOptionId: "c",
                explanation: "É o ODS 13. Ele pede ações para diminuir os gases que esquentam o planeta (como os que saem da queima de combustíveis) e para proteger as pessoas de secas, enchentes e outros eventos extremos.",
            },
            {
                id: "q7",
                prompt: "Proteger os oceanos, os rios e os animais que vivem neles, evitando que o plástico chegue ao mar, é o foco de qual ODS?",
                options: [
                    { id: "a", text: "ODS 15 – Vida terrestre" },
                    { id: "b", text: "ODS 14 – Vida na água" },
                    { id: "c", text: "ODS 8 – Trabalho decente e crescimento econômico" },
                    { id: "d", text: "ODS 10 – Redução das desigualdades" },
                ],
                correctOptionId: "b",
                explanation: "É o ODS 14, Vida na água. Muito plástico jogado fora acaba no mar e pode ferir tartarugas, peixes e aves. Já o ODS 15, Vida terrestre, cuida das florestas e dos animais da terra.",
            },
            {
                id: "q8",
                prompt: "Qual ODS quer acabar com a fome no mundo e incentivar uma agricultura que não destrua a natureza?",
                options: [
                    { id: "a", text: "ODS 2 – Fome zero e agricultura sustentável" },
                    { id: "b", text: "ODS 12 – Consumo e produção responsáveis" },
                    { id: "c", text: "ODS 17 – Parcerias e meios de implementação" },
                    { id: "d", text: "ODS 6 – Água potável e saneamento" },
                ],
                correctOptionId: "a",
                explanation: "É o ODS 2, Fome zero e agricultura sustentável. A ideia é que todas as pessoas tenham comida suficiente e saudável, produzida de um jeito que cuide do solo e da água para as próximas gerações.",
            },
            {
                id: "q9",
                prompt: "Separar o lixo para reciclagem, evitar desperdiçar comida e consertar objetos em vez de jogá-los fora são atitudes ligadas a qual ODS?",
                options: [
                    { id: "a", text: "ODS 7 – Energia limpa e acessível" },
                    { id: "b", text: "ODS 4 – Educação de qualidade" },
                    { id: "c", text: "ODS 12 – Consumo e produção responsáveis" },
                    { id: "d", text: "ODS 13 – Ação contra a mudança global do clima" },
                ],
                correctOptionId: "c",
                explanation: "É o ODS 12, Consumo e produção responsáveis. Ele propõe usar os recursos do planeta com cuidado: comprar só o necessário, reaproveitar, reciclar e gerar menos lixo.",
            },
            {
                id: "q10",
                prompt: "O ODS 17 fala de parcerias. Por que ele é importante para todos os outros?",
                options: [
                    { id: "a", text: "Porque cada país deve resolver seus problemas sozinho" },
                    { id: "b", text: "Porque só os cientistas podem ajudar nos ODS" },
                    { id: "c", text: "Porque os ODS só valem para países ricos" },
                    { id: "d", text: "Porque os objetivos só serão alcançados com governos, empresas, escolas e pessoas trabalhando juntos" },
                ],
                correctOptionId: "d",
                explanation: "O ODS 17 lembra que ninguém consegue sozinho: países, empresas, escolas e cada um de nós precisam colaborar, trocando conhecimento e tecnologia. Até um jogo no Scratch que ensina a separar o lixo é uma forma de ajudar!",
            },
        ],
    },
    {
        title: "Introdução ao Scratch",
        icon: "🐱",
        difficulty: "iniciante",
        minLevel: 1,
        description: "Dê os primeiros passos no Scratch: atores, palco, fantasias e a bandeira verde",
        rewardXp: 150,
        rewardCoins: 60,
        rewardItem: {
            name: "Bigode do Gato Scratch",
            icon: "😺",
            description: "Dizem que caiu do próprio Gato Scratch. Usar faz você lembrar de tudo que aprendeu no palco.",
            rarity: "comum",
            value: 15,
            xp: 40,
        },
        kind: "quiz",
        questions: [
            {
                id: "q1",
                prompt: "O que é o Scratch?",
                options: [
                    { id: "a", text: "Um jogo de corrida para celular" },
                    { id: "b", text: "Uma linguagem de programação visual, em que montamos programas encaixando blocos" },
                    { id: "c", text: "Um editor de vídeos" },
                    { id: "d", text: "Uma rede social de fotos" },
                ],
                correctOptionId: "b",
                explanation: "O Scratch é uma linguagem de programação visual: em vez de digitar código, você arrasta e encaixa blocos coloridos, como peças de quebra-cabeça. Com ele dá para criar jogos, animações e histórias.",
            },
            {
                id: "q2",
                prompt: "Quem criou o Scratch?",
                options: [
                    { id: "a", text: "O MIT Media Lab, um laboratório de uma universidade dos Estados Unidos" },
                    { id: "b", text: "A Microsoft" },
                    { id: "c", text: "A Nintendo" },
                    { id: "d", text: "A NASA" },
                ],
                correctOptionId: "a",
                explanation: "O Scratch foi criado por um grupo do MIT Media Lab, o laboratório de mídia do Instituto de Tecnologia de Massachusetts (EUA). Ele foi lançado em 2007 e é gratuito para todo mundo.",
            },
            {
                id: "q3",
                prompt: "Qual personagem já aparece no palco quando você começa um projeto novo no Scratch?",
                options: [
                    { id: "a", text: "Um cachorro" },
                    { id: "b", text: "Um robô" },
                    { id: "c", text: "O gato laranja, mascote do Scratch" },
                    { id: "d", text: "Nenhum, o palco começa vazio" },
                ],
                correctOptionId: "c",
                explanation: "Todo projeto novo começa com o gato laranja, o mascote do Scratch. Você pode programar ele, trocar por outro personagem ou apagá-lo.",
            },
            {
                id: "q4",
                prompt: "No Scratch, como se chamam os personagens e objetos que você programa (o gato, uma bola, uma nave...)?",
                options: [
                    { id: "a", text: "Cenários" },
                    { id: "b", text: "Blocos" },
                    { id: "c", text: "Atores" },
                    { id: "d", text: "Arquivos" },
                ],
                correctOptionId: "c",
                explanation: "São os atores (em inglês, \"sprites\"). Cada ator tem seus próprios blocos de código, fantasias e sons. Um jogo pode ter vários atores ao mesmo tempo.",
            },
            {
                id: "q5",
                prompt: "Como se chama a imagem de fundo do palco, como uma floresta, o espaço ou uma sala de aula?",
                options: [
                    { id: "a", text: "Cenário" },
                    { id: "b", text: "Fantasia" },
                    { id: "c", text: "Ator" },
                    { id: "d", text: "Extensão" },
                ],
                correctOptionId: "a",
                explanation: "É o cenário. O palco pode ter vários cenários e trocar entre eles, por exemplo para mudar de fase num jogo. As fantasias são as aparências dos atores, não do fundo.",
            },
            {
                id: "q6",
                prompt: "Para que serve a bandeira verde que fica em cima do palco?",
                options: [
                    { id: "a", text: "Para salvar o projeto" },
                    { id: "b", text: "Para começar o projeto" },
                    { id: "c", text: "Para apagar todos os blocos" },
                    { id: "d", text: "Para mudar o idioma" },
                ],
                correctOptionId: "b",
                explanation: "A bandeira verde começa o projeto: todos os scripts que começam com \"quando a bandeira verde for clicada\" passam a rodar. O botão vermelho, ao lado, para tudo.",
            },
            {
                id: "q7",
                prompt: "O palco do Scratch funciona como um plano com coordenadas x e y. Onde fica a posição x: 0, y: 0?",
                options: [
                    { id: "a", text: "No canto superior esquerdo" },
                    { id: "b", text: "No canto inferior direito" },
                    { id: "c", text: "Bem no centro do palco" },
                    { id: "d", text: "Fora do palco" },
                ],
                correctOptionId: "c",
                explanation: "O ponto x: 0, y: 0 é o centro do palco. O x vai de -240 (esquerda) a 240 (direita) e o y vai de -180 (embaixo) a 180 (em cima). Assim dá para dizer exatamente onde cada ator está.",
            },
            {
                id: "q8",
                prompt: "Trocar rapidamente as fantasias de um ator serve para quê?",
                options: [
                    { id: "a", text: "Para criar a ilusão de movimento, como numa animação" },
                    { id: "b", text: "Para deixar o projeto mais rápido" },
                    { id: "c", text: "Para apagar o ator" },
                    { id: "d", text: "Para tocar uma música" },
                ],
                correctOptionId: "a",
                explanation: "Fantasias são as aparências de um ator. Se você troca uma pela outra rapidamente (por exemplo, com as pernas em posições diferentes), parece que ele está andando. É assim que os desenhos animados funcionam!",
            },
            {
                id: "q9",
                prompt: "Quando você salva um projeto do Scratch 3 no computador, qual é a extensão do arquivo?",
                options: [
                    { id: "a", text: ".mp4" },
                    { id: "b", text: ".pdf" },
                    { id: "c", text: ".docx" },
                    { id: "d", text: ".sb3" },
                ],
                correctOptionId: "d",
                explanation: "Os projetos do Scratch 3 são salvos com a extensão .sb3. É esse o arquivo que você envia nas missões de entrega da CodeGuilds e que dá para abrir de novo no Scratch depois.",
            },
            {
                id: "q10",
                prompt: "No site do Scratch, o que significa fazer um \"remix\" de um projeto?",
                options: [
                    { id: "a", text: "Apagar o projeto de outra pessoa" },
                    { id: "b", text: "Criar a sua própria versão de um projeto compartilhado, mantendo o crédito do autor original" },
                    { id: "c", text: "Copiar o projeto e dizer que foi você que fez tudo" },
                    { id: "d", text: "Colocar uma música no projeto" },
                ],
                correctOptionId: "b",
                explanation: "Remixar é partir do projeto de alguém para criar uma versão sua, com mudanças e ideias novas. O Scratch mostra automaticamente de quem é o projeto original: dar crédito é uma regra de respeito da comunidade.",
            },
        ],
    },
    {
        title: "O Mundo da Programação",
        icon: "💻",
        difficulty: "iniciante",
        minLevel: 1,
        description: "Algoritmos, bugs, variáveis e outras ideias que todo programador precisa conhecer",
        rewardXp: 150,
        rewardCoins: 60,
        rewardItem: {
            name: "Pergaminho do Algoritmo",
            icon: "📜",
            description: "Um pergaminho com os passos de um algoritmo muito antigo. Usar revela o conhecimento escrito nele em forma de XP.",
            rarity: "comum",
            value: 15,
            xp: 40,
        },
        kind: "quiz",
        questions: [
            {
                id: "q1",
                prompt: "O que é um algoritmo?",
                options: [
                    { id: "a", text: "Um tipo de computador muito rápido" },
                    { id: "b", text: "Um vírus de computador" },
                    { id: "c", text: "Uma sequência de passos, em ordem, para resolver um problema ou fazer uma tarefa" },
                    { id: "d", text: "Um jogo de matemática" },
                ],
                correctOptionId: "c",
                explanation: "Um algoritmo é uma sequência de passos bem definidos, em ordem. Uma receita de bolo é um algoritmo! Na programação, escrevemos algoritmos de um jeito que o computador consegue seguir.",
            },
            {
                id: "q2",
                prompt: "Veja os passos para fazer um sanduíche. Qual está fora de ordem?",
                code: "1. Pegar duas fatias de pão\n2. Comer o sanduíche\n3. Passar a manteiga\n4. Colocar o queijo",
                options: [
                    { id: "a", text: "O passo 1" },
                    { id: "b", text: "O passo 2" },
                    { id: "c", text: "O passo 3" },
                    { id: "d", text: "Nenhum, está tudo certo" },
                ],
                correctOptionId: "b",
                explanation: "Não dá para comer o sanduíche antes de montá-lo! O passo 2 deveria ser o último. Num programa é igual: a ordem das instruções muda o resultado, e o computador faz exatamente o que está escrito.",
            },
            {
                id: "q3",
                prompt: "Qual destes é uma linguagem de programação?",
                options: [
                    { id: "a", text: "Python" },
                    { id: "b", text: "Google Chrome" },
                    { id: "c", text: "Windows" },
                    { id: "d", text: "YouTube" },
                ],
                correctOptionId: "a",
                explanation: "Python é uma linguagem de programação, assim como JavaScript, Java e o próprio Scratch. O Chrome é um navegador, o Windows é um sistema operacional e o YouTube é um site: todos foram criados com programação, mas não são linguagens.",
            },
            {
                id: "q4",
                prompt: "Na programação, o que é um \"bug\"?",
                options: [
                    { id: "a", text: "Um computador novo" },
                    { id: "b", text: "Um erro no programa que faz ele funcionar de um jeito diferente do esperado" },
                    { id: "c", text: "Um botão do teclado" },
                    { id: "d", text: "Um programa que nunca dá erro" },
                ],
                correctOptionId: "b",
                explanation: "Bug é um erro no programa. Encontrar e corrigir bugs se chama depurar (em inglês, \"debug\"). Uma história famosa conta que, em 1947, encontraram uma mariposa presa dentro de um computador, e o termo ficou ainda mais conhecido.",
            },
            {
                id: "q5",
                prompt: "Lá no fundo, o computador guarda e processa tudo usando apenas dois símbolos. Quais são eles?",
                options: [
                    { id: "a", text: "A e B" },
                    { id: "b", text: "+ e -" },
                    { id: "c", text: "0 e 1" },
                    { id: "d", text: "X e Y" },
                ],
                correctOptionId: "c",
                explanation: "O computador usa o sistema binário, só com 0 e 1 (desligado e ligado). Textos, fotos, músicas e jogos viram longas sequências de zeros e uns. As linguagens de programação existem para a gente não precisar escrever direto em binário.",
            },
            {
                id: "q6",
                prompt: "Qual destes é um dispositivo de entrada, ou seja, que manda informações PARA o computador?",
                options: [
                    { id: "a", text: "O monitor" },
                    { id: "b", text: "A caixa de som" },
                    { id: "c", text: "A impressora" },
                    { id: "d", text: "O teclado" },
                ],
                correctOptionId: "d",
                explanation: "O teclado é de entrada: ele manda para o computador as teclas que você aperta. Mouse, microfone e câmera também. Já o monitor, a caixa de som e a impressora são de saída: mostram ou entregam o resultado.",
            },
            {
                id: "q7",
                prompt: "Num jogo, os pontos do jogador mudam o tempo todo. Onde o programa guarda esse valor?",
                options: [
                    { id: "a", text: "Numa variável" },
                    { id: "b", text: "No mouse" },
                    { id: "c", text: "Na tela de carregamento" },
                    { id: "d", text: "Em lugar nenhum, o computador adivinha" },
                ],
                correctOptionId: "a",
                explanation: "Uma variável é como uma caixinha com nome (por exemplo, \"pontos\") que guarda um valor. O valor pode mudar durante o programa: começa em 0 e aumenta a cada moeda coletada.",
            },
            {
                id: "q8",
                prompt: "Que tipo de instrução é esta?",
                code: "se estiver chovendo então\n    levar guarda-chuva\nsenão\n    levar boné",
                options: [
                    { id: "a", text: "Uma repetição" },
                    { id: "b", text: "Uma condição (o programa toma uma decisão)" },
                    { id: "c", text: "Uma variável" },
                    { id: "d", text: "Um bug" },
                ],
                correctOptionId: "b",
                explanation: "É uma condição, também chamada de condicional (\"se... então... senão\"). O programa testa se algo é verdadeiro e escolhe o que fazer. Os jogos usam isso o tempo todo: se o jogador encostar no inimigo, então perde uma vida.",
            },
            {
                id: "q9",
                prompt: "Para desenhar 100 estrelas, em vez de escrever \"desenhe uma estrela\" 100 vezes, o que um programador usa?",
                options: [
                    { id: "a", text: "Uma condição" },
                    { id: "b", text: "Um bug" },
                    { id: "c", text: "Uma repetição (também chamada de laço ou loop)" },
                    { id: "d", text: "Um dispositivo de saída" },
                ],
                correctOptionId: "c",
                explanation: "Uma repetição (laço ou loop) executa as mesmas instruções várias vezes: \"repita 100 vezes: desenhe uma estrela\". O programa fica menor, mais fácil de ler e de mudar.",
            },
            {
                id: "q10",
                prompt: "Quem é considerada a primeira pessoa programadora da história?",
                options: [
                    { id: "a", text: "Ada Lovelace" },
                    { id: "b", text: "Albert Einstein" },
                    { id: "c", text: "Marie Curie" },
                    { id: "d", text: "Isaac Newton" },
                ],
                correctOptionId: "a",
                explanation: "Ada Lovelace, uma matemática inglesa, escreveu por volta de 1843 um algoritmo para a Máquina Analítica, um computador mecânico imaginado por Charles Babbage. Por isso ela é considerada a primeira programadora, mais de 100 anos antes dos computadores modernos.",
            },
        ],
    },
    {
        title: "Blocos de Código no Scratch",
        icon: "🧩",
        difficulty: "medio",
        minLevel: 1,
        description: "Movimento, eventos, controle, sensores e variáveis: descubra o que cada bloco faz",
        rewardXp: 180,
        rewardCoins: 80,
        rewardItem: {
            name: "Bloco Dourado",
            icon: "🧩",
            description: "Um bloco raro que se encaixa em qualquer script. Usar libera a energia guardada nele em forma de XP.",
            rarity: "raro",
            value: 30,
            xp: 60,
        },
        kind: "quiz",
        questions: [
            {
                id: "q1",
                prompt: "Em qual categoria de blocos fica o bloco \"mova 10 passos\"?",
                options: [
                    { id: "a", text: "Aparência" },
                    { id: "b", text: "Movimento" },
                    { id: "c", text: "Som" },
                    { id: "d", text: "Operadores" },
                ],
                correctOptionId: "b",
                explanation: "Fica em Movimento, a categoria azul. Lá estão os blocos que mudam a posição e a direção do ator, como \"mova 10 passos\", \"gire 15 graus\" e \"vá para x: 0 y: 0\".",
            },
            {
                id: "q2",
                prompt: "O bloco \"quando a bandeira verde for clicada\" começa um script. De qual categoria ele é?",
                options: [
                    { id: "a", text: "Controle" },
                    { id: "b", text: "Sensores" },
                    { id: "c", text: "Eventos" },
                    { id: "d", text: "Variáveis" },
                ],
                correctOptionId: "c",
                explanation: "É da categoria Eventos, a amarela. Os eventos dizem QUANDO um script começa: ao clicar na bandeira verde, ao apertar uma tecla, ao clicar no ator... Repare que eles têm formato de chapéu: nada se encaixa em cima deles.",
            },
            {
                id: "q3",
                prompt: "Quantos passos o ator anda ao todo quando este script roda?",
                code: "quando a bandeira verde for clicada\nrepita 4 vezes\n    mova 10 passos\nfim",
                options: [
                    { id: "a", text: "10 passos" },
                    { id: "b", text: "14 passos" },
                    { id: "c", text: "4 passos" },
                    { id: "d", text: "40 passos" },
                ],
                correctOptionId: "d",
                explanation: "O bloco \"repita 4 vezes\" executa o que está dentro dele 4 vezes. Como dentro tem \"mova 10 passos\", o ator anda 10 + 10 + 10 + 10 = 40 passos.",
            },
            {
                id: "q4",
                prompt: "Qual é a diferença entre os blocos \"sempre\" e \"repita 10 vezes\"?",
                options: [
                    { id: "a", text: "O \"sempre\" repete sem parar até o projeto ser parado; o \"repita 10 vezes\" para depois de 10 vezes" },
                    { id: "b", text: "Não há diferença" },
                    { id: "c", text: "O \"sempre\" roda só uma vez" },
                    { id: "d", text: "O \"repita 10 vezes\" nunca para" },
                ],
                correctOptionId: "a",
                explanation: "Os dois são blocos de repetição (categoria Controle). O \"sempre\" é ótimo para coisas que acontecem o jogo inteiro, como seguir o mouse. O \"repita\" serve quando você sabe quantas vezes quer repetir.",
            },
            {
                id: "q5",
                prompt: "O bloco \"tocando em borda?\" verifica se o ator encostou na borda do palco. De qual categoria ele é?",
                options: [
                    { id: "a", text: "Movimento" },
                    { id: "b", text: "Sensores" },
                    { id: "c", text: "Som" },
                    { id: "d", text: "Meus Blocos" },
                ],
                correctOptionId: "b",
                explanation: "É da categoria Sensores, a azul-clara. Os sensores fazem perguntas (\"está tocando em...?\", \"a tecla espaço foi pressionada?\") e respondem verdadeiro ou falso. Eles se encaixam em blocos como o \"se ... então\".",
            },
            {
                id: "q6",
                prompt: "Qual é o valor da variável \"pontos\" depois que este script roda?",
                code: "quando a bandeira verde for clicada\nmude pontos para 0\nrepita 3 vezes\n    adicione 1 a pontos\nfim",
                options: [
                    { id: "a", text: "0" },
                    { id: "b", text: "1" },
                    { id: "c", text: "3" },
                    { id: "d", text: "4" },
                ],
                correctOptionId: "c",
                explanation: "Primeiro \"mude pontos para 0\" zera a variável. Depois, o \"adicione 1 a pontos\" roda 3 vezes: 0 + 1 + 1 + 1 = 3. Zerar a variável no começo garante que o jogo sempre comece do zero.",
            },
            {
                id: "q7",
                prompt: "Você quer criar um dado que sorteia um número de 1 a 6. Qual bloco usar?",
                options: [
                    { id: "a", text: "mova 6 passos" },
                    { id: "b", text: "espere 6 seg" },
                    { id: "c", text: "número aleatório entre 1 e 6" },
                    { id: "d", text: "repita 6 vezes" },
                ],
                correctOptionId: "c",
                explanation: "O bloco \"número aleatório entre 1 e 6\", da categoria Operadores (verde), sorteia um número a cada vez que é usado. É perfeito para dados, inimigos que aparecem em lugares diferentes e jogos de sorte.",
            },
            {
                id: "q8",
                prompt: "Qual é a diferença entre \"diga Olá!\" e \"diga Olá! por 2 segundos\"?",
                options: [
                    { id: "a", text: "Nenhuma, os dois somem depois de 2 segundos" },
                    { id: "b", text: "O primeiro deixa o balão na tela; o segundo mostra o balão por 2 segundos, apaga e só então segue para o próximo bloco" },
                    { id: "c", text: "O primeiro toca um som" },
                    { id: "d", text: "O segundo não mostra nada" },
                ],
                correctOptionId: "b",
                explanation: "O \"diga Olá!\" mostra o balão e já passa para o próximo bloco, deixando o balão na tela. O \"diga Olá! por 2 segundos\" espera os 2 segundos, apaga o balão e só depois continua. Isso ajuda a montar diálogos entre atores.",
            },
            {
                id: "q9",
                prompt: "Para o ator desenhar um quadrado com a caneta, que número deve ficar no lugar do \"?\"",
                code: "abaixe a caneta\nrepita 4 vezes\n    mova 100 passos\n    gire ? graus\nfim",
                options: [
                    { id: "a", text: "45" },
                    { id: "b", text: "90" },
                    { id: "c", text: "180" },
                    { id: "d", text: "360" },
                ],
                correctOptionId: "b",
                explanation: "Um quadrado tem 4 cantos retos, de 90 graus. A cada volta, o ator anda um lado e gira 90 graus: 4 × 90 = 360 graus, uma volta completa. Os blocos de caneta vêm da extensão \"Caneta\", que você adiciona no botão do canto inferior esquerdo.",
            },
            {
                id: "q10",
                prompt: "Para que servem os blocos \"transmita mensagem1\" e \"quando receber mensagem1\"?",
                options: [
                    { id: "a", text: "Para enviar um e-mail" },
                    { id: "b", text: "Para mudar a cor do ator" },
                    { id: "c", text: "Para salvar o projeto" },
                    { id: "d", text: "Para um ator (ou o palco) avisar os outros que algo aconteceu, fazendo scripts começarem" },
                ],
                correctOptionId: "d",
                explanation: "São blocos de Eventos para os atores conversarem entre si. Quando um ator transmite \"mensagem1\", todos os scripts que começam com \"quando receber mensagem1\" rodam. Exemplo: o gato transmite \"fim de jogo\" e o palco troca para o cenário de Game Over.",
            },
        ],
    },
]

export default missions
