import { MissionContent } from "../../../src/engine/missions";

// Sétima leva de missões de quiz para as turmas de programação: Informática
// parte 3, Computação em Nuvem (partes 1 a 3), Linguagens de Programação
// (partes 1 e 2) e A História da Computação. 10 perguntas cada, todas
// comentadas, sem repetir as das levas anteriores. Nível mínimo 50 em todas
// (o professor ajusta depois no painel). Importar com:
//   npm run missions:import -- <e-mail do professor> scripts/missions/programacao-12-anos-parte-7.ts
const missions: MissionContent[] = [
    {
        title: "Informática parte 3",
        icon: "⌨️",
        difficulty: "medio",
        minLevel: 50,
        description: "Mais atalhos e truques: explorador de arquivos, bloquear a tela, renomear, gerenciador de tarefas, ZIP e e-mail",
        rewardXp: 250,
        rewardCoins: 100,
        rewardItem: {
            name: "Teclado Mecânico",
            icon: "⌨️",
            description: "Um teclado que faz clac-clac a cada atalho. Usar transforma cada tecla em XP.",
            rarity: "raro",
            value: 35,
            xp: 70,
        },
        kind: "quiz",
        questions: [
            {
                id: "q1",
                prompt: "No Windows, qual atalho abre o Explorador de Arquivos?",
                options: [
                    { id: "a", text: "Windows + E" },
                    { id: "b", text: "Ctrl + E" },
                    { id: "c", text: "Alt + F4" },
                    { id: "d", text: "Shift + Delete" },
                ],
                correctOptionId: "a",
                explanation: "Windows + E abre o Explorador de Arquivos, onde ficam suas pastas e documentos. O E vem de \"Explorer\" (explorador, em inglês).",
            },
            {
                id: "q2",
                prompt: "Você vai sair de perto do computador por um momento. Qual atalho bloqueia a tela na hora?",
                options: [
                    { id: "a", text: "Ctrl + B" },
                    { id: "b", text: "Windows + L" },
                    { id: "c", text: "Alt + Tab" },
                    { id: "d", text: "F5" },
                ],
                correctOptionId: "b",
                explanation: "Windows + L (de \"lock\", trancar) bloqueia o computador: ninguém mexe nas suas coisas sem a senha. Os programas continuam abertos, do jeito que estavam.",
            },
            {
                id: "q3",
                prompt: "Com um arquivo selecionado, qual tecla serve para renomeá-lo?",
                options: [
                    { id: "a", text: "F1" },
                    { id: "b", text: "F5" },
                    { id: "c", text: "F2" },
                    { id: "d", text: "Esc" },
                ],
                correctOptionId: "c",
                explanation: "O F2 renomeia o arquivo ou a pasta selecionada. Cuidado para não apagar a extensão (.sb3, .docx...), senão o computador não sabe qual programa abre o arquivo.",
            },
            {
                id: "q4",
                prompt: "No navegador, para que serve a tecla F5?",
                options: [
                    { id: "a", text: "Para fechar a aba" },
                    { id: "b", text: "Para recarregar (atualizar) a página" },
                    { id: "c", text: "Para abrir o histórico" },
                    { id: "d", text: "Para salvar a página" },
                ],
                correctOptionId: "b",
                explanation: "O F5 recarrega a página. Ajuda quando algo não carregou direito ou quando o site foi atualizado, como depois de um deploy da CodeGuilds.",
            },
            {
                id: "q5",
                prompt: "Um programa travou e não fecha. Qual atalho abre o Gerenciador de Tarefas para encerrá-lo?",
                options: [
                    { id: "a", text: "Ctrl + Shift + Esc" },
                    { id: "b", text: "Ctrl + C" },
                    { id: "c", text: "Windows + D" },
                    { id: "d", text: "Alt + Enter" },
                ],
                correctOptionId: "a",
                explanation: "Ctrl + Shift + Esc abre direto o Gerenciador de Tarefas. Lá você seleciona o programa travado e clica em \"Finalizar tarefa\". Ele também mostra quanto de memória e processador cada programa usa.",
            },
            {
                id: "q6",
                prompt: "Para que serve compactar arquivos num arquivo .zip?",
                options: [
                    { id: "a", text: "Para apagar os arquivos" },
                    { id: "b", text: "Para juntar vários arquivos num só e, muitas vezes, deixar tudo menor para enviar" },
                    { id: "c", text: "Para transformar fotos em vídeo" },
                    { id: "d", text: "Para deixar o computador mais rápido" },
                ],
                correctOptionId: "b",
                explanation: "O .zip junta arquivos e pastas num só arquivo e, muitas vezes, diminui o tamanho. No Windows, clique com o botão direito e escolha \"Compactar para arquivo ZIP\". Para abrir, use \"Extrair tudo\".",
            },
            {
                id: "q7",
                prompt: "No endereço de e-mail aluna@escola.com.br, o que vem depois do @?",
                options: [
                    { id: "a", text: "A senha" },
                    { id: "b", text: "O nome da pessoa" },
                    { id: "c", text: "O domínio, ou seja, o serviço ou a organização do e-mail" },
                    { id: "d", text: "O assunto da mensagem" },
                ],
                correctOptionId: "c",
                explanation: "Antes do @ fica o nome do usuário (aluna) e depois o domínio (escola.com.br), que diz onde a caixa de e-mail está. O @ se lê \"arroba\" e quer dizer \"em\" (at, em inglês).",
            },
            {
                id: "q8",
                prompt: "Ao enviar um e-mail, o que acontece com quem está no campo CCO (cópia oculta)?",
                options: [
                    { id: "a", text: "Recebe o e-mail, mas os outros destinatários não veem que essa pessoa recebeu" },
                    { id: "b", text: "Não recebe o e-mail" },
                    { id: "c", text: "Recebe só o assunto" },
                    { id: "d", text: "Recebe o e-mail duas vezes" },
                ],
                correctOptionId: "a",
                explanation: "No CC (com cópia), todos veem quem recebeu. No CCO (cópia oculta), o endereço fica escondido dos outros. É o jeito educado de mandar um e-mail para muita gente sem expor o e-mail de todos.",
            },
            {
                id: "q9",
                prompt: "O que a navegação anônima (aba anônima) do navegador realmente faz?",
                options: [
                    { id: "a", text: "Deixa você invisível na internet, para todo mundo" },
                    { id: "b", text: "Esconde o que você faz da escola e do provedor de internet" },
                    { id: "c", text: "Não guarda o histórico, os cookies e as senhas no seu computador depois que você fecha a aba" },
                    { id: "d", text: "Deixa a internet mais rápida" },
                ],
                correctOptionId: "c",
                explanation: "A aba anônima só evita que o SEU navegador guarde o histórico e os logins. Os sites que você visita, a rede da escola e o provedor de internet continuam vendo o acesso. Ela não deixa ninguém invisível.",
            },
            {
                id: "q10",
                prompt: "No navegador, qual atalho abre uma nova aba?",
                options: [
                    { id: "a", text: "Ctrl + W" },
                    { id: "b", text: "Ctrl + T" },
                    { id: "c", text: "Ctrl + H" },
                    { id: "d", text: "Ctrl + D" },
                ],
                correctOptionId: "b",
                explanation: "Ctrl + T abre uma nova aba e Ctrl + W fecha a aba atual. Fechou sem querer? Ctrl + Shift + T reabre a última aba fechada.",
            },
        ],
    },
    {
        title: "Computação em Nuvem",
        icon: "☁️",
        difficulty: "medio",
        minLevel: 50,
        description: "O que é a nuvem de verdade: data centers, serviços que você já usa e por que tudo depende da internet",
        rewardXp: 250,
        rewardCoins: 100,
        rewardItem: {
            name: "Nuvenzinha de Estimação",
            icon: "🌥️",
            description: "Uma nuvem pequena que te segue por qualquer computador. Usar transforma os dados guardados em XP.",
            rarity: "raro",
            value: 35,
            xp: 70,
        },
        kind: "quiz",
        questions: [
            {
                id: "q1",
                prompt: "Os arquivos que você guarda \"na nuvem\" ficam, de verdade, onde?",
                options: [
                    { id: "a", text: "Flutuando no céu" },
                    { id: "b", text: "Em computadores de verdade (servidores) dentro de grandes prédios chamados data centers" },
                    { id: "c", text: "Só no seu celular" },
                    { id: "d", text: "Em satélites no espaço" },
                ],
                correctOptionId: "b",
                explanation: "\"Nuvem\" é só um apelido. Os dados ficam em servidores, computadores potentes guardados em data centers, prédios enormes com refrigeração, energia reserva e segurança. Você acessa esses computadores pela internet.",
            },
            {
                id: "q2",
                prompt: "Qual destes é um serviço de armazenamento na nuvem?",
                options: [
                    { id: "a", text: "Bloco de Notas" },
                    { id: "b", text: "Calculadora" },
                    { id: "c", text: "Google Drive" },
                    { id: "d", text: "Paint" },
                ],
                correctOptionId: "c",
                explanation: "Google Drive, OneDrive, Dropbox e iCloud guardam seus arquivos em servidores dessas empresas. O Bloco de Notas, a Calculadora e o Paint são programas que rodam no seu próprio computador.",
            },
            {
                id: "q3",
                prompt: "Qual é uma das maiores vantagens de guardar um trabalho na nuvem?",
                options: [
                    { id: "a", text: "Ele nunca precisa de internet" },
                    { id: "b", text: "Ele fica mais bonito" },
                    { id: "c", text: "Dá para abrir de qualquer computador ou celular, entrando na sua conta" },
                    { id: "d", text: "Ninguém consegue apagar, nem você" },
                ],
                correctOptionId: "c",
                explanation: "Começou o trabalho na escola e quer terminar em casa? Na nuvem, basta entrar na sua conta em outro aparelho. E se o computador quebrar, o arquivo continua salvo.",
            },
            {
                id: "q4",
                prompt: "O que você precisa para acessar seus arquivos que estão só na nuvem?",
                options: [
                    { id: "a", text: "De um pendrive" },
                    { id: "b", text: "De conexão com a internet" },
                    { id: "c", text: "De uma impressora" },
                    { id: "d", text: "De nada, eles aparecem sozinhos" },
                ],
                correctOptionId: "b",
                explanation: "Como os arquivos ficam em servidores distantes, é a internet que leva os dados até você. Por isso muitos serviços deixam marcar arquivos para \"usar offline\", que ficam guardados também no aparelho.",
            },
            {
                id: "q5",
                prompt: "Quais destas empresas são grandes provedoras de computação em nuvem?",
                options: [
                    { id: "a", text: "Nintendo, Sega e Sony" },
                    { id: "b", text: "Amazon (AWS), Microsoft (Azure) e Google (Google Cloud)" },
                    { id: "c", text: "Netflix, Spotify e YouTube" },
                    { id: "d", text: "Só os bancos" },
                ],
                correctOptionId: "b",
                explanation: "AWS (Amazon Web Services), Microsoft Azure e Google Cloud são os maiores provedores: eles alugam servidores para outras empresas. Muitos apps que você usa rodam nos computadores deles.",
            },
            {
                id: "q6",
                prompt: "Quando você assiste a um filme num streaming, como a Netflix, de onde vem o vídeo?",
                options: [
                    { id: "a", text: "De um DVD dentro da TV" },
                    { id: "b", text: "De servidores na nuvem, que mandam o vídeo pela internet enquanto você assiste" },
                    { id: "c", text: "Ele já vem gravado no celular" },
                    { id: "d", text: "Da antena da TV" },
                ],
                correctOptionId: "b",
                explanation: "No streaming, o vídeo fica em servidores e chega em pedacinhos pela internet, enquanto você assiste. Por isso, com internet lenta, a qualidade cai ou o vídeo para pra carregar.",
            },
            {
                id: "q7",
                prompt: "Muitos jogos têm o \"salvamento na nuvem\" (cloud save). Para que serve?",
                options: [
                    { id: "a", text: "Para o jogo rodar sem eletricidade" },
                    { id: "b", text: "Para o progresso ficar guardado online e continuar em outro aparelho" },
                    { id: "c", text: "Para o jogo ficar com gráficos melhores" },
                    { id: "d", text: "Para apagar o progresso todo dia" },
                ],
                correctOptionId: "b",
                explanation: "Com o cloud save, seu progresso fica num servidor. Trocou de console ou de computador? É só entrar na conta. A CodeGuilds faz o mesmo: seu XP, moedas e itens ficam no servidor, não no navegador.",
            },
            {
                id: "q8",
                prompt: "O que é um data center?",
                options: [
                    { id: "a", text: "Um prédio cheio de servidores, com refrigeração, energia reserva e segurança, que funciona 24 horas por dia" },
                    { id: "b", text: "Uma loja de computadores" },
                    { id: "c", text: "Um tipo de pendrive" },
                    { id: "d", text: "O nome de um aplicativo" },
                ],
                correctOptionId: "a",
                explanation: "Um data center abriga milhares de servidores em fileiras de armários (racks). Eles esquentam muito, então a refrigeração é essencial, e têm geradores para não desligar nem quando falta luz.",
            },
            {
                id: "q9",
                prompt: "Você editou um arquivo no computador e ele apareceu atualizado no celular sozinho. Como se chama isso?",
                options: [
                    { id: "a", text: "Formatação" },
                    { id: "b", text: "Sincronização" },
                    { id: "c", text: "Compactação" },
                    { id: "d", text: "Impressão" },
                ],
                correctOptionId: "b",
                explanation: "Sincronizar é manter a mesma versão do arquivo em todos os aparelhos: a mudança vai para a nuvem e de lá para os outros dispositivos conectados à sua conta.",
            },
            {
                id: "q10",
                prompt: "Se o seu computador quebrar, o que acontece com os arquivos que estavam salvos na nuvem?",
                options: [
                    { id: "a", text: "Somem junto com o computador" },
                    { id: "b", text: "Continuam guardados nos servidores, e você acessa de outro aparelho" },
                    { id: "c", text: "Ficam presos no computador quebrado" },
                    { id: "d", text: "Viram vírus" },
                ],
                correctOptionId: "b",
                explanation: "Os arquivos da nuvem não dependem do seu aparelho: eles estão nos servidores. Por isso a nuvem é uma ótima forma de backup, a cópia de segurança dos seus arquivos.",
            },
        ],
    },
    {
        title: "Computação em Nuvem parte 2",
        icon: "🌐",
        difficulty: "medio",
        minLevel: 50,
        description: "Como a nuvem funciona por dentro: SaaS, escalabilidade, redundância, regiões, jogos na nuvem e a própria CodeGuilds",
        rewardXp: 250,
        rewardCoins: 100,
        rewardItem: {
            name: "Servidor de Bolso",
            icon: "🖥️",
            description: "Um servidor tão pequeno que cabe no bolso, mas aguenta uma guilda inteira. Usar transforma o processamento em XP.",
            rarity: "raro",
            value: 35,
            xp: 70,
        },
        kind: "quiz",
        questions: [
            {
                id: "q1",
                prompt: "O Gmail e o Google Docs funcionam direto no navegador, sem instalar nada. Que tipo de serviço de nuvem eles são?",
                options: [
                    { id: "a", text: "SaaS (Software como Serviço): um programa pronto, usado pela internet" },
                    { id: "b", text: "Hardware" },
                    { id: "c", text: "Um sistema operacional" },
                    { id: "d", text: "Um vírus" },
                ],
                correctOptionId: "a",
                explanation: "SaaS (Software as a Service) é o software que você usa pronto, pelo navegador ou app: Gmail, Google Docs, Canva. Ninguém precisa instalar nem atualizar nada: o programa roda nos servidores da empresa.",
            },
            {
                id: "q2",
                prompt: "Numa Black Friday, uma loja online recebe 10 vezes mais visitas. Como a nuvem ajuda?",
                options: [
                    { id: "a", text: "Ela desliga o site para descansar" },
                    { id: "b", text: "Ela permite usar mais servidores rapidinho nos dias de pico e menos depois (escalabilidade)" },
                    { id: "c", text: "Ela deixa entrar só 10 pessoas" },
                    { id: "d", text: "Não ajuda em nada" },
                ],
                correctOptionId: "b",
                explanation: "Escalabilidade é crescer ou diminuir conforme a necessidade. Na nuvem, dá pra ligar mais servidores em minutos quando o movimento aumenta e desligar quando acaba, pagando só pelo que usou.",
            },
            {
                id: "q3",
                prompt: "Por que muitas empresas preferem alugar servidores na nuvem em vez de comprar os próprios?",
                options: [
                    { id: "a", text: "Porque a nuvem é sempre grátis" },
                    { id: "b", text: "Porque pagam pelo que usam e não precisam cuidar do prédio, da energia e da manutenção dos computadores" },
                    { id: "c", text: "Porque é proibido ter servidor próprio" },
                    { id: "d", text: "Porque a nuvem não usa internet" },
                ],
                correctOptionId: "b",
                explanation: "Ter servidor próprio exige comprar máquinas, refrigeração, energia e uma equipe para cuidar de tudo. Na nuvem, a empresa aluga a capacidade de que precisa e paga como uma conta de luz: pelo consumo.",
            },
            {
                id: "q4",
                prompt: "Se um servidor de um data center quebra, por que o serviço costuma continuar funcionando?",
                options: [
                    { id: "a", text: "Porque existem cópias dos dados e outros servidores prontos para assumir (redundância)" },
                    { id: "b", text: "Porque servidores nunca quebram" },
                    { id: "c", text: "Porque o serviço vai para o celular do usuário" },
                    { id: "d", text: "Por sorte" },
                ],
                correctOptionId: "a",
                explanation: "Redundância é ter peças e cópias de sobra. Os dados ficam guardados em mais de um lugar e, se um servidor falha, outro assume. É por isso que serviços grandes raramente saem do ar.",
            },
            {
                id: "q5",
                prompt: "A própria CodeGuilds roda na nuvem. Onde ficam o site, o servidor (a API) e o banco de dados dela?",
                options: [
                    { id: "a", text: "Num computador na casa do professor" },
                    { id: "b", text: "Em serviços de nuvem: o site na Vercel, a API no Render e o banco de dados no Neon" },
                    { id: "c", text: "No celular de cada aluno" },
                    { id: "d", text: "Num pendrive" },
                ],
                correctOptionId: "b",
                explanation: "A CodeGuilds usa três serviços de nuvem: a Vercel entrega as páginas do site, o Render roda a API (que confere as missões e guarda o progresso) e o Neon guarda o banco de dados. Os arquivos das entregas ficam no Supabase.",
            },
            {
                id: "q6",
                prompt: "Por que um provedor de nuvem tem data centers em vários países e regiões, como em São Paulo?",
                options: [
                    { id: "a", text: "Para os dados viajarem menos e o serviço responder mais rápido para quem está perto" },
                    { id: "b", text: "Só para ter mais prédios" },
                    { id: "c", text: "Porque cada país tem uma internet diferente que não se conecta" },
                    { id: "d", text: "Para gastar mais energia" },
                ],
                correctOptionId: "a",
                explanation: "Os dados viajam por cabos, e distância gera atraso, a chamada latência. Um servidor em São Paulo responde mais rápido para quem está no Brasil do que um do outro lado do mundo.",
            },
            {
                id: "q7",
                prompt: "O que é latência?",
                options: [
                    { id: "a", text: "O tamanho de um arquivo" },
                    { id: "b", text: "O tempo que os dados levam para ir até o servidor e voltar" },
                    { id: "c", text: "A cor da tela" },
                    { id: "d", text: "A quantidade de servidores" },
                ],
                correctOptionId: "b",
                explanation: "Latência é o atraso da comunicação, medido em milissegundos (o famoso \"ping\" dos jogos online). Ping alto deixa o jogo travando, mesmo com uma internet rápida para downloads.",
            },
            {
                id: "q8",
                prompt: "Nos serviços de jogos na nuvem (cloud gaming), onde o jogo realmente roda?",
                options: [
                    { id: "a", text: "No controle" },
                    { id: "b", text: "Num computador potente no data center, que manda a imagem do jogo como um vídeo para o seu aparelho" },
                    { id: "c", text: "Num disco dentro da TV" },
                    { id: "d", text: "No roteador da sua casa" },
                ],
                correctOptionId: "b",
                explanation: "No cloud gaming, o jogo roda num servidor e você recebe o vídeo da partida, mandando de volta os comandos do controle. Por isso dá pra jogar jogos pesados num aparelho simples, mas a internet precisa ser boa e com latência baixa.",
            },
            {
                id: "q9",
                prompt: "Qual é a diferença entre nuvem pública e nuvem privada?",
                options: [
                    { id: "a", text: "Na pública, a mesma estrutura do provedor atende muitos clientes; na privada, os servidores são só de uma organização" },
                    { id: "b", text: "A pública é grátis e a privada é paga, sempre" },
                    { id: "c", text: "Na nuvem pública todo mundo vê os seus arquivos" },
                    { id: "d", text: "Não existe diferença" },
                ],
                correctOptionId: "a",
                explanation: "Na nuvem pública (como AWS ou Google Cloud), vários clientes dividem a mesma estrutura, mas cada um só acessa os próprios dados. Na privada, uma empresa ou governo tem servidores só seus, para mais controle.",
            },
            {
                id: "q10",
                prompt: "Os data centers gastam muita energia. Por que isso importa para os ODS?",
                options: [
                    { id: "a", text: "Não importa" },
                    { id: "b", text: "Porque usar energia limpa e economizar energia nos data centers ajuda a combater a mudança do clima" },
                    { id: "c", text: "Porque data centers produzem comida" },
                    { id: "d", text: "Porque data centers ficam no oceano" },
                ],
                correctOptionId: "b",
                explanation: "Data centers usam muita eletricidade para os servidores e a refrigeração. Usar energia solar e eólica e equipamentos eficientes se liga ao ODS 7 (energia limpa) e ao ODS 13 (ação contra a mudança do clima).",
            },
        ],
    },
    {
        title: "Computação em Nuvem parte 3",
        icon: "🔐",
        difficulty: "medio",
        minLevel: 50,
        description: "Segurança e bom uso da nuvem: verificação em duas etapas, compartilhamento, criptografia, espaço e privacidade",
        rewardXp: 250,
        rewardCoins: 100,
        rewardItem: {
            name: "Cadeado da Nuvem",
            icon: "🔐",
            description: "Um cadeado com chave dupla que protege qualquer arquivo. Usar transforma a proteção em XP.",
            rarity: "raro",
            value: 35,
            xp: 70,
        },
        kind: "quiz",
        questions: [
            {
                id: "q1",
                prompt: "O que é a verificação em duas etapas (2FA) numa conta da nuvem?",
                options: [
                    { id: "a", text: "Digitar a senha duas vezes" },
                    { id: "b", text: "Além da senha, confirmar com um segundo fator, como um código no celular" },
                    { id: "c", text: "Ter duas contas iguais" },
                    { id: "d", text: "Entrar na conta duas vezes por dia" },
                ],
                correctOptionId: "b",
                explanation: "Na verificação em duas etapas, mesmo que alguém descubra sua senha, ainda precisa do segundo fator (um código no celular ou um app autenticador). É uma das proteções mais eficientes para contas.",
            },
            {
                id: "q2",
                prompt: "Você quer mostrar um trabalho para a turma sem que ninguém o altere. Como compartilhar o link?",
                options: [
                    { id: "a", text: "Com permissão de \"editor\" para todos" },
                    { id: "b", text: "Com permissão de \"leitor\" (só visualizar)" },
                    { id: "c", text: "Mandando sua senha" },
                    { id: "d", text: "Não dá para compartilhar" },
                ],
                correctOptionId: "b",
                explanation: "Os serviços de nuvem deixam escolher o que cada pessoa pode fazer: só ver (leitor), comentar ou editar. Para mostrar sem risco de mudanças, use \"leitor\". E nunca compartilhe sua senha.",
            },
            {
                id: "q3",
                prompt: "O que a criptografia faz com os seus dados na nuvem?",
                options: [
                    { id: "a", text: "Apaga os dados" },
                    { id: "b", text: "Deixa os arquivos coloridos" },
                    { id: "c", text: "Embaralha os dados, para que só quem tem a chave certa consiga ler" },
                    { id: "d", text: "Deixa os arquivos maiores para ninguém baixar" },
                ],
                correctOptionId: "c",
                explanation: "Criptografar é transformar os dados num código embaralhado. Mesmo que alguém intercepte, sem a chave não entende nada. É o que protege seus dados no caminho (https) e guardados nos servidores.",
            },
            {
                id: "q4",
                prompt: "Os planos gratuitos dos serviços de nuvem têm um limite. Qual?",
                options: [
                    { id: "a", text: "Só funcionam aos domingos" },
                    { id: "b", text: "Só aceitam fotos" },
                    { id: "c", text: "Um espaço de armazenamento limitado (o Google, por exemplo, dá 15 GB grátis)" },
                    { id: "d", text: "Não têm limite nenhum" },
                ],
                correctOptionId: "c",
                explanation: "Cada serviço dá um espaço grátis: o Google dá 15 GB, divididos entre Drive, Gmail e Fotos, e o OneDrive dá 5 GB. Passou disso? É preciso apagar arquivos ou pagar por mais espaço.",
            },
            {
                id: "q5",
                prompt: "Você apagou um arquivo do Google Drive sem querer. O que fazer primeiro?",
                options: [
                    { id: "a", text: "Nada, ele sumiu para sempre na hora" },
                    { id: "b", text: "Procurar na Lixeira do próprio Drive, onde ele fica por um tempo antes de ser apagado de vez" },
                    { id: "c", text: "Formatar o computador" },
                    { id: "d", text: "Criar outra conta" },
                ],
                correctOptionId: "b",
                explanation: "Assim como o computador, os serviços de nuvem têm uma lixeira: o arquivo apagado fica lá por um tempo (no Google Drive, 30 dias) e pode ser restaurado. Depois disso, é apagado de verdade.",
            },
            {
                id: "q6",
                prompt: "Os assistentes de inteligência artificial que respondem perguntas no celular fazem os cálculos onde, na maioria das vezes?",
                options: [
                    { id: "a", text: "Em servidores potentes na nuvem" },
                    { id: "b", text: "Só na bateria do celular" },
                    { id: "c", text: "No fone de ouvido" },
                    { id: "d", text: "Num satélite" },
                ],
                correctOptionId: "a",
                explanation: "As inteligências artificiais grandes precisam de muitos computadores com placas de vídeo (GPUs) trabalhando juntos. Por isso, na maioria das vezes, a pergunta vai pela internet até um data center, e a resposta volta para o seu aparelho.",
            },
            {
                id: "q7",
                prompt: "Você usou sua conta da nuvem num computador da escola. O que fazer antes de ir embora?",
                options: [
                    { id: "a", text: "Deixar a conta aberta para a próxima aula" },
                    { id: "b", text: "Sair da conta e não salvar a senha no navegador" },
                    { id: "c", text: "Anotar a senha num papel do lado do computador" },
                    { id: "d", text: "Desligar o monitor" },
                ],
                correctOptionId: "b",
                explanation: "Num computador compartilhado, sempre saia da conta (\"Sair\" ou \"Logout\") e não deixe o navegador salvar sua senha. Senão, quem usar o computador depois entra nos seus arquivos.",
            },
            {
                id: "q8",
                prompt: "Por que é importante ler o que um aplicativo pede de permissão antes de conectar à sua conta da nuvem?",
                options: [
                    { id: "a", text: "Porque o app pode ganhar acesso aos seus arquivos, e-mails ou contatos" },
                    { id: "b", text: "Porque o texto é divertido" },
                    { id: "c", text: "Porque o app vai ficar mais rápido" },
                    { id: "d", text: "Não é importante" },
                ],
                correctOptionId: "a",
                explanation: "Ao clicar em \"Entrar com o Google\" ou parecido, o app pede permissões. Algumas são simples (seu nome), outras são grandes (ler todos os seus arquivos). Na dúvida, não autorize e peça ajuda a um adulto.",
            },
            {
                id: "q9",
                prompt: "Dois colegas editaram o mesmo arquivo da nuvem ao mesmo tempo, sem internet, e depois reconectaram. O que pode acontecer?",
                options: [
                    { id: "a", text: "Os computadores explodem" },
                    { id: "b", text: "Um conflito de sincronização: o serviço pode criar duas versões do arquivo para vocês escolherem" },
                    { id: "c", text: "O arquivo vira um vírus" },
                    { id: "d", text: "Nada acontece, nunca" },
                ],
                correctOptionId: "b",
                explanation: "Quando duas mudanças diferentes chegam ao mesmo arquivo, o serviço não sabe qual vale e cria uma \"cópia em conflito\". Ferramentas como o Google Docs evitam isso juntando as edições em tempo real, quando todos estão online.",
            },
            {
                id: "q10",
                prompt: "Qual é uma boa prática para não perder um trabalho importante?",
                options: [
                    { id: "a", text: "Guardar só numa pasta do computador" },
                    { id: "b", text: "Ter mais de uma cópia: por exemplo, no computador e na nuvem" },
                    { id: "c", text: "Nunca salvar" },
                    { id: "d", text: "Imprimir e apagar o arquivo" },
                ],
                correctOptionId: "b",
                explanation: "Quem tem uma cópia só pode perder tudo de uma vez. Ter cópias em lugares diferentes, como no computador, num pendrive e na nuvem, é a base de um bom backup.",
            },
        ],
    },
    {
        title: "Linguagens de Programação",
        icon: "🗣️",
        difficulty: "medio",
        minLevel: 50,
        description: "Cada linguagem tem seu lugar: sites, apps, jogos, inteligência artificial, bancos de dados e mais",
        rewardXp: 250,
        rewardCoins: 100,
        rewardItem: {
            name: "Dicionário Poliglota",
            icon: "📚",
            description: "Um dicionário que traduz entre todas as linguagens de programação. Usar transforma o vocabulário em XP.",
            rarity: "raro",
            value: 35,
            xp: 70,
        },
        kind: "quiz",
        questions: [
            {
                id: "q1",
                prompt: "Por que existem tantas linguagens de programação diferentes?",
                options: [
                    { id: "a", text: "Porque cada uma foi criada para resolver melhor certos tipos de problema" },
                    { id: "b", text: "Porque os computadores só entendem uma por dia" },
                    { id: "c", text: "Por acaso, todas fazem exatamente a mesma coisa do mesmo jeito" },
                    { id: "d", text: "Porque é proibido usar a mesma linguagem duas vezes" },
                ],
                correctOptionId: "a",
                explanation: "Assim como existem ferramentas diferentes para cada trabalho, cada linguagem tem seus pontos fortes: velocidade, facilidade, rodar no navegador, criar apps... A lógica de programação, porém, é parecida em todas.",
            },
            {
                id: "q2",
                prompt: "Qual linguagem roda direto dentro do navegador e dá interatividade às páginas?",
                options: [
                    { id: "a", text: "SQL" },
                    { id: "b", text: "JavaScript" },
                    { id: "c", text: "Swift" },
                    { id: "d", text: "Assembly" },
                ],
                correctOptionId: "b",
                explanation: "O JavaScript é a linguagem dos navegadores: todos eles sabem rodá-la. Junto com o HTML (estrutura) e o CSS (aparência), forma a base de todos os sites.",
            },
            {
                id: "q3",
                prompt: "Qual linguagem a Apple criou para fazer aplicativos de iPhone?",
                options: [
                    { id: "a", text: "Swift" },
                    { id: "b", text: "Lua" },
                    { id: "c", text: "Python" },
                    { id: "d", text: "HTML" },
                ],
                correctOptionId: "a",
                explanation: "A Apple lançou o Swift em 2014 para criar apps de iPhone, iPad e Mac. No Android, a linguagem recomendada pelo Google é o Kotlin.",
            },
            {
                id: "q4",
                prompt: "Qual linguagem o Google recomenda como principal para criar apps de Android?",
                options: [
                    { id: "a", text: "Kotlin" },
                    { id: "b", text: "Swift" },
                    { id: "c", text: "CSS" },
                    { id: "d", text: "SQL" },
                ],
                correctOptionId: "a",
                explanation: "Desde 2019, o Google diz que o Android é \"Kotlin first\": o Kotlin é a linguagem principal recomendada para apps Android. Ele roda na mesma máquina virtual do Java (a JVM) e conversa bem com código Java.",
            },
            {
                id: "q5",
                prompt: "Qual linguagem é usada para buscar e organizar informações em bancos de dados?",
                code: "SELECT nome FROM alunos WHERE nivel > 10;",
                options: [
                    { id: "a", text: "SQL" },
                    { id: "b", text: "HTML" },
                    { id: "c", text: "Scratch" },
                    { id: "d", text: "Lua" },
                ],
                correctOptionId: "a",
                explanation: "O SQL (Structured Query Language) conversa com bancos de dados. A linha acima pede o nome dos alunos com nível maior que 10. A API da CodeGuilds usa SQL para guardar e buscar o progresso de vocês!",
            },
            {
                id: "q6",
                prompt: "Muitos motores de jogos profissionais, como a Unreal Engine, são programados principalmente em qual linguagem?",
                options: [
                    { id: "a", text: "C++" },
                    { id: "b", text: "HTML" },
                    { id: "c", text: "SQL" },
                    { id: "d", text: "CSS" },
                ],
                correctOptionId: "a",
                explanation: "O C++ é muito rápido e dá controle sobre a memória do computador, por isso é usado em motores de jogos, como a Unreal, e em programas pesados. Em compensação, é bem mais difícil de aprender.",
            },
            {
                id: "q7",
                prompt: "Por que o HTML não é considerado uma linguagem de programação?",
                options: [
                    { id: "a", text: "Porque ele é muito antigo" },
                    { id: "b", text: "Porque ele é uma linguagem de marcação: descreve a estrutura da página, mas não tem condições, laços nem contas" },
                    { id: "c", text: "Porque só funciona no celular" },
                    { id: "d", text: "Porque é escrito em português" },
                ],
                correctOptionId: "b",
                explanation: "O HTML marca o que é cada parte da página (título, parágrafo, imagem), mas não toma decisões nem repete ações. Para isso, entra o JavaScript. O CSS também não é linguagem de programação: é de estilo.",
            },
            {
                id: "q8",
                prompt: "Scratch e MIT App Inventor são linguagens de que tipo?",
                options: [
                    { id: "a", text: "Linguagens de marcação" },
                    { id: "b", text: "Linguagens visuais, de blocos de encaixar" },
                    { id: "c", text: "Linguagens de banco de dados" },
                    { id: "d", text: "Linguagens de máquina" },
                ],
                correctOptionId: "b",
                explanation: "Nas linguagens visuais, você monta o programa encaixando blocos, sem se preocupar com vírgulas e parênteses. É um ótimo jeito de aprender lógica. Depois, a mesma lógica vale para Python, JavaScript e Lua.",
            },
            {
                id: "q9",
                prompt: "Qual linguagem é muito usada em inteligência artificial e análise de dados?",
                options: [
                    { id: "a", text: "Python" },
                    { id: "b", text: "HTML" },
                    { id: "c", text: "CSS" },
                    { id: "d", text: "Assembly" },
                ],
                correctOptionId: "a",
                explanation: "O Python tem bibliotecas prontas para IA e dados (como TensorFlow, PyTorch e pandas) e é fácil de ler. Por isso virou a linguagem preferida de cientistas e de quem trabalha com inteligência artificial.",
            },
            {
                id: "q10",
                prompt: "O que é uma linguagem de \"baixo nível\", como o Assembly?",
                options: [
                    { id: "a", text: "Uma linguagem ruim" },
                    { id: "b", text: "Uma linguagem só para crianças" },
                    { id: "c", text: "Uma linguagem bem próxima das instruções do processador, mais difícil de ler para pessoas" },
                    { id: "d", text: "Uma linguagem que roda debaixo da mesa" },
                ],
                correctOptionId: "c",
                explanation: "\"Baixo nível\" quer dizer perto da máquina: o Assembly dá ordens quase diretas ao processador. Linguagens de \"alto nível\", como Python e JavaScript, são mais próximas da forma como as pessoas pensam e escrevem.",
            },
        ],
    },
    {
        title: "Linguagens de Programação parte 2",
        icon: "🧩",
        difficulty: "medio",
        minLevel: 50,
        description: "Como as linguagens funcionam: compiladores, interpretadores, erros, comentários, nomes de variáveis e ferramentas",
        rewardXp: 250,
        rewardCoins: 100,
        rewardItem: {
            name: "Tradutor Universal",
            icon: "🗺️",
            description: "O mapa que mostra como transformar qualquer código em instruções da máquina. Usar transforma a tradução em XP.",
            rarity: "raro",
            value: 35,
            xp: 70,
        },
        kind: "quiz",
        questions: [
            {
                id: "q1",
                prompt: "O que faz um compilador?",
                options: [
                    { id: "a", text: "Traduz o programa inteiro para a linguagem da máquina antes de ele rodar" },
                    { id: "b", text: "Desenha a interface do programa" },
                    { id: "c", text: "Apaga os erros sozinho" },
                    { id: "d", text: "Conecta o computador à internet" },
                ],
                correctOptionId: "a",
                explanation: "O compilador lê todo o código e gera um programa pronto para a máquina, que depois roda rápido. Linguagens como C, C++ e Swift são compiladas.",
            },
            {
                id: "q2",
                prompt: "E o interpretador, como trabalha?",
                options: [
                    { id: "a", text: "Ele só funciona no celular" },
                    { id: "b", text: "Ele lê e executa o programa aos poucos, enquanto roda, sem gerar antes um programa separado" },
                    { id: "c", text: "Ele traduz o programa para outro idioma, como o inglês" },
                    { id: "d", text: "Ele não executa nada" },
                ],
                correctOptionId: "b",
                explanation: "O interpretador executa o código conforme vai lendo. Python, JavaScript e Lua costumam ser interpretados: é fácil testar mudanças na hora. (Na prática, muitos usam truques que misturam as duas ideias para ficar mais rápidos.)",
            },
            {
                id: "q3",
                prompt: "O que é um erro de sintaxe?",
                code: "print(\"Olá\"",
                options: [
                    { id: "a", text: "Um erro na lógica do jogo" },
                    { id: "b", text: "Um erro de digitação ou de \"gramática\" da linguagem, como esquecer de fechar um parêntese" },
                    { id: "c", text: "Um vírus" },
                    { id: "d", text: "Quando o computador está desligado" },
                ],
                correctOptionId: "b",
                explanation: "Sintaxe é a \"gramática\" da linguagem. Faltou fechar o parêntese, esqueceu uma aspa ou um ponto e vírgula (em Java)? O programa nem começa a rodar. A mensagem de erro costuma dizer a linha onde está o problema.",
            },
            {
                id: "q4",
                prompt: "Qual é o primeiro programa tradicional que muita gente escreve ao aprender uma linguagem nova?",
                options: [
                    { id: "a", text: "Um jogo de corrida 3D" },
                    { id: "b", text: "Um programa que mostra \"Hello, World!\" (Olá, Mundo!) na tela" },
                    { id: "c", text: "Um sistema operacional" },
                    { id: "d", text: "Um banco de dados" },
                ],
                correctOptionId: "b",
                explanation: "O \"Hello, World!\" é uma tradição que ficou famosa em um livro da linguagem C, nos anos 1970. Ele mostra o jeito mais simples de exibir uma mensagem: print(\"Hello, World!\") em Python, console.log em JavaScript.",
            },
            {
                id: "q5",
                prompt: "Cada linguagem tem seu jeito de escrever comentários. Qual combinação está correta?",
                options: [
                    { id: "a", text: "Python: //, JavaScript: #, Lua: --" },
                    { id: "b", text: "Python: #, JavaScript: //, Lua: --" },
                    { id: "c", text: "Python: --, JavaScript: #, Lua: //" },
                    { id: "d", text: "Todas usam o mesmo símbolo" },
                ],
                correctOptionId: "b",
                explanation: "Python usa #, JavaScript e Java usam //, e Lua usa --. O comentário é ignorado pelo computador e serve para explicar o código para pessoas, inclusive para você mesmo no futuro.",
            },
            {
                id: "q6",
                prompt: "Qual destes nomes de variável é válido na maioria das linguagens?",
                options: [
                    { id: "a", text: "1pontos" },
                    { id: "b", text: "pontos do jogador" },
                    { id: "c", text: "pontosDoJogador" },
                    { id: "d", text: "pontos-jogador!" },
                ],
                correctOptionId: "c",
                explanation: "Nomes de variáveis não podem ter espaços nem a maioria dos símbolos, e não podem começar com número. Por isso juntamos as palavras: pontosDoJogador (camelCase, comum em JavaScript e Java) ou pontos_do_jogador (snake_case, comum em Python).",
            },
            {
                id: "q7",
                prompt: "O que é uma IDE, como o VS Code?",
                options: [
                    { id: "a", text: "Um programa feito para escrever código, com cores, sugestões e ferramentas para achar erros" },
                    { id: "b", text: "Um tipo de vírus" },
                    { id: "c", text: "Um navegador de internet" },
                    { id: "d", text: "Um jogo de programação" },
                ],
                correctOptionId: "a",
                explanation: "IDE quer dizer Ambiente de Desenvolvimento Integrado. Ela colore o código, sugere comandos, mostra erros e ajuda a rodar e testar o programa. O VS Code é um dos editores mais usados do mundo.",
            },
            {
                id: "q8",
                prompt: "O Portugol (ou VisuAlg) é muito usado em escolas brasileiras. O que ele tem de especial?",
                code: "se idade >= 12 entao\n    escreva(\"Pode jogar!\")\nfimse",
                options: [
                    { id: "a", text: "Os comandos são em português, para aprender lógica sem se preocupar com o inglês" },
                    { id: "b", text: "Ele só funciona em Portugal" },
                    { id: "c", text: "Ele é usado para criar jogos 3D profissionais" },
                    { id: "d", text: "Ele é o idioma dos computadores" },
                ],
                correctOptionId: "a",
                explanation: "O Portugol usa palavras em português (se, entao, escreva) para ensinar a lógica de programação. Depois, basta trocar pelas palavras em inglês: se vira if, escreva vira print.",
            },
            {
                id: "q9",
                prompt: "O que é um software de código aberto (open source)?",
                options: [
                    { id: "a", text: "Um programa cujo código-fonte qualquer pessoa pode ver, estudar e, em geral, ajudar a melhorar" },
                    { id: "b", text: "Um programa que fica aberto o tempo todo" },
                    { id: "c", text: "Um programa sem senha" },
                    { id: "d", text: "Um programa que não funciona" },
                ],
                correctOptionId: "a",
                explanation: "No código aberto, o código-fonte é público. O Linux, o Firefox, o Python e a própria linguagem Lua são exemplos. Programadores do mundo todo podem estudar e contribuir.",
            },
            {
                id: "q10",
                prompt: "Você aprendeu Scratch. O que você aproveita ao começar a aprender Python?",
                options: [
                    { id: "a", text: "Nada, é tudo diferente" },
                    { id: "b", text: "A lógica: sequência, condições, repetições e variáveis funcionam do mesmo jeito; só muda a forma de escrever" },
                    { id: "c", text: "Só os desenhos dos personagens" },
                    { id: "d", text: "Os sons do Scratch" },
                ],
                correctOptionId: "b",
                explanation: "O \"se ... então\" do Scratch vira if, o \"repita\" vira for, e as variáveis continuam sendo variáveis. A lógica que você aprendeu vale em qualquer linguagem. Cada linguagem nova fica mais fácil que a anterior!",
            },
        ],
    },
    {
        title: "A História da Computação",
        icon: "🏛️",
        difficulty: "medio",
        minLevel: 50,
        description: "Do ábaco ao smartphone: as invenções e as pessoas que criaram a computação",
        rewardXp: 250,
        rewardCoins: 100,
        rewardItem: {
            name: "Ábaco Ancestral",
            icon: "🧮",
            description: "Um ábaco de milhares de anos, o avô de todos os computadores. Usar transforma a história em XP.",
            rarity: "raro",
            value: 35,
            xp: 70,
        },
        kind: "quiz",
        questions: [
            {
                id: "q1",
                prompt: "Qual destes é um dos instrumentos de cálculo mais antigos, usado há milhares de anos?",
                options: [
                    { id: "a", text: "A calculadora de bolso" },
                    { id: "b", text: "O ábaco" },
                    { id: "c", text: "O computador pessoal" },
                    { id: "d", text: "O smartphone" },
                ],
                correctOptionId: "b",
                explanation: "O ábaco, com contas que deslizam em varetas, é usado há milhares de anos em várias civilizações para fazer contas. Ele mostra que a ideia de \"uma ferramenta para calcular\" é muito antiga.",
            },
            {
                id: "q2",
                prompt: "Em 1642, o francês Blaise Pascal criou uma máquina que fazia somas e subtrações com engrenagens. Como ela se chamava?",
                options: [
                    { id: "a", text: "Pascalina" },
                    { id: "b", text: "ENIAC" },
                    { id: "c", text: "Ábaco" },
                    { id: "d", text: "Máquina de Turing" },
                ],
                correctOptionId: "a",
                explanation: "A Pascalina foi uma das primeiras calculadoras mecânicas: Pascal a criou ainda jovem, para ajudar o pai, que era cobrador de impostos, com as contas. Em homenagem a ele, existe até uma linguagem de programação chamada Pascal.",
            },
            {
                id: "q3",
                prompt: "No século XIX, quem projetou a Máquina Analítica, considerada a ideia do primeiro computador de uso geral?",
                options: [
                    { id: "a", text: "Thomas Edison" },
                    { id: "b", text: "Charles Babbage" },
                    { id: "c", text: "Isaac Newton" },
                    { id: "d", text: "Albert Einstein" },
                ],
                correctOptionId: "b",
                explanation: "O inglês Charles Babbage projetou a Máquina Analítica, que poderia ser programada com cartões perfurados. Ela nunca foi totalmente construída em sua época, mas já tinha as partes de um computador moderno: memória, processamento, entrada e saída.",
            },
            {
                id: "q4",
                prompt: "Quem é considerado o \"pai da ciência da computação\" e ajudou a decifrar as mensagens secretas da máquina Enigma na Segunda Guerra Mundial?",
                options: [
                    { id: "a", text: "Alan Turing" },
                    { id: "b", text: "Bill Gates" },
                    { id: "c", text: "Steve Jobs" },
                    { id: "d", text: "Galileu Galilei" },
                ],
                correctOptionId: "a",
                explanation: "O matemático inglês Alan Turing criou a ideia da \"máquina de Turing\", um modelo do que qualquer computador consegue calcular, e liderou trabalhos para quebrar o código Enigma, ajudando a encurtar a guerra.",
            },
            {
                id: "q5",
                prompt: "O ENIAC, de 1946, foi um dos primeiros computadores eletrônicos. Como ele era?",
                options: [
                    { id: "a", text: "Cabia no bolso" },
                    { id: "b", text: "Era do tamanho de um notebook" },
                    { id: "c", text: "Era gigante: ocupava uma sala inteira e pesava cerca de 30 toneladas" },
                    { id: "d", text: "Funcionava sem eletricidade" },
                ],
                correctOptionId: "c",
                explanation: "O ENIAC tinha milhares de válvulas, ocupava uma sala enorme e pesava cerca de 30 toneladas. Hoje, um celular é milhões de vezes mais rápido e cabe na mão.",
            },
            {
                id: "q6",
                prompt: "Que invenção de 1947 substituiu as válvulas e permitiu computadores cada vez menores e mais rápidos?",
                options: [
                    { id: "a", text: "O mouse" },
                    { id: "b", text: "O transistor" },
                    { id: "c", text: "A impressora" },
                    { id: "d", text: "O teclado" },
                ],
                correctOptionId: "b",
                explanation: "O transistor, criado nos Laboratórios Bell, faz o trabalho das válvulas sendo muito menor, mais rápido e gastando menos energia. Um processador moderno tem bilhões de transistores minúsculos.",
            },
            {
                id: "q7",
                prompt: "A programadora Grace Hopper ficou famosa por qual contribuição?",
                options: [
                    { id: "a", text: "Inventar o mouse" },
                    { id: "b", text: "Criar um dos primeiros compiladores, que traduziam código mais parecido com o inglês para a linguagem da máquina" },
                    { id: "c", text: "Fundar a Apple" },
                    { id: "d", text: "Criar o primeiro videogame" },
                ],
                correctOptionId: "b",
                explanation: "Grace Hopper, uma cientista e oficial da Marinha dos Estados Unidos, defendia que programar deveria ser mais próximo da linguagem humana. Ela criou um dos primeiros compiladores e influenciou a linguagem COBOL.",
            },
            {
                id: "q8",
                prompt: "Quem fundou a Apple, em 1976, começando numa garagem?",
                options: [
                    { id: "a", text: "Bill Gates e Paul Allen" },
                    { id: "b", text: "Steve Jobs e Steve Wozniak (com Ronald Wayne)" },
                    { id: "c", text: "Alan Turing e Charles Babbage" },
                    { id: "d", text: "Mark Zuckerberg" },
                ],
                correctOptionId: "b",
                explanation: "Steve Jobs e Steve Wozniak fundaram a Apple em 1976, junto com Ronald Wayne. Já a Microsoft foi fundada em 1975 por Bill Gates e Paul Allen. As duas ajudaram a levar o computador pessoal para dentro das casas.",
            },
            {
                id: "q9",
                prompt: "Quem criou a World Wide Web (a \"www\" dos sites) no CERN, em 1989?",
                options: [
                    { id: "a", text: "Tim Berners-Lee" },
                    { id: "b", text: "Steve Jobs" },
                    { id: "c", text: "Ada Lovelace" },
                    { id: "d", text: "Alan Turing" },
                ],
                correctOptionId: "a",
                explanation: "O cientista inglês Tim Berners-Lee criou a Web no CERN, um laboratório na Suíça, para compartilhar documentos usando links. Ele também criou a primeira versão do HTML, a linguagem das páginas que você estudou!",
            },
            {
                id: "q10",
                prompt: "Em que ano foi lançado o primeiro iPhone, que ajudou a popularizar os smartphones com tela touch?",
                options: [
                    { id: "a", text: "1990" },
                    { id: "b", text: "2000" },
                    { id: "c", text: "2007" },
                    { id: "d", text: "2015" },
                ],
                correctOptionId: "c",
                explanation: "O primeiro iPhone foi apresentado em 2007. Em 2008 veio o primeiro celular com Android. Desde então, o smartphone virou o computador mais usado do mundo, e ele cabe no bolso!",
            },
        ],
    },
]

export default missions
